# Table of Contents
### 1. Importing libraries and data
### 2. Data Cleaning and Wrangling
### 3. Reshaping for Modeling
### 4. Splitting the data
### 5. Optimizing Bayesian Hyperparameters
### 6. Running the CNN with new Parameters
### 7. Creating the Confusion Matrix

# 1. Importing libraries and data

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import time
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from sklearn.model_selection import cross_val_score
from keras.layers import Conv1D, Conv2D, Dense, Dropout, BatchNormalization, Flatten, MaxPooling1D
from tensorflow.keras.utils import to_categorical
from keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adagrad, Adamax, Nadam, Ftrl
from keras.callbacks import EarlyStopping, ModelCheckpoint
from scikeras.wrappers import KerasClassifier
from math import floor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import make_scorer, accuracy_score
from bayes_opt import BayesianOptimization
from sklearn.model_selection import StratifiedKFold
from keras.layers import LeakyReLU
LeakyReLU = LeakyReLU(alpha=0.1)

C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\activations\leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(

In [9]:
# Identifying a path to where data is stored

path = 'C:/Users/andyc/Machine Learning - ClimateWins'

In [11]:
# Importing the cleaned weather data set

cleancw = pd.read_csv(os.path.join(path, 'Data Sets', 'cleaned_weather.csv'), index_col = False)

In [13]:
# Importing the pleasant_weather data set

pleasant = pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_weather.csv'), index_col = False)

In [15]:
cleancw.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [17]:
pleasant.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
cleancw.shape

(22950, 137)

In [21]:
pleasant.shape

(22950, 16)

# 2. Data Cleaning and Wrangling

In [24]:
# Dropping the unnecessary columns

cleancw.drop(['DATE', 'MONTH'], axis=1, inplace=True)

In [26]:
cleancw.shape

(22950, 135)

In [28]:
pleasant.drop(columns = 'DATE', inplace = True)

In [30]:
pleasant.shape

(22950, 15)

# 3. Reshaping for Modeling

In [35]:
# Turning cleancw and pleasant dataframes from dataframes to arrays

X = np.array(cleancw)
y = np.array(pleasant)

In [37]:
X = X.reshape(-1,15,9)

In [39]:
X.shape

(22950, 15, 9)

In [41]:
# Using argmax to transform y

y =  np.argmax(y, axis = 1)
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
y.shape

(22950,)

In [45]:
# Checking y layout

from sklearn.utils.multiclass import type_of_target
type_of_target(y)

'multiclass'

Only 'multiclass' and 'binary' layouts are accepted by the Bayesian Optimization function.

# 4. Splitting the data

In [49]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 28)

In [51]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212,)
(5738, 15, 9) (5738,)

# 5. Optimizing Bayesian Hyperparameters

In [56]:
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15 # Number of weather stations

# Make scorer accuracy
score_acc = make_scorer(accuracy_score)

In [58]:
# Create function

def bay_area(neurons, activation, kernel, optimizer, learning_rate, batch_size, epochs,
              layers1, layers2, normalization, dropout, dropout_rate): 
    optimizerL = ['SGD', 'Adam', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','SGD']
    #optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
                 #'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
                 #'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
                 #'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
    activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
                   'elu', 'exponential', LeakyReLU,'relu']
    
    neurons = round(neurons)
    kernel = round(kernel)
    activation = activationL[round(activation)]  #optimizerD[optimizerL[round(optimizer)]]
    optimizer = optimizerL[round(optimizer)]
    batch_size = round(batch_size)
    
    epochs = round(epochs)
    layers1 = round(layers1)
    layers2 = round(layers2)
    
    def cnn_model():
        model = Sequential()
        model.add(Conv1D(neurons, kernel_size=kernel,activation=activation, input_shape=(timesteps, input_dim)))
        #model.add(Conv1D(32, kernel_size=1,activation='relu', input_shape=(timesteps, input_dim)))
        
        if normalization > 0.5:
            model.add(BatchNormalization())
        for i in range(layers1):
            model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
        if dropout > 0.5:
            model.add(Dropout(dropout_rate, seed=123))
        for i in range(layers2):
            model.add(Dense(neurons, activation=activation))
        model.add(MaxPooling1D())
        model.add(Flatten())
        model.add(Dense(n_classes, activation='softmax')) #sigmoid softmax
        #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        return model
    es = EarlyStopping(monitor='accuracy', mode='max', verbose=2, patience=20)
    nn = KerasClassifier(build_fn=cnn_model, epochs=epochs, batch_size=batch_size, verbose=2)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
    score = cross_val_score(nn, X_train, y_train, scoring=score_acc, cv=kfold, fit_params={'callbacks':[es]}).mean()
    return score

In [60]:
start = time.time()
params ={
    'neurons': (10, 100),
    'kernel': (1, 3),
    'activation':(0, 9), 
    'optimizer':(0,7),
    'learning_rate':(0.01, 1),
    'batch_size': (200, 1000), 
    'epochs':(20, 50),
    'layers1':(1,3),
    'layers2':(1,3),
    'normalization':(0,1),
    'dropout':(0,1),
    'dropout_rate':(0,0.3)
}

# Run Bayesian Optimization
nn_opt = BayesianOptimization(bay_area, params, random_state=28)
nn_opt.maximize(init_points=15, n_iter=4) 
print('Search took %s minutes' % ((time.time() - start)/60))

|   iter    |  target   | activa... | batch_... |  dropout  | dropou... |  epochs   |  kernel   |  layers1  |  layers2  | learni... |  neurons  | normal... | optimizer |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/43
22/22 - 3s - 157ms/step - accuracy: 0.6442 - loss: nan
Epoch 2/43
22/22 - 1s - 55ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
22/22 - 1s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
22/22 - 1s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
22/22 - 1s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
22/22 - 1s - 34ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
22/22 - 1s - 31ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
22/22 - 1s - 31ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
22/22 - 1s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
6/6 - 0s - 69ms/step

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/43
22/22 - 4s - 160ms/step - accuracy: 0.6143 - loss: nan
Epoch 2/43
22/22 - 1s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 3/43
22/22 - 1s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 4/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 5/43
22/22 - 1s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 6/43
22/22 - 1s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 7/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 8/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 9/43
22/22 - 1s - 32ms/step - accuracy: 0.6443 - loss: nan
Epoch 10/43
22/22 - 1s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 11/43
22/22 - 1s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 12/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 13/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 14/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 15/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 16/43
22/22 - 1s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 17/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 18/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 19/43
22/22 - 1s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 20/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 21/43
22/22 - 1s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 22/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 23/43
22/22 - 1s - 34ms/step - accuracy: 0.6443 - loss: nan
Epoch 24/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 25/43
22/22 - 1s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 26/43
22/22 - 1s - 33ms/step - accuracy: 0.6443 - loss: nan
Epoch 27/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 28/43
22/22 - 1s - 31ms/step - accuracy: 0.6443 - loss: nan
Epoch 29/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 30/43
22/22 - 1s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 31/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 32/43
22/22 - 1s - 34ms/step - accuracy: 0.6443 - loss: nan
Epoch 33/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 34/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 35/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 36/43
22/22 - 1s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 37/43
22/22 - 1s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 38/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 39/43
22/22 - 1s - 33ms/step - accuracy: 0.6443 - loss: nan
Epoch 40/43
22/22 - 1s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 41/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 42/43
22/22 - 1s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 43/43
22/22 - 1s - 28ms/step - accuracy: 0.6443 - loss: nan
6/6 - 0s - 70ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 4s - 174ms/step - accuracy: 0.6442 - loss: nan
Epoch 2/43
22/22 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
22/22 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
22/22 - 1s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
22/22 - 1s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
22/22 - 1s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
22/22 - 1s - 34ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
22/22 - 1s - 34ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
22/22 - 1s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
22/22 - 1s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
22/22 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000018F4A969F80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 - 0s - 66ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 4s - 167ms/step - accuracy: 0.6142 - loss: nan
Epoch 2/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
22/22 - 1s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000018F4A6862A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 - 0s - 73ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 3s - 156ms/step - accuracy: 0.6194 - loss: nan
Epoch 2/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
22/22 - 1s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
22/22 - 1s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
22/22 - 1s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
22/22 - 1s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
22/22 - 1s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
22/22 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
22/22 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
22/22 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
22/22 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
22/22 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
22/22 - 1s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
22/22 - 1s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
22/22 - 1s - 24ms/step - accuracy: 0.6442 - loss: nan
6/6 - 0s - 68ms/step
| 1         | 0.6442    | 6.561     | 649.0     | 0.125     | 0.1193    | 43.44     | 2.022     | 1.365     | 2.707     | 0.9558    | 98.58     | 0.1927    | 6.796     |
Epoch 1/29

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 - 4s - 58ms/step - accuracy: 0.6441 - loss: 1.4054
Epoch 2/29
63/63 - 1s - 18ms/step - accuracy: 0.6441 - loss: 1.2347
Epoch 3/29
63/63 - 1s - 23ms/step - accuracy: 0.6441 - loss: 1.1902
Epoch 4/29
63/63 - 1s - 20ms/step - accuracy: 0.6441 - loss: 1.1665
Epoch 5/29
63/63 - 1s - 22ms/step - accuracy: 0.6441 - loss: 1.1484
Epoch 6/29
63/63 - 1s - 20ms/step - accuracy: 0.6442 - loss: 1.1368
Epoch 7/29
63/63 - 1s - 19ms/step - accuracy: 0.6442 - loss: 1.1253
Epoch 8/29
63/63 - 2s - 24ms/step - accuracy: 0.6441 - loss: 1.1145
Epoch 9/29
63/63 - 1s - 22ms/step - accuracy: 0.6441 - loss: 1.1030
Epoch 10/29
63/63 - 2s - 39ms/step - accuracy: 0.6445 - loss: 1.0951
Epoch 11/29
63/63 - 2s - 24ms/step - accuracy: 0.6441 - loss: 1.0880
Epoch 12/29
63/63 - 3s - 41ms/step - accuracy: 0.6438 - loss: 1.0823
Epoch 13/29
63/63 - 2s - 38ms/step - accuracy: 0.6435 - loss: 1.0747
Epoch 14/29
63/63 - 2s - 24ms/step - accuracy: 0.6424 - loss: 1.0726
Epoch 15/29
63/63 - 1s - 21ms/step - accuracy: 0.6426 - loss: 1.0674
Epoch 16/29
63/63 - 1s - 15ms/step - accuracy: 0.6446 - loss: 1.0624
Epoch 17/29
63/63 - 1s - 11ms/step - accuracy: 0.6438 - loss: 1.0602
Epoch 18/29
63/63 - 1s - 13ms/step - accuracy: 0.6470 - loss: 1.0580
Epoch 19/29
63/63 - 2s - 28ms/step - accuracy: 0.6435 - loss: 1.0535
Epoch 20/29
63/63 - 1s - 22ms/step - accuracy: 0.6445 - loss: 1.0504
Epoch 21/29
63/63 - 3s - 40ms/step - accuracy: 0.6483 - loss: 1.0491
Epoch 22/29
63/63 - 1s - 23ms/step - accuracy: 0.6454 - loss: 1.0465
Epoch 23/29
63/63 - 1s - 16ms/step - accuracy: 0.6448 - loss: 1.0474
Epoch 24/29
63/63 - 1s - 22ms/step - accuracy: 0.6453 - loss: 1.0443
Epoch 25/29
63/63 - 1s - 21ms/step - accuracy: 0.6455 - loss: 1.0430
Epoch 26/29
63/63 - 1s - 19ms/step - accuracy: 0.6432 - loss: 1.0426
Epoch 27/29
63/63 - 1s - 21ms/step - accuracy: 0.6450 - loss: 1.0406
Epoch 28/29
63/63 - 3s - 41ms/step - accuracy: 0.6490 - loss: 1.0379
Epoch 29/29
63/63 - 3s - 45ms/step - accuracy: 0.6471 - loss: 1.0373
16/16 - 0s - 29ms/step
Epoch 1/29

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 - 3s - 48ms/step - accuracy: 0.5501 - loss: 1.5810
Epoch 2/29
63/63 - 1s - 21ms/step - accuracy: 0.6442 - loss: 1.2176
Epoch 3/29
63/63 - 1s - 15ms/step - accuracy: 0.6441 - loss: 1.1712
Epoch 4/29
63/63 - 1s - 12ms/step - accuracy: 0.6436 - loss: 1.1477
Epoch 5/29
63/63 - 1s - 22ms/step - accuracy: 0.6447 - loss: 1.1310
Epoch 6/29
63/63 - 1s - 13ms/step - accuracy: 0.6435 - loss: 1.1162
Epoch 7/29
63/63 - 1s - 16ms/step - accuracy: 0.6425 - loss: 1.1074
Epoch 8/29
63/63 - 1s - 23ms/step - accuracy: 0.6417 - loss: 1.0998
Epoch 9/29
63/63 - 1s - 17ms/step - accuracy: 0.6391 - loss: 1.0940
Epoch 10/29
63/63 - 1s - 23ms/step - accuracy: 0.6413 - loss: 1.0864
Epoch 11/29
63/63 - 1s - 23ms/step - accuracy: 0.6395 - loss: 1.0820
Epoch 12/29
63/63 - 3s - 41ms/step - accuracy: 0.6407 - loss: 1.0772
Epoch 13/29
63/63 - 1s - 16ms/step - accuracy: 0.6385 - loss: 1.0731
Epoch 14/29
63/63 - 1s - 21ms/step - accuracy: 0.6388 - loss: 1.0700
Epoch 15/29
63/63 - 2s - 26ms/step - accuracy: 0.6412 - loss: 1.0641
Epoch 16/29
63/63 - 1s - 21ms/step - accuracy: 0.6375 - loss: 1.0625
Epoch 17/29
63/63 - 3s - 43ms/step - accuracy: 0.6435 - loss: 1.0560
Epoch 18/29
63/63 - 3s - 42ms/step - accuracy: 0.6406 - loss: 1.0541
Epoch 19/29
63/63 - 3s - 42ms/step - accuracy: 0.6404 - loss: 1.0505
Epoch 20/29
63/63 - 1s - 21ms/step - accuracy: 0.6422 - loss: 1.0472
Epoch 21/29
63/63 - 3s - 40ms/step - accuracy: 0.6410 - loss: 1.0447
Epoch 22/29
63/63 - 1s - 17ms/step - accuracy: 0.6414 - loss: 1.0412
Epoch 23/29
63/63 - 2s - 25ms/step - accuracy: 0.6449 - loss: 1.0371
Epoch 24/29
63/63 - 3s - 40ms/step - accuracy: 0.6416 - loss: 1.0362
Epoch 25/29
63/63 - 1s - 19ms/step - accuracy: 0.6472 - loss: 1.0317
Epoch 26/29
63/63 - 1s - 22ms/step - accuracy: 0.6469 - loss: 1.0297
Epoch 27/29
63/63 - 3s - 41ms/step - accuracy: 0.6488 - loss: 1.0238
Epoch 28/29
63/63 - 1s - 22ms/step - accuracy: 0.6486 - loss: 1.0228
Epoch 29/29
63/63 - 3s - 41ms/step - accuracy: 0.6453 - loss: 1.0231
16/16 - 0s - 30ms/step
Epoch 1/29

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 - 3s - 54ms/step - accuracy: 0.4966 - loss: 1.8646
Epoch 2/29
63/63 - 1s - 20ms/step - accuracy: 0.6435 - loss: 1.1885
Epoch 3/29
63/63 - 1s - 21ms/step - accuracy: 0.6438 - loss: 1.1615
Epoch 4/29
63/63 - 3s - 42ms/step - accuracy: 0.6438 - loss: 1.1456
Epoch 5/29
63/63 - 3s - 41ms/step - accuracy: 0.6426 - loss: 1.1338
Epoch 6/29
63/63 - 1s - 15ms/step - accuracy: 0.6426 - loss: 1.1222
Epoch 7/29
63/63 - 2s - 27ms/step - accuracy: 0.6426 - loss: 1.1156
Epoch 8/29
63/63 - 2s - 35ms/step - accuracy: 0.6423 - loss: 1.1080
Epoch 9/29
63/63 - 1s - 11ms/step - accuracy: 0.6424 - loss: 1.1006
Epoch 10/29
63/63 - 1s - 12ms/step - accuracy: 0.6410 - loss: 1.0951
Epoch 11/29
63/63 - 1s - 11ms/step - accuracy: 0.6394 - loss: 1.0884
Epoch 12/29
63/63 - 1s - 13ms/step - accuracy: 0.6389 - loss: 1.0864
Epoch 13/29
63/63 - 1s - 10ms/step - accuracy: 0.6399 - loss: 1.0840
Epoch 14/29
63/63 - 1s - 11ms/step - accuracy: 0.6379 - loss: 1.0818
Epoch 15/29
63/63 - 2s - 26ms/step - accuracy: 0.6388 - loss: 1.0779
Epoch 16/29
63/63 - 2s - 26ms/step - accuracy: 0.6381 - loss: 1.0765
Epoch 17/29
63/63 - 3s - 41ms/step - accuracy: 0.6394 - loss: 1.0714
Epoch 18/29
63/63 - 1s - 19ms/step - accuracy: 0.6397 - loss: 1.0696
Epoch 19/29
63/63 - 1s - 19ms/step - accuracy: 0.6377 - loss: 1.0660
Epoch 20/29
63/63 - 1s - 13ms/step - accuracy: 0.6426 - loss: 1.0634
Epoch 21/29
63/63 - 2s - 30ms/step - accuracy: 0.6405 - loss: 1.0621
Epoch 22/29
63/63 - 1s - 18ms/step - accuracy: 0.6432 - loss: 1.0553
Epoch 23/29
63/63 - 1s - 22ms/step - accuracy: 0.6438 - loss: 1.0547
Epoch 24/29
63/63 - 1s - 22ms/step - accuracy: 0.6452 - loss: 1.0502
Epoch 25/29
63/63 - 1s - 15ms/step - accuracy: 0.6433 - loss: 1.0511
Epoch 26/29
63/63 - 1s - 21ms/step - accuracy: 0.6424 - loss: 1.0469
Epoch 27/29
63/63 - 2s - 36ms/step - accuracy: 0.6471 - loss: 1.0422
Epoch 28/29
63/63 - 2s - 28ms/step - accuracy: 0.6459 - loss: 1.0437
Epoch 29/29
63/63 - 2s - 37ms/step - accuracy: 0.6472 - loss: 1.0358
16/16 - 0s - 25ms/step
Epoch 1/29

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 - 3s - 55ms/step - accuracy: 0.4801 - loss: 1.8937
Epoch 2/29
63/63 - 1s - 21ms/step - accuracy: 0.6442 - loss: 1.1792
Epoch 3/29
63/63 - 1s - 20ms/step - accuracy: 0.6440 - loss: 1.1394
Epoch 4/29
63/63 - 1s - 17ms/step - accuracy: 0.6440 - loss: 1.1200
Epoch 5/29
63/63 - 2s - 24ms/step - accuracy: 0.6434 - loss: 1.1066
Epoch 6/29
63/63 - 2s - 24ms/step - accuracy: 0.6438 - loss: 1.0944
Epoch 7/29
63/63 - 2s - 34ms/step - accuracy: 0.6435 - loss: 1.0853
Epoch 8/29
63/63 - 1s - 21ms/step - accuracy: 0.6430 - loss: 1.0784
Epoch 9/29
63/63 - 2s - 24ms/step - accuracy: 0.6418 - loss: 1.0733
Epoch 10/29
63/63 - 3s - 40ms/step - accuracy: 0.6410 - loss: 1.0675
Epoch 11/29
63/63 - 1s - 22ms/step - accuracy: 0.6391 - loss: 1.0634
Epoch 12/29
63/63 - 2s - 37ms/step - accuracy: 0.6398 - loss: 1.0596
Epoch 13/29
63/63 - 1s - 19ms/step - accuracy: 0.6390 - loss: 1.0584
Epoch 14/29
63/63 - 1s - 23ms/step - accuracy: 0.6365 - loss: 1.0518
Epoch 15/29
63/63 - 3s - 41ms/step - accuracy: 0.6379 - loss: 1.0531
Epoch 16/29
63/63 - 2s - 37ms/step - accuracy: 0.6405 - loss: 1.0477
Epoch 17/29
63/63 - 1s - 14ms/step - accuracy: 0.6377 - loss: 1.0444
Epoch 18/29
63/63 - 1s - 14ms/step - accuracy: 0.6384 - loss: 1.0412
Epoch 19/29
63/63 - 1s - 15ms/step - accuracy: 0.6397 - loss: 1.0386
Epoch 20/29
63/63 - 1s - 15ms/step - accuracy: 0.6384 - loss: 1.0368
Epoch 21/29
63/63 - 2s - 24ms/step - accuracy: 0.6391 - loss: 1.0368
Epoch 22/29
63/63 - 2s - 25ms/step - accuracy: 0.6385 - loss: 1.0342
Epoch 23/29
63/63 - 3s - 40ms/step - accuracy: 0.6394 - loss: 1.0306
Epoch 24/29
63/63 - 3s - 44ms/step - accuracy: 0.6401 - loss: 1.0278
Epoch 25/29
63/63 - 3s - 40ms/step - accuracy: 0.6439 - loss: 1.0252
Epoch 26/29
63/63 - 2s - 39ms/step - accuracy: 0.6410 - loss: 1.0211
Epoch 27/29
63/63 - 3s - 41ms/step - accuracy: 0.6409 - loss: 1.0249
Epoch 28/29
63/63 - 1s - 21ms/step - accuracy: 0.6424 - loss: 1.0224
Epoch 29/29
63/63 - 3s - 43ms/step - accuracy: 0.6404 - loss: 1.0172
16/16 - 1s - 41ms/step
Epoch 1/29

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 - 4s - 57ms/step - accuracy: 0.6025 - loss: 1.5484
Epoch 2/29
63/63 - 1s - 22ms/step - accuracy: 0.6442 - loss: 1.1930
Epoch 3/29
63/63 - 3s - 42ms/step - accuracy: 0.6439 - loss: 1.1444
Epoch 4/29
63/63 - 3s - 40ms/step - accuracy: 0.6440 - loss: 1.1217
Epoch 5/29
63/63 - 1s - 23ms/step - accuracy: 0.6440 - loss: 1.1102
Epoch 6/29
63/63 - 1s - 23ms/step - accuracy: 0.6437 - loss: 1.0969
Epoch 7/29
63/63 - 3s - 44ms/step - accuracy: 0.6434 - loss: 1.0920
Epoch 8/29
63/63 - 1s - 22ms/step - accuracy: 0.6420 - loss: 1.0861
Epoch 9/29
63/63 - 3s - 43ms/step - accuracy: 0.6434 - loss: 1.0822
Epoch 10/29
63/63 - 3s - 42ms/step - accuracy: 0.6434 - loss: 1.0762
Epoch 11/29
63/63 - 2s - 38ms/step - accuracy: 0.6434 - loss: 1.0724
Epoch 12/29
63/63 - 1s - 13ms/step - accuracy: 0.6415 - loss: 1.0738
Epoch 13/29
63/63 - 1s - 14ms/step - accuracy: 0.6423 - loss: 1.0670
Epoch 14/29
63/63 - 2s - 27ms/step - accuracy: 0.6410 - loss: 1.0651
Epoch 15/29
63/63 - 1s - 22ms/step - accuracy: 0.6443 - loss: 1.0615
Epoch 16/29
63/63 - 1s - 22ms/step - accuracy: 0.6436 - loss: 1.0585
Epoch 17/29
63/63 - 2s - 37ms/step - accuracy: 0.6445 - loss: 1.0584
Epoch 18/29
63/63 - 1s - 21ms/step - accuracy: 0.6460 - loss: 1.0527
Epoch 19/29
63/63 - 1s - 14ms/step - accuracy: 0.6449 - loss: 1.0505
Epoch 20/29
63/63 - 1s - 14ms/step - accuracy: 0.6479 - loss: 1.0475
Epoch 21/29
63/63 - 1s - 16ms/step - accuracy: 0.6484 - loss: 1.0431
Epoch 22/29
63/63 - 1s - 15ms/step - accuracy: 0.6439 - loss: 1.0457
Epoch 23/29
63/63 - 1s - 19ms/step - accuracy: 0.6481 - loss: 1.0419
Epoch 24/29
63/63 - 1s - 17ms/step - accuracy: 0.6442 - loss: 1.0422
Epoch 25/29
63/63 - 2s - 28ms/step - accuracy: 0.6471 - loss: 1.0378
Epoch 26/29
63/63 - 1s - 21ms/step - accuracy: 0.6471 - loss: 1.0365
Epoch 27/29
63/63 - 1s - 21ms/step - accuracy: 0.6471 - loss: 1.0365
Epoch 28/29
63/63 - 1s - 19ms/step - accuracy: 0.6476 - loss: 1.0327
Epoch 29/29
63/63 - 1s - 21ms/step - accuracy: 0.6482 - loss: 1.0345
16/16 - 0s - 29ms/step
| 2         | 0.652     | 2.113     | 221.1     | 0.9461    | 0.2765    | 28.82     | 1.333     | 1.791     | 2.021     | 0.315     | 48.66     | 0.8301    | 3.937     |

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/43
14/14 - 4s - 304ms/step - accuracy: 0.6441 - loss: nan
Epoch 2/43
14/14 - 1s - 55ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
14/14 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
14/14 - 1s - 57ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
14/14 - 1s - 37ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
14/14 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
14/14 - 0s - 34ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
14/14 - 0s - 31ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
14/14 - 1s - 37ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
14/14 - 1s - 43ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
14/14 - 0s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
14/14 - 1s - 51ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
14/14 - 1s - 46ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
14/14 - 1s - 55ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
14/14 - 1s - 45ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
14/14 - 0s - 35ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
14/14 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
14/14 - 0s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
14/14 - 0s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
14/14 - 1s - 45ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
14/14 - 1s - 51ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
14/14 - 0s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
14/14 - 0s - 34ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
14/14 - 1s - 48ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
14/14 - 1s - 50ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
14/14 - 0s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
14/14 - 1s - 49ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
14/14 - 1s - 39ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
14/14 - 1s - 52ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
14/14 - 0s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
14/14 - 1s - 48ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
14/14 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
14/14 - 1s - 48ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
14/14 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
14/14 - 1s - 50ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
14/14 - 1s - 49ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 103ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

14/14 - 4s - 304ms/step - accuracy: 0.6443 - loss: nan
Epoch 2/43
14/14 - 0s - 34ms/step - accuracy: 0.6443 - loss: nan
Epoch 3/43
14/14 - 1s - 37ms/step - accuracy: 0.6443 - loss: nan
Epoch 4/43
14/14 - 0s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 5/43
14/14 - 0s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 6/43
14/14 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 7/43
14/14 - 0s - 20ms/step - accuracy: 0.6443 - loss: nan
Epoch 8/43
14/14 - 0s - 20ms/step - accuracy: 0.6443 - loss: nan
Epoch 9/43
14/14 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 10/43
14/14 - 0s - 28ms/step - accuracy: 0.6443 - loss: nan
Epoch 11/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 12/43
14/14 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 13/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 14/43
14/14 - 1s - 53ms/step - accuracy: 0.6443 - loss: nan
Epoch 15/43
14/14 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 16/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 17/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 18/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 19/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 20/43
14/14 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 21/43
14/14 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 22/43
14/14 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 23/43
14/14 - 0s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 24/43
14/14 - 0s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 25/43
14/14 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 26/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 27/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 28/43
14/14 - 0s - 33ms/step - accuracy: 0.6443 - loss: nan
Epoch 29/43
14/14 - 0s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 30/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 31/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 32/43
14/14 - 0s - 20ms/step - accuracy: 0.6443 - loss: nan
Epoch 33/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 34/43
14/14 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 35/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 36/43
14/14 - 0s - 30ms/step - accuracy: 0.6443 - loss: nan
Epoch 37/43
14/14 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 38/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 39/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 40/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 41/43
14/14 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 42/43
14/14 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 43/43
14/14 - 0s - 18ms/step - accuracy: 0.6443 - loss: nan
4/4 - 0s - 83ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

14/14 - 4s - 291ms/step - accuracy: 0.6435 - loss: nan
Epoch 2/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
14/14 - 0s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
14/14 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
14/14 - 1s - 50ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
14/14 - 1s - 47ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 93ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

14/14 - 4s - 294ms/step - accuracy: 0.6442 - loss: nan
Epoch 2/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
14/14 - 0s - 31ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
14/14 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
14/14 - 0s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
14/14 - 0s - 31ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
14/14 - 0s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
14/14 - 1s - 54ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
14/14 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
14/14 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
14/14 - 1s - 56ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
14/14 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
14/14 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
14/14 - 0s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
14/14 - 1s - 53ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
14/14 - 0s - 35ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 111ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

14/14 - 5s - 322ms/step - accuracy: 0.6441 - loss: nan
Epoch 2/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/43
14/14 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/43
14/14 - 0s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/43
14/14 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/43
14/14 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/43
14/14 - 1s - 47ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/43
14/14 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/43
14/14 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/43
14/14 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/43
14/14 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/43
14/14 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/43
14/14 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/43
14/14 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/43
14/14 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 40/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 41/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 42/43
14/14 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 43/43
14/14 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 84ms/step
| 3         | 0.6442    | 7.478     | 997.5     | 0.3326    | 0.0273    | 43.21     | 1.299     | 2.451     | 2.91      | 0.08236   | 50.24     | 0.8411    | 1.019     |
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 151ms/step - accuracy: 0.6441 - loss: nan
Epoch 2/21
17/17 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/21
17/17 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/21
17/17 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/21
17/17 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/21
17/17 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/21
17/17 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/21
17/17 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/21
17/17 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/21
17/17 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/21
17/17 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/21
17/17 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/21
17/17 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/21
17/17 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/21
17/17 - 1s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/21
17/17 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/21
17/17 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/21
17/17 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/21
17/17 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/21
17/17 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/21
17/17 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
5/5 - 0s - 77ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 192ms/step - accuracy: 0.6414 - loss: nan
Epoch 2/21
17/17 - 0s - 17ms/step - accuracy: 0.6443 - loss: nan
Epoch 3/21
17/17 - 0s - 14ms/step - accuracy: 0.6443 - loss: nan
Epoch 4/21
17/17 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 5/21
17/17 - 0s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 6/21
17/17 - 1s - 31ms/step - accuracy: 0.6443 - loss: nan
Epoch 7/21
17/17 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 8/21
17/17 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 9/21
17/17 - 1s - 37ms/step - accuracy: 0.6443 - loss: nan
Epoch 10/21
17/17 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 11/21
17/17 - 0s - 17ms/step - accuracy: 0.6443 - loss: nan
Epoch 12/21
17/17 - 0s - 16ms/step - accuracy: 0.6443 - loss: nan
Epoch 13/21
17/17 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 14/21
17/17 - 0s - 19ms/step - accuracy: 0.6443 - loss: nan
Epoch 15/21
17/17 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 16/21
17/17 - 1s - 34ms/step - accuracy: 0.6443 - loss: nan
Epoch 17/21
17/17 - 0s - 16ms/step - accuracy: 0.6443 - loss: nan
Epoch 18/21
17/17 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 19/21
17/17 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 20/21
17/17 - 1s - 34ms/step - accuracy: 0.6443 - loss: nan
Epoch 21/21
17/17 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
5/5 - 0s - 78ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 156ms/step - accuracy: 0.6442 - loss: nan
Epoch 2/21
17/17 - 1s - 46ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/21
17/17 - 1s - 34ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/21
17/17 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/21
17/17 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/21
17/17 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/21
17/17 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/21
17/17 - 1s - 33ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/21
17/17 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/21
17/17 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/21
17/17 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/21
17/17 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/21
17/17 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/21
17/17 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/21
17/17 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/21
17/17 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/21
17/17 - 1s - 43ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/21
17/17 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/21
17/17 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/21
17/17 - 1s - 43ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/21
17/17 - 1s - 39ms/step - accuracy: 0.6442 - loss: nan
5/5 - 0s - 76ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 155ms/step - accuracy: 0.6442 - loss: nan
Epoch 2/21
17/17 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/21
17/17 - 1s - 35ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/21
17/17 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/21
17/17 - 0s - 17ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/21
17/17 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/21
17/17 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/21
17/17 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/21
17/17 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/21
17/17 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/21
17/17 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/21
17/17 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/21
17/17 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/21
17/17 - 1s - 31ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/21
17/17 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/21
17/17 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/21
17/17 - 1s - 35ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/21
17/17 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/21
17/17 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/21
17/17 - 1s - 35ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/21
17/17 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
5/5 - 0s - 73ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 205ms/step - accuracy: 0.6321 - loss: nan
Epoch 2/21
17/17 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/21
17/17 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/21
17/17 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/21
17/17 - 1s - 43ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/21
17/17 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/21
17/17 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/21
17/17 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/21
17/17 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/21
17/17 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/21
17/17 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/21
17/17 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/21
17/17 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/21
17/17 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/21
17/17 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/21
17/17 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/21
17/17 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/21
17/17 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/21
17/17 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/21
17/17 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/21
17/17 - 0s - 17ms/step - accuracy: 0.6442 - loss: nan
5/5 - 0s - 64ms/step
| 4         | 0.6442    | 6.887     | 825.4     | 0.6751    | 0.03951   | 21.18     | 2.312     | 1.502     | 2.977     | 0.538     | 15.33     | 0.6988    | 4.39      |
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

42/42 - 4s - 84ms/step - accuracy: 0.4637 - loss: 1.7005
Epoch 2/43
42/42 - 1s - 28ms/step - accuracy: 0.6363 - loss: 1.0719
Epoch 3/43
42/42 - 0s - 9ms/step - accuracy: 0.6463 - loss: 1.0330
Epoch 4/43
42/42 - 1s - 22ms/step - accuracy: 0.6592 - loss: 0.9951
Epoch 5/43
42/42 - 1s - 17ms/step - accuracy: 0.6732 - loss: 0.9556
Epoch 6/43
42/42 - 1s - 14ms/step - accuracy: 0.6803 - loss: 0.9207
Epoch 7/43
42/42 - 1s - 18ms/step - accuracy: 0.6928 - loss: 0.8858
Epoch 8/43
42/42 - 0s - 9ms/step - accuracy: 0.6987 - loss: 0.8660
Epoch 9/43
42/42 - 1s - 23ms/step - accuracy: 0.7072 - loss: 0.8462
Epoch 10/43
42/42 - 1s - 16ms/step - accuracy: 0.7101 - loss: 0.8323
Epoch 11/43
42/42 - 1s - 32ms/step - accuracy: 0.7117 - loss: 0.8219
Epoch 12/43
42/42 - 1s - 31ms/step - accuracy: 0.7108 - loss: 0.8123
Epoch 13/43
42/42 - 1s - 16ms/step - accuracy: 0.7189 - loss: 0.7989
Epoch 14/43
42/42 - 1s - 15ms/step - accuracy: 0.7237 - loss: 0.7865
Epoch 15/43
42/42 - 1s - 14ms/step - accuracy: 0.7229 - loss: 0.7824
Epoch 16/43
42/42 - 1s - 17ms/step - accuracy: 0.7244 - loss: 0.7720
Epoch 17/43
42/42 - 1s - 15ms/step - accuracy: 0.7277 - loss: 0.7635
Epoch 18/43
42/42 - 1s - 13ms/step - accuracy: 0.7296 - loss: 0.7512
Epoch 19/43
42/42 - 1s - 12ms/step - accuracy: 0.7332 - loss: 0.7494
Epoch 20/43
42/42 - 1s - 19ms/step - accuracy: 0.7339 - loss: 0.7388
Epoch 21/43
42/42 - 1s - 18ms/step - accuracy: 0.7399 - loss: 0.7339
Epoch 22/43
42/42 - 1s - 31ms/step - accuracy: 0.7444 - loss: 0.7222
Epoch 23/43
42/42 - 1s - 31ms/step - accuracy: 0.7452 - loss: 0.7188
Epoch 24/43
42/42 - 1s - 26ms/step - accuracy: 0.7454 - loss: 0.7105
Epoch 25/43
42/42 - 1s - 19ms/step - accuracy: 0.7491 - loss: 0.7054
Epoch 26/43
42/42 - 1s - 17ms/step - accuracy: 0.7541 - loss: 0.6968
Epoch 27/43
42/42 - 1s - 19ms/step - accuracy: 0.7590 - loss: 0.6862
Epoch 28/43
42/42 - 1s - 30ms/step - accuracy: 0.7606 - loss: 0.6800
Epoch 29/43
42/42 - 1s - 32ms/step - accuracy: 0.7640 - loss: 0.6718
Epoch 30/43
42/42 - 1s - 17ms/step - accuracy: 0.7654 - loss: 0.6655
Epoch 31/43
42/42 - 1s - 32ms/step - accuracy: 0.7695 - loss: 0.6544
Epoch 32/43
42/42 - 1s - 31ms/step - accuracy: 0.7726 - loss: 0.6523
Epoch 33/43
42/42 - 1s - 30ms/step - accuracy: 0.7757 - loss: 0.6432
Epoch 34/43
42/42 - 1s - 18ms/step - accuracy: 0.7762 - loss: 0.6369
Epoch 35/43
42/42 - 1s - 28ms/step - accuracy: 0.7773 - loss: 0.6291
Epoch 36/43
42/42 - 1s - 16ms/step - accuracy: 0.7800 - loss: 0.6235
Epoch 37/43
42/42 - 1s - 17ms/step - accuracy: 0.7820 - loss: 0.6169
Epoch 38/43
42/42 - 1s - 13ms/step - accuracy: 0.7810 - loss: 0.6120
Epoch 39/43
42/42 - 1s - 16ms/step - accuracy: 0.7868 - loss: 0.6013
Epoch 40/43
42/42 - 1s - 32ms/step - accuracy: 0.7889 - loss: 0.5944
Epoch 41/43
42/42 - 1s - 15ms/step - accuracy: 0.7923 - loss: 0.5905
Epoch 42/43
42/42 - 1s - 19ms/step - accuracy: 0.7944 - loss: 0.5835
Epoch 43/43
42/42 - 1s - 28ms/step - accuracy: 0.7962 - loss: 0.5725
11/11 - 1s - 47ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

42/42 - 5s - 109ms/step - accuracy: 0.5633 - loss: 1.3530
Epoch 2/43
42/42 - 1s - 17ms/step - accuracy: 0.6447 - loss: 1.0507
Epoch 3/43
42/42 - 1s - 17ms/step - accuracy: 0.6488 - loss: 1.0078
Epoch 4/43
42/42 - 1s - 32ms/step - accuracy: 0.6583 - loss: 0.9712
Epoch 5/43
42/42 - 1s - 31ms/step - accuracy: 0.6618 - loss: 0.9424
Epoch 6/43
42/42 - 1s - 33ms/step - accuracy: 0.6770 - loss: 0.9146
Epoch 7/43
42/42 - 1s - 27ms/step - accuracy: 0.6842 - loss: 0.8910
Epoch 8/43
42/42 - 1s - 19ms/step - accuracy: 0.6892 - loss: 0.8757
Epoch 9/43
42/42 - 0s - 10ms/step - accuracy: 0.6982 - loss: 0.8590
Epoch 10/43
42/42 - 1s - 23ms/step - accuracy: 0.7009 - loss: 0.8473
Epoch 11/43
42/42 - 1s - 15ms/step - accuracy: 0.7071 - loss: 0.8302
Epoch 12/43
42/42 - 0s - 9ms/step - accuracy: 0.7103 - loss: 0.8202
Epoch 13/43
42/42 - 1s - 20ms/step - accuracy: 0.7134 - loss: 0.8091
Epoch 14/43
42/42 - 1s - 14ms/step - accuracy: 0.7239 - loss: 0.7975
Epoch 15/43
42/42 - 1s - 16ms/step - accuracy: 0.7251 - loss: 0.7892
Epoch 16/43
42/42 - 0s - 10ms/step - accuracy: 0.7284 - loss: 0.7753
Epoch 17/43
42/42 - 0s - 8ms/step - accuracy: 0.7306 - loss: 0.7670
Epoch 18/43
42/42 - 0s - 10ms/step - accuracy: 0.7352 - loss: 0.7603
Epoch 19/43
42/42 - 0s - 11ms/step - accuracy: 0.7400 - loss: 0.7509
Epoch 20/43
42/42 - 0s - 8ms/step - accuracy: 0.7399 - loss: 0.7445
Epoch 21/43
42/42 - 0s - 12ms/step - accuracy: 0.7473 - loss: 0.7317
Epoch 22/43
42/42 - 0s - 11ms/step - accuracy: 0.7452 - loss: 0.7285
Epoch 23/43
42/42 - 1s - 14ms/step - accuracy: 0.7510 - loss: 0.7159
Epoch 24/43
42/42 - 1s - 13ms/step - accuracy: 0.7544 - loss: 0.7098
Epoch 25/43
42/42 - 1s - 13ms/step - accuracy: 0.7586 - loss: 0.7017
Epoch 26/43
42/42 - 1s - 13ms/step - accuracy: 0.7618 - loss: 0.6924
Epoch 27/43
42/42 - 1s - 16ms/step - accuracy: 0.7640 - loss: 0.6810
Epoch 28/43
42/42 - 1s - 31ms/step - accuracy: 0.7670 - loss: 0.6764
Epoch 29/43
42/42 - 1s - 17ms/step - accuracy: 0.7674 - loss: 0.6727
Epoch 30/43
42/42 - 1s - 27ms/step - accuracy: 0.7709 - loss: 0.6615
Epoch 31/43
42/42 - 1s - 23ms/step - accuracy: 0.7741 - loss: 0.6574
Epoch 32/43
42/42 - 1s - 30ms/step - accuracy: 0.7785 - loss: 0.6474
Epoch 33/43
42/42 - 1s - 18ms/step - accuracy: 0.7801 - loss: 0.6405
Epoch 34/43
42/42 - 1s - 27ms/step - accuracy: 0.7795 - loss: 0.6350
Epoch 35/43
42/42 - 1s - 15ms/step - accuracy: 0.7848 - loss: 0.6259
Epoch 36/43
42/42 - 1s - 19ms/step - accuracy: 0.7844 - loss: 0.6200
Epoch 37/43
42/42 - 1s - 31ms/step - accuracy: 0.7927 - loss: 0.6068
Epoch 38/43
42/42 - 1s - 32ms/step - accuracy: 0.7950 - loss: 0.5998
Epoch 39/43
42/42 - 1s - 29ms/step - accuracy: 0.7939 - loss: 0.5969
Epoch 40/43
42/42 - 1s - 18ms/step - accuracy: 0.7967 - loss: 0.5867
Epoch 41/43
42/42 - 1s - 18ms/step - accuracy: 0.8020 - loss: 0.5788
Epoch 42/43
42/42 - 1s - 28ms/step - accuracy: 0.8024 - loss: 0.5722
Epoch 43/43
42/42 - 1s - 16ms/step - accuracy: 0.8075 - loss: 0.5613
11/11 - 0s - 42ms/step

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/43
42/42 - 4s - 87ms/step - accuracy: 0.6406 - loss: 1.2652
Epoch 2/43
42/42 - 1s - 31ms/step - accuracy: 0.6643 - loss: 1.0290
Epoch 3/43
42/42 - 1s - 16ms/step - accuracy: 0.6688 - loss: 0.9682
Epoch 4/43
42/42 - 1s - 31ms/step - accuracy: 0.6777 - loss: 0.9304
Epoch 5/43
42/42 - 1s - 32ms/step - accuracy: 0.6841 - loss: 0.9086
Epoch 6/43
42/42 - 1s - 32ms/step - accuracy: 0.6912 - loss: 0.8818
Epoch 7/43
42/42 - 1s - 17ms/step - accuracy: 0.6924 - loss: 0.8679
Epoch 8/43
42/42 - 1s - 32ms/step - accuracy: 0.7027 - loss: 0.8467
Epoch 9/43
42/42 - 1s - 31ms/step - accuracy: 0.7078 - loss: 0.8360
Epoch 10/43
42/42 - 1s - 28ms/step - accuracy: 0.7124 - loss: 0.8208
Epoch 11/43
42/42 - 1s - 15ms/step - accuracy: 0.7132 - loss: 0.8089
Epoch 12/43
42/42 - 1s - 21ms/step - accuracy: 0.7192 - loss: 0.7950
Epoch 13/43
42/42 - 1s - 28ms/step - accuracy: 0.7231 - loss: 0.7875
Epoch 14/43
42/42 - 1s - 18ms/step - accuracy: 0.7271 - loss: 0.7766
Epoch 15/43
42/42 - 1s - 14ms/step - accuracy: 0.7319 - loss: 0.7645
Epoch 16/43
42/42 - 1s - 14ms/step - accuracy: 0.7347 - loss: 0.7535
Epoch 17/43
42/42 - 0s - 9ms/step - accuracy: 0.7361 - loss: 0.7502
Epoch 18/43
42/42 - 1s - 12ms/step - accuracy: 0.7430 - loss: 0.7404
Epoch 19/43
42/42 - 1s - 20ms/step - accuracy: 0.7495 - loss: 0.7287
Epoch 20/43
42/42 - 1s - 31ms/step - accuracy: 0.7517 - loss: 0.7231
Epoch 21/43
42/42 - 1s - 18ms/step - accuracy: 0.7507 - loss: 0.7159
Epoch 22/43
42/42 - 1s - 25ms/step - accuracy: 0.7595 - loss: 0.7065
Epoch 23/43
42/42 - 1s - 21ms/step - accuracy: 0.7569 - loss: 0.6973
Epoch 24/43
42/42 - 1s - 31ms/step - accuracy: 0.7605 - loss: 0.6920
Epoch 25/43
42/42 - 1s - 32ms/step - accuracy: 0.7610 - loss: 0.6859
Epoch 26/43
42/42 - 1s - 30ms/step - accuracy: 0.7635 - loss: 0.6789
Epoch 27/43
42/42 - 0s - 10ms/step - accuracy: 0.7676 - loss: 0.6743
Epoch 28/43
42/42 - 1s - 15ms/step - accuracy: 0.7723 - loss: 0.6660
Epoch 29/43
42/42 - 0s - 10ms/step - accuracy: 0.7746 - loss: 0.6583
Epoch 30/43
42/42 - 1s - 17ms/step - accuracy: 0.7752 - loss: 0.6573
Epoch 31/43
42/42 - 0s - 9ms/step - accuracy: 0.7729 - loss: 0.6485
Epoch 32/43
42/42 - 1s - 19ms/step - accuracy: 0.7781 - loss: 0.6372
Epoch 33/43
42/42 - 1s - 16ms/step - accuracy: 0.7840 - loss: 0.6321
Epoch 34/43
42/42 - 1s - 14ms/step - accuracy: 0.7848 - loss: 0.6233
Epoch 35/43
42/42 - 0s - 10ms/step - accuracy: 0.7836 - loss: 0.6205
Epoch 36/43
42/42 - 0s - 10ms/step - accuracy: 0.7862 - loss: 0.6103
Epoch 37/43
42/42 - 1s - 16ms/step - accuracy: 0.7914 - loss: 0.6047
Epoch 38/43
42/42 - 1s - 16ms/step - accuracy: 0.7916 - loss: 0.5982
Epoch 39/43
42/42 - 1s - 12ms/step - accuracy: 0.7960 - loss: 0.5903
Epoch 40/43
42/42 - 1s - 20ms/step - accuracy: 0.7978 - loss: 0.5822
Epoch 41/43
42/42 - 1s - 25ms/step - accuracy: 0.7986 - loss: 0.5755
Epoch 42/43
42/42 - 1s - 15ms/step - accuracy: 0.8017 - loss: 0.5658
Epoch 43/43
42/42 - 1s - 18ms/step - accuracy: 0.8051 - loss: 0.5576
11/11 - 0s - 25ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

42/42 - 3s - 77ms/step - accuracy: 0.5139 - loss: 1.6082
Epoch 2/43
42/42 - 1s - 33ms/step - accuracy: 0.6400 - loss: 1.0609
Epoch 3/43
42/42 - 1s - 30ms/step - accuracy: 0.6571 - loss: 1.0099
Epoch 4/43
42/42 - 1s - 27ms/step - accuracy: 0.6646 - loss: 0.9757
Epoch 5/43
42/42 - 1s - 16ms/step - accuracy: 0.6771 - loss: 0.9393
Epoch 6/43
42/42 - 1s - 28ms/step - accuracy: 0.6855 - loss: 0.9079
Epoch 7/43
42/42 - 0s - 11ms/step - accuracy: 0.6927 - loss: 0.8816
Epoch 8/43
42/42 - 1s - 18ms/step - accuracy: 0.7028 - loss: 0.8580
Epoch 9/43
42/42 - 1s - 16ms/step - accuracy: 0.7096 - loss: 0.8392
Epoch 10/43
42/42 - 1s - 20ms/step - accuracy: 0.7184 - loss: 0.8220
Epoch 11/43
42/42 - 1s - 30ms/step - accuracy: 0.7224 - loss: 0.8060
Epoch 12/43
42/42 - 1s - 18ms/step - accuracy: 0.7275 - loss: 0.7933
Epoch 13/43
42/42 - 1s - 16ms/step - accuracy: 0.7319 - loss: 0.7824
Epoch 14/43
42/42 - 1s - 30ms/step - accuracy: 0.7362 - loss: 0.7678
Epoch 15/43
42/42 - 1s - 17ms/step - accuracy: 0.7404 - loss: 0.7564
Epoch 16/43
42/42 - 1s - 12ms/step - accuracy: 0.7454 - loss: 0.7482
Epoch 17/43
42/42 - 1s - 20ms/step - accuracy: 0.7487 - loss: 0.7372
Epoch 18/43
42/42 - 0s - 12ms/step - accuracy: 0.7490 - loss: 0.7276
Epoch 19/43
42/42 - 0s - 10ms/step - accuracy: 0.7540 - loss: 0.7172
Epoch 20/43
42/42 - 0s - 11ms/step - accuracy: 0.7574 - loss: 0.7080
Epoch 21/43
42/42 - 1s - 13ms/step - accuracy: 0.7617 - loss: 0.6937
Epoch 22/43
42/42 - 1s - 12ms/step - accuracy: 0.7630 - loss: 0.6879
Epoch 23/43
42/42 - 1s - 20ms/step - accuracy: 0.7686 - loss: 0.6774
Epoch 24/43
42/42 - 1s - 14ms/step - accuracy: 0.7714 - loss: 0.6679
Epoch 25/43
42/42 - 1s - 14ms/step - accuracy: 0.7741 - loss: 0.6609
Epoch 26/43
42/42 - 1s - 16ms/step - accuracy: 0.7742 - loss: 0.6542
Epoch 27/43
42/42 - 1s - 17ms/step - accuracy: 0.7802 - loss: 0.6473
Epoch 28/43
42/42 - 1s - 12ms/step - accuracy: 0.7826 - loss: 0.6374
Epoch 29/43
42/42 - 1s - 19ms/step - accuracy: 0.7812 - loss: 0.6301
Epoch 30/43
42/42 - 1s - 13ms/step - accuracy: 0.7834 - loss: 0.6278
Epoch 31/43
42/42 - 1s - 12ms/step - accuracy: 0.7875 - loss: 0.6155
Epoch 32/43
42/42 - 1s - 21ms/step - accuracy: 0.7909 - loss: 0.6074
Epoch 33/43
42/42 - 1s - 12ms/step - accuracy: 0.7943 - loss: 0.6003
Epoch 34/43
42/42 - 0s - 11ms/step - accuracy: 0.7969 - loss: 0.5970
Epoch 35/43
42/42 - 1s - 13ms/step - accuracy: 0.7943 - loss: 0.5916
Epoch 36/43
42/42 - 1s - 17ms/step - accuracy: 0.7945 - loss: 0.5851
Epoch 37/43
42/42 - 0s - 9ms/step - accuracy: 0.8004 - loss: 0.5753
Epoch 38/43
42/42 - 1s - 15ms/step - accuracy: 0.8051 - loss: 0.5653
Epoch 39/43
42/42 - 1s - 17ms/step - accuracy: 0.8094 - loss: 0.5592
Epoch 40/43
42/42 - 1s - 30ms/step - accuracy: 0.8103 - loss: 0.5568
Epoch 41/43
42/42 - 1s - 16ms/step - accuracy: 0.8130 - loss: 0.5413
Epoch 42/43
42/42 - 1s - 30ms/step - accuracy: 0.8174 - loss: 0.5386
Epoch 43/43
42/42 - 1s - 12ms/step - accuracy: 0.8165 - loss: 0.5338
11/11 - 0s - 34ms/step
Epoch 1/43

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

42/42 - 4s - 106ms/step - accuracy: 0.5220 - loss: 1.7053
Epoch 2/43
42/42 - 1s - 15ms/step - accuracy: 0.6456 - loss: 1.0956
Epoch 3/43
42/42 - 1s - 14ms/step - accuracy: 0.6511 - loss: 1.0459
Epoch 4/43
42/42 - 1s - 14ms/step - accuracy: 0.6587 - loss: 1.0161
Epoch 5/43
42/42 - 0s - 9ms/step - accuracy: 0.6609 - loss: 0.9857
Epoch 6/43
42/42 - 1s - 20ms/step - accuracy: 0.6694 - loss: 0.9593
Epoch 7/43
42/42 - 1s - 13ms/step - accuracy: 0.6778 - loss: 0.9309
Epoch 8/43
42/42 - 1s - 18ms/step - accuracy: 0.6809 - loss: 0.9093
Epoch 9/43
42/42 - 1s - 12ms/step - accuracy: 0.6900 - loss: 0.8874
Epoch 10/43
42/42 - 1s - 20ms/step - accuracy: 0.6955 - loss: 0.8673
Epoch 11/43
42/42 - 1s - 15ms/step - accuracy: 0.7012 - loss: 0.8554
Epoch 12/43
42/42 - 1s - 13ms/step - accuracy: 0.7035 - loss: 0.8431
Epoch 13/43
42/42 - 0s - 12ms/step - accuracy: 0.7069 - loss: 0.8340
Epoch 14/43
42/42 - 1s - 17ms/step - accuracy: 0.7084 - loss: 0.8198
Epoch 15/43
42/42 - 1s - 13ms/step - accuracy: 0.7144 - loss: 0.8150
Epoch 16/43
42/42 - 1s - 16ms/step - accuracy: 0.7174 - loss: 0.8029
Epoch 17/43
42/42 - 1s - 17ms/step - accuracy: 0.7226 - loss: 0.7950
Epoch 18/43
42/42 - 1s - 30ms/step - accuracy: 0.7272 - loss: 0.7844
Epoch 19/43
42/42 - 1s - 17ms/step - accuracy: 0.7315 - loss: 0.7755
Epoch 20/43
42/42 - 1s - 30ms/step - accuracy: 0.7322 - loss: 0.7689
Epoch 21/43
42/42 - 0s - 11ms/step - accuracy: 0.7354 - loss: 0.7585
Epoch 22/43
42/42 - 1s - 21ms/step - accuracy: 0.7365 - loss: 0.7485
Epoch 23/43
42/42 - 1s - 29ms/step - accuracy: 0.7406 - loss: 0.7451
Epoch 24/43
42/42 - 1s - 13ms/step - accuracy: 0.7448 - loss: 0.7358
Epoch 25/43
42/42 - 0s - 8ms/step - accuracy: 0.7442 - loss: 0.7321
Epoch 26/43
42/42 - 0s - 9ms/step - accuracy: 0.7486 - loss: 0.7236
Epoch 27/43
42/42 - 0s - 10ms/step - accuracy: 0.7540 - loss: 0.7107
Epoch 28/43
42/42 - 0s - 9ms/step - accuracy: 0.7524 - loss: 0.7104
Epoch 29/43
42/42 - 0s - 11ms/step - accuracy: 0.7589 - loss: 0.7016
Epoch 30/43
42/42 - 0s - 10ms/step - accuracy: 0.7596 - loss: 0.6957
Epoch 31/43
42/42 - 1s - 15ms/step - accuracy: 0.7609 - loss: 0.6897
Epoch 32/43
42/42 - 0s - 10ms/step - accuracy: 0.7685 - loss: 0.6792
Epoch 33/43
42/42 - 0s - 10ms/step - accuracy: 0.7667 - loss: 0.6775
Epoch 34/43
42/42 - 0s - 11ms/step - accuracy: 0.7702 - loss: 0.6694
Epoch 35/43
42/42 - 0s - 9ms/step - accuracy: 0.7691 - loss: 0.6664
Epoch 36/43
42/42 - 1s - 13ms/step - accuracy: 0.7739 - loss: 0.6562
Epoch 37/43
42/42 - 0s - 12ms/step - accuracy: 0.7730 - loss: 0.6480
Epoch 38/43
42/42 - 1s - 16ms/step - accuracy: 0.7778 - loss: 0.6429
Epoch 39/43
42/42 - 1s - 16ms/step - accuracy: 0.7768 - loss: 0.6404
Epoch 40/43
42/42 - 1s - 20ms/step - accuracy: 0.7794 - loss: 0.6340
Epoch 41/43
42/42 - 1s - 31ms/step - accuracy: 0.7826 - loss: 0.6276
Epoch 42/43
42/42 - 1s - 33ms/step - accuracy: 0.7843 - loss: 0.6209
Epoch 43/43
42/42 - 1s - 17ms/step - accuracy: 0.7841 - loss: 0.6155
11/11 - 0s - 34ms/step
| 5         | 0.8084    | 8.062     | 329.5     | 0.6104    | 0.0951    | 42.9      | 1.313     | 2.86      | 1.996     | 0.8349    | 30.7      | 0.1068    | 4.716     |

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/42
16/16 - 2s - 114ms/step - accuracy: 0.4929 - loss: 1.9391
Epoch 2/42
16/16 - 0s - 28ms/step - accuracy: 0.6347 - loss: 1.2068
Epoch 3/42
16/16 - 1s - 39ms/step - accuracy: 0.6503 - loss: 1.0828
Epoch 4/42
16/16 - 0s - 21ms/step - accuracy: 0.6600 - loss: 1.0276
Epoch 5/42
16/16 - 0s - 28ms/step - accuracy: 0.6666 - loss: 0.9935
Epoch 6/42
16/16 - 1s - 41ms/step - accuracy: 0.6740 - loss: 0.9721
Epoch 7/42
16/16 - 1s - 43ms/step - accuracy: 0.6773 - loss: 0.9532
Epoch 8/42
16/16 - 1s - 45ms/step - accuracy: 0.6831 - loss: 0.9352
Epoch 9/42
16/16 - 1s - 46ms/step - accuracy: 0.6811 - loss: 0.9213
Epoch 10/42
16/16 - 0s - 26ms/step - accuracy: 0.6881 - loss: 0.9061
Epoch 11/42
16/16 - 1s - 49ms/step - accuracy: 0.6884 - loss: 0.8979
Epoch 12/42
16/16 - 1s - 42ms/step - accuracy: 0.6916 - loss: 0.8866
Epoch 13/42
16/16 - 1s - 37ms/step - accuracy: 0.6980 - loss: 0.8764
Epoch 14/42
16/16 - 1s - 44ms/step - accuracy: 0.6974 - loss: 0.8706
Epoch 15/42
16/16 - 1s - 40ms/step - accuracy: 0.7037 - loss: 0.8599
Epoch 16/42
16/16 - 0s - 28ms/step - accuracy: 0.7050 - loss: 0.8512
Epoch 17/42
16/16 - 1s - 36ms/step - accuracy: 0.7059 - loss: 0.8469
Epoch 18/42
16/16 - 1s - 47ms/step - accuracy: 0.7089 - loss: 0.8382
Epoch 19/42
16/16 - 1s - 35ms/step - accuracy: 0.7125 - loss: 0.8306
Epoch 20/42
16/16 - 0s - 27ms/step - accuracy: 0.7133 - loss: 0.8242
Epoch 21/42
16/16 - 1s - 36ms/step - accuracy: 0.7167 - loss: 0.8188
Epoch 22/42
16/16 - 1s - 34ms/step - accuracy: 0.7179 - loss: 0.8131
Epoch 23/42
16/16 - 0s - 19ms/step - accuracy: 0.7213 - loss: 0.8046
Epoch 24/42
16/16 - 1s - 32ms/step - accuracy: 0.7237 - loss: 0.8004
Epoch 25/42
16/16 - 0s - 28ms/step - accuracy: 0.7226 - loss: 0.7953
Epoch 26/42
16/16 - 1s - 37ms/step - accuracy: 0.7257 - loss: 0.7853
Epoch 27/42
16/16 - 1s - 34ms/step - accuracy: 0.7224 - loss: 0.7859
Epoch 28/42
16/16 - 1s - 39ms/step - accuracy: 0.7287 - loss: 0.7773
Epoch 29/42
16/16 - 1s - 42ms/step - accuracy: 0.7284 - loss: 0.7718
Epoch 30/42
16/16 - 1s - 34ms/step - accuracy: 0.7316 - loss: 0.7708
Epoch 31/42
16/16 - 0s - 23ms/step - accuracy: 0.7322 - loss: 0.7667
Epoch 32/42
16/16 - 1s - 43ms/step - accuracy: 0.7314 - loss: 0.7648
Epoch 33/42
16/16 - 1s - 53ms/step - accuracy: 0.7393 - loss: 0.7535
Epoch 34/42
16/16 - 1s - 33ms/step - accuracy: 0.7408 - loss: 0.7529
Epoch 35/42
16/16 - 1s - 41ms/step - accuracy: 0.7385 - loss: 0.7489
Epoch 36/42
16/16 - 1s - 45ms/step - accuracy: 0.7410 - loss: 0.7452
Epoch 37/42
16/16 - 1s - 42ms/step - accuracy: 0.7438 - loss: 0.7433
Epoch 38/42
16/16 - 0s - 27ms/step - accuracy: 0.7424 - loss: 0.7361
Epoch 39/42
16/16 - 1s - 46ms/step - accuracy: 0.7465 - loss: 0.7326
Epoch 40/42
16/16 - 1s - 35ms/step - accuracy: 0.7490 - loss: 0.7291
Epoch 41/42
16/16 - 1s - 47ms/step - accuracy: 0.7474 - loss: 0.7258
Epoch 42/42
16/16 - 0s - 26ms/step - accuracy: 0.7443 - loss: 0.7227
4/4 - 0s - 89ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 2s - 126ms/step - accuracy: 0.4419 - loss: 2.3097
Epoch 2/42
16/16 - 1s - 42ms/step - accuracy: 0.6364 - loss: 1.2666
Epoch 3/42
16/16 - 1s - 40ms/step - accuracy: 0.6550 - loss: 1.1150
Epoch 4/42
16/16 - 0s - 26ms/step - accuracy: 0.6622 - loss: 1.0402
Epoch 5/42
16/16 - 1s - 45ms/step - accuracy: 0.6685 - loss: 1.0006
Epoch 6/42
16/16 - 1s - 35ms/step - accuracy: 0.6735 - loss: 0.9790
Epoch 7/42
16/16 - 1s - 42ms/step - accuracy: 0.6768 - loss: 0.9642
Epoch 8/42
16/16 - 0s - 28ms/step - accuracy: 0.6766 - loss: 0.9488
Epoch 9/42
16/16 - 1s - 43ms/step - accuracy: 0.6797 - loss: 0.9370
Epoch 10/42
16/16 - 1s - 45ms/step - accuracy: 0.6859 - loss: 0.9239
Epoch 11/42
16/16 - 1s - 38ms/step - accuracy: 0.6892 - loss: 0.9112
Epoch 12/42
16/16 - 1s - 44ms/step - accuracy: 0.6902 - loss: 0.9079
Epoch 13/42
16/16 - 1s - 45ms/step - accuracy: 0.6929 - loss: 0.8974
Epoch 14/42
16/16 - 1s - 39ms/step - accuracy: 0.6953 - loss: 0.8836
Epoch 15/42
16/16 - 1s - 36ms/step - accuracy: 0.6982 - loss: 0.8775
Epoch 16/42
16/16 - 1s - 47ms/step - accuracy: 0.7028 - loss: 0.8677
Epoch 17/42
16/16 - 1s - 41ms/step - accuracy: 0.7047 - loss: 0.8637
Epoch 18/42
16/16 - 1s - 37ms/step - accuracy: 0.7049 - loss: 0.8544
Epoch 19/42
16/16 - 0s - 24ms/step - accuracy: 0.7068 - loss: 0.8502
Epoch 20/42
16/16 - 1s - 46ms/step - accuracy: 0.7118 - loss: 0.8412
Epoch 21/42
16/16 - 1s - 40ms/step - accuracy: 0.7143 - loss: 0.8378
Epoch 22/42
16/16 - 1s - 39ms/step - accuracy: 0.7165 - loss: 0.8263
Epoch 23/42
16/16 - 1s - 50ms/step - accuracy: 0.7176 - loss: 0.8232
Epoch 24/42
16/16 - 1s - 41ms/step - accuracy: 0.7223 - loss: 0.8173
Epoch 25/42
16/16 - 1s - 36ms/step - accuracy: 0.7232 - loss: 0.8112
Epoch 26/42
16/16 - 1s - 43ms/step - accuracy: 0.7271 - loss: 0.8079
Epoch 27/42
16/16 - 1s - 36ms/step - accuracy: 0.7265 - loss: 0.8050
Epoch 28/42
16/16 - 1s - 35ms/step - accuracy: 0.7324 - loss: 0.7959
Epoch 29/42
16/16 - 1s - 42ms/step - accuracy: 0.7298 - loss: 0.7912
Epoch 30/42
16/16 - 1s - 46ms/step - accuracy: 0.7322 - loss: 0.7881
Epoch 31/42
16/16 - 1s - 46ms/step - accuracy: 0.7357 - loss: 0.7827
Epoch 32/42
16/16 - 1s - 37ms/step - accuracy: 0.7356 - loss: 0.7804
Epoch 33/42
16/16 - 0s - 18ms/step - accuracy: 0.7381 - loss: 0.7766
Epoch 34/42
16/16 - 0s - 14ms/step - accuracy: 0.7420 - loss: 0.7704
Epoch 35/42
16/16 - 0s - 26ms/step - accuracy: 0.7392 - loss: 0.7691
Epoch 36/42
16/16 - 0s - 22ms/step - accuracy: 0.7406 - loss: 0.7618
Epoch 37/42
16/16 - 0s - 19ms/step - accuracy: 0.7429 - loss: 0.7623
Epoch 38/42
16/16 - 0s - 14ms/step - accuracy: 0.7431 - loss: 0.7565
Epoch 39/42
16/16 - 0s - 19ms/step - accuracy: 0.7443 - loss: 0.7577
Epoch 40/42
16/16 - 0s - 22ms/step - accuracy: 0.7457 - loss: 0.7499
Epoch 41/42
16/16 - 0s - 20ms/step - accuracy: 0.7494 - loss: 0.7477
Epoch 42/42
16/16 - 0s - 20ms/step - accuracy: 0.7482 - loss: 0.7454
4/4 - 0s - 64ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 2s - 97ms/step - accuracy: 0.5106 - loss: 1.7047
Epoch 2/42
16/16 - 0s - 20ms/step - accuracy: 0.6579 - loss: 1.1358
Epoch 3/42
16/16 - 0s - 21ms/step - accuracy: 0.6649 - loss: 1.0408
Epoch 4/42
16/16 - 0s - 30ms/step - accuracy: 0.6760 - loss: 0.9902
Epoch 5/42
16/16 - 1s - 48ms/step - accuracy: 0.6802 - loss: 0.9616
Epoch 6/42
16/16 - 0s - 30ms/step - accuracy: 0.6846 - loss: 0.9410
Epoch 7/42
16/16 - 1s - 49ms/step - accuracy: 0.6885 - loss: 0.9233
Epoch 8/42
16/16 - 0s - 25ms/step - accuracy: 0.6944 - loss: 0.9060
Epoch 9/42
16/16 - 0s - 17ms/step - accuracy: 0.6969 - loss: 0.8916
Epoch 10/42
16/16 - 1s - 33ms/step - accuracy: 0.7030 - loss: 0.8765
Epoch 11/42
16/16 - 1s - 37ms/step - accuracy: 0.7028 - loss: 0.8661
Epoch 12/42
16/16 - 0s - 31ms/step - accuracy: 0.7090 - loss: 0.8615
Epoch 13/42
16/16 - 0s - 28ms/step - accuracy: 0.7083 - loss: 0.8524
Epoch 14/42
16/16 - 0s - 28ms/step - accuracy: 0.7121 - loss: 0.8428
Epoch 15/42
16/16 - 1s - 43ms/step - accuracy: 0.7152 - loss: 0.8405
Epoch 16/42
16/16 - 0s - 29ms/step - accuracy: 0.7174 - loss: 0.8291
Epoch 17/42
16/16 - 1s - 32ms/step - accuracy: 0.7244 - loss: 0.8208
Epoch 18/42
16/16 - 0s - 26ms/step - accuracy: 0.7232 - loss: 0.8128
Epoch 19/42
16/16 - 1s - 43ms/step - accuracy: 0.7280 - loss: 0.8077
Epoch 20/42
16/16 - 0s - 19ms/step - accuracy: 0.7275 - loss: 0.7999
Epoch 21/42
16/16 - 0s - 22ms/step - accuracy: 0.7339 - loss: 0.7923
Epoch 22/42
16/16 - 1s - 46ms/step - accuracy: 0.7316 - loss: 0.7888
Epoch 23/42
16/16 - 1s - 44ms/step - accuracy: 0.7369 - loss: 0.7834
Epoch 24/42
16/16 - 1s - 36ms/step - accuracy: 0.7365 - loss: 0.7772
Epoch 25/42
16/16 - 0s - 24ms/step - accuracy: 0.7376 - loss: 0.7722
Epoch 26/42
16/16 - 1s - 46ms/step - accuracy: 0.7409 - loss: 0.7680
Epoch 27/42
16/16 - 0s - 29ms/step - accuracy: 0.7420 - loss: 0.7632
Epoch 28/42
16/16 - 0s - 29ms/step - accuracy: 0.7435 - loss: 0.7574
Epoch 29/42
16/16 - 1s - 40ms/step - accuracy: 0.7435 - loss: 0.7588
Epoch 30/42
16/16 - 1s - 43ms/step - accuracy: 0.7513 - loss: 0.7483
Epoch 31/42
16/16 - 0s - 20ms/step - accuracy: 0.7508 - loss: 0.7443
Epoch 32/42
16/16 - 0s - 26ms/step - accuracy: 0.7511 - loss: 0.7412
Epoch 33/42
16/16 - 0s - 16ms/step - accuracy: 0.7504 - loss: 0.7380
Epoch 34/42
16/16 - 0s - 18ms/step - accuracy: 0.7529 - loss: 0.7357
Epoch 35/42
16/16 - 0s - 22ms/step - accuracy: 0.7527 - loss: 0.7322
Epoch 36/42
16/16 - 0s - 21ms/step - accuracy: 0.7542 - loss: 0.7267
Epoch 37/42
16/16 - 0s - 20ms/step - accuracy: 0.7552 - loss: 0.7288
Epoch 38/42
16/16 - 0s - 23ms/step - accuracy: 0.7550 - loss: 0.7258
Epoch 39/42
16/16 - 0s - 31ms/step - accuracy: 0.7617 - loss: 0.7172
Epoch 40/42
16/16 - 1s - 31ms/step - accuracy: 0.7608 - loss: 0.7162
Epoch 41/42
16/16 - 1s - 34ms/step - accuracy: 0.7638 - loss: 0.7112
Epoch 42/42
16/16 - 0s - 26ms/step - accuracy: 0.7611 - loss: 0.7077
4/4 - 0s - 74ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 2s - 144ms/step - accuracy: 0.4173 - loss: 2.0094
Epoch 2/42
16/16 - 1s - 42ms/step - accuracy: 0.6463 - loss: 1.1810
Epoch 3/42
16/16 - 0s - 16ms/step - accuracy: 0.6588 - loss: 1.0724
Epoch 4/42
16/16 - 0s - 23ms/step - accuracy: 0.6678 - loss: 1.0163
Epoch 5/42
16/16 - 0s - 17ms/step - accuracy: 0.6773 - loss: 0.9783
Epoch 6/42
16/16 - 1s - 32ms/step - accuracy: 0.6792 - loss: 0.9594
Epoch 7/42
16/16 - 1s - 42ms/step - accuracy: 0.6905 - loss: 0.9306
Epoch 8/42
16/16 - 1s - 41ms/step - accuracy: 0.6922 - loss: 0.9135
Epoch 9/42
16/16 - 1s - 43ms/step - accuracy: 0.6989 - loss: 0.9035
Epoch 10/42
16/16 - 1s - 46ms/step - accuracy: 0.7001 - loss: 0.8903
Epoch 11/42
16/16 - 1s - 38ms/step - accuracy: 0.7052 - loss: 0.8788
Epoch 12/42
16/16 - 1s - 43ms/step - accuracy: 0.7062 - loss: 0.8661
Epoch 13/42
16/16 - 1s - 42ms/step - accuracy: 0.7119 - loss: 0.8555
Epoch 14/42
16/16 - 1s - 42ms/step - accuracy: 0.7202 - loss: 0.8419
Epoch 15/42
16/16 - 1s - 35ms/step - accuracy: 0.7172 - loss: 0.8380
Epoch 16/42
16/16 - 1s - 49ms/step - accuracy: 0.7183 - loss: 0.8358
Epoch 17/42
16/16 - 1s - 42ms/step - accuracy: 0.7217 - loss: 0.8253
Epoch 18/42
16/16 - 1s - 38ms/step - accuracy: 0.7243 - loss: 0.8167
Epoch 19/42
16/16 - 1s - 44ms/step - accuracy: 0.7261 - loss: 0.8114
Epoch 20/42
16/16 - 1s - 33ms/step - accuracy: 0.7261 - loss: 0.8094
Epoch 21/42
16/16 - 1s - 36ms/step - accuracy: 0.7316 - loss: 0.7995
Epoch 22/42
16/16 - 1s - 45ms/step - accuracy: 0.7306 - loss: 0.7940
Epoch 23/42
16/16 - 1s - 44ms/step - accuracy: 0.7339 - loss: 0.7914
Epoch 24/42
16/16 - 0s - 30ms/step - accuracy: 0.7336 - loss: 0.7890
Epoch 25/42
16/16 - 1s - 38ms/step - accuracy: 0.7372 - loss: 0.7801
Epoch 26/42
16/16 - 1s - 40ms/step - accuracy: 0.7365 - loss: 0.7804
Epoch 27/42
16/16 - 1s - 47ms/step - accuracy: 0.7389 - loss: 0.7723
Epoch 28/42
16/16 - 1s - 39ms/step - accuracy: 0.7398 - loss: 0.7699
Epoch 29/42
16/16 - 1s - 42ms/step - accuracy: 0.7375 - loss: 0.7673
Epoch 30/42
16/16 - 1s - 46ms/step - accuracy: 0.7430 - loss: 0.7598
Epoch 31/42
16/16 - 1s - 35ms/step - accuracy: 0.7419 - loss: 0.7563
Epoch 32/42
16/16 - 1s - 49ms/step - accuracy: 0.7462 - loss: 0.7541
Epoch 33/42
16/16 - 1s - 32ms/step - accuracy: 0.7442 - loss: 0.7497
Epoch 34/42
16/16 - 1s - 39ms/step - accuracy: 0.7500 - loss: 0.7469
Epoch 35/42
16/16 - 1s - 41ms/step - accuracy: 0.7465 - loss: 0.7452
Epoch 36/42
16/16 - 0s - 22ms/step - accuracy: 0.7480 - loss: 0.7405
Epoch 37/42
16/16 - 0s - 31ms/step - accuracy: 0.7524 - loss: 0.7388
Epoch 38/42
16/16 - 0s - 25ms/step - accuracy: 0.7519 - loss: 0.7301
Epoch 39/42
16/16 - 1s - 47ms/step - accuracy: 0.7516 - loss: 0.7336
Epoch 40/42
16/16 - 1s - 41ms/step - accuracy: 0.7510 - loss: 0.7309
Epoch 41/42
16/16 - 1s - 45ms/step - accuracy: 0.7543 - loss: 0.7246
Epoch 42/42
16/16 - 1s - 38ms/step - accuracy: 0.7533 - loss: 0.7245
4/4 - 0s - 98ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 2s - 134ms/step - accuracy: 0.5032 - loss: 1.7352
Epoch 2/42
16/16 - 1s - 40ms/step - accuracy: 0.6496 - loss: 1.1473
Epoch 3/42
16/16 - 1s - 42ms/step - accuracy: 0.6647 - loss: 1.0573
Epoch 4/42
16/16 - 0s - 28ms/step - accuracy: 0.6733 - loss: 1.0084
Epoch 5/42
16/16 - 1s - 44ms/step - accuracy: 0.6819 - loss: 0.9758
Epoch 6/42
16/16 - 1s - 45ms/step - accuracy: 0.6899 - loss: 0.9479
Epoch 7/42
16/16 - 0s - 29ms/step - accuracy: 0.6922 - loss: 0.9327
Epoch 8/42
16/16 - 0s - 17ms/step - accuracy: 0.6921 - loss: 0.9178
Epoch 9/42
16/16 - 0s - 22ms/step - accuracy: 0.6961 - loss: 0.9008
Epoch 10/42
16/16 - 0s - 19ms/step - accuracy: 0.7007 - loss: 0.8909
Epoch 11/42
16/16 - 0s - 18ms/step - accuracy: 0.7039 - loss: 0.8795
Epoch 12/42
16/16 - 0s - 21ms/step - accuracy: 0.7069 - loss: 0.8694
Epoch 13/42
16/16 - 0s - 20ms/step - accuracy: 0.7105 - loss: 0.8639
Epoch 14/42
16/16 - 0s - 24ms/step - accuracy: 0.7107 - loss: 0.8520
Epoch 15/42
16/16 - 0s - 17ms/step - accuracy: 0.7126 - loss: 0.8445
Epoch 16/42
16/16 - 0s - 24ms/step - accuracy: 0.7135 - loss: 0.8414
Epoch 17/42
16/16 - 0s - 19ms/step - accuracy: 0.7173 - loss: 0.8312
Epoch 18/42
16/16 - 0s - 19ms/step - accuracy: 0.7174 - loss: 0.8282
Epoch 19/42
16/16 - 0s - 23ms/step - accuracy: 0.7236 - loss: 0.8185
Epoch 20/42
16/16 - 1s - 47ms/step - accuracy: 0.7221 - loss: 0.8171
Epoch 21/42
16/16 - 0s - 25ms/step - accuracy: 0.7245 - loss: 0.8077
Epoch 22/42
16/16 - 0s - 24ms/step - accuracy: 0.7249 - loss: 0.8056
Epoch 23/42
16/16 - 1s - 34ms/step - accuracy: 0.7266 - loss: 0.7992
Epoch 24/42
16/16 - 1s - 41ms/step - accuracy: 0.7259 - loss: 0.7945
Epoch 25/42
16/16 - 1s - 33ms/step - accuracy: 0.7312 - loss: 0.7906
Epoch 26/42
16/16 - 1s - 47ms/step - accuracy: 0.7345 - loss: 0.7848
Epoch 27/42
16/16 - 1s - 44ms/step - accuracy: 0.7364 - loss: 0.7784
Epoch 28/42
16/16 - 1s - 38ms/step - accuracy: 0.7348 - loss: 0.7779
Epoch 29/42
16/16 - 1s - 45ms/step - accuracy: 0.7335 - loss: 0.7748
Epoch 30/42
16/16 - 1s - 41ms/step - accuracy: 0.7383 - loss: 0.7679
Epoch 31/42
16/16 - 1s - 39ms/step - accuracy: 0.7420 - loss: 0.7593
Epoch 32/42
16/16 - 1s - 41ms/step - accuracy: 0.7399 - loss: 0.7591
Epoch 33/42
16/16 - 0s - 30ms/step - accuracy: 0.7392 - loss: 0.7590
Epoch 34/42
16/16 - 1s - 43ms/step - accuracy: 0.7441 - loss: 0.7556
Epoch 35/42
16/16 - 0s - 26ms/step - accuracy: 0.7433 - loss: 0.7490
Epoch 36/42
16/16 - 1s - 45ms/step - accuracy: 0.7456 - loss: 0.7471
Epoch 37/42
16/16 - 0s - 27ms/step - accuracy: 0.7491 - loss: 0.7444
Epoch 38/42
16/16 - 1s - 43ms/step - accuracy: 0.7473 - loss: 0.7391
Epoch 39/42
16/16 - 1s - 43ms/step - accuracy: 0.7494 - loss: 0.7396
Epoch 40/42
16/16 - 1s - 36ms/step - accuracy: 0.7487 - loss: 0.7360
Epoch 41/42
16/16 - 1s - 46ms/step - accuracy: 0.7500 - loss: 0.7320
Epoch 42/42
16/16 - 1s - 40ms/step - accuracy: 0.7525 - loss: 0.7267
4/4 - 0s - 93ms/step
| 6         | 0.7569    | 5.211     | 900.7     | 0.9971    | 0.08259   | 42.28     | 1.569     | 2.452     | 1.982     | 0.8693    | 24.6      | 0.9713    | 0.3422    |
Epoch 1/30

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 4s - 209ms/step - accuracy: 0.5421 - loss: 1.6445
Epoch 2/30
20/20 - 1s - 34ms/step - accuracy: 0.6585 - loss: 0.9576
Epoch 3/30
20/20 - 1s - 35ms/step - accuracy: 0.6907 - loss: 0.8877
Epoch 4/30
20/20 - 1s - 35ms/step - accuracy: 0.7085 - loss: 0.8401
Epoch 5/30
20/20 - 0s - 25ms/step - accuracy: 0.7242 - loss: 0.7987
Epoch 6/30
20/20 - 1s - 35ms/step - accuracy: 0.7335 - loss: 0.7643
Epoch 7/30
20/20 - 1s - 27ms/step - accuracy: 0.7450 - loss: 0.7356
Epoch 8/30
20/20 - 1s - 35ms/step - accuracy: 0.7490 - loss: 0.7214
Epoch 9/30
20/20 - 1s - 32ms/step - accuracy: 0.7608 - loss: 0.6826
Epoch 10/30
20/20 - 1s - 30ms/step - accuracy: 0.7660 - loss: 0.6674
Epoch 11/30
20/20 - 1s - 26ms/step - accuracy: 0.7711 - loss: 0.6483
Epoch 12/30
20/20 - 1s - 32ms/step - accuracy: 0.7692 - loss: 0.6482
Epoch 13/30
20/20 - 1s - 32ms/step - accuracy: 0.7828 - loss: 0.6170
Epoch 14/30
20/20 - 1s - 32ms/step - accuracy: 0.7846 - loss: 0.6081
Epoch 15/30
20/20 - 1s - 39ms/step - accuracy: 0.7874 - loss: 0.5949
Epoch 16/30
20/20 - 0s - 25ms/step - accuracy: 0.7897 - loss: 0.5860
Epoch 17/30
20/20 - 1s - 37ms/step - accuracy: 0.7948 - loss: 0.5729
Epoch 18/30
20/20 - 0s - 15ms/step - accuracy: 0.7935 - loss: 0.5744
Epoch 19/30
20/20 - 0s - 17ms/step - accuracy: 0.8019 - loss: 0.5510
Epoch 20/30
20/20 - 0s - 15ms/step - accuracy: 0.8078 - loss: 0.5421
Epoch 21/30
20/20 - 0s - 15ms/step - accuracy: 0.8087 - loss: 0.5357
Epoch 22/30
20/20 - 0s - 13ms/step - accuracy: 0.8089 - loss: 0.5321
Epoch 23/30
20/20 - 0s - 13ms/step - accuracy: 0.8120 - loss: 0.5231
Epoch 24/30
20/20 - 0s - 12ms/step - accuracy: 0.8182 - loss: 0.5097
Epoch 25/30
20/20 - 0s - 12ms/step - accuracy: 0.8227 - loss: 0.5016
Epoch 26/30
20/20 - 0s - 13ms/step - accuracy: 0.8216 - loss: 0.4946
Epoch 27/30
20/20 - 0s - 12ms/step - accuracy: 0.8207 - loss: 0.5004
Epoch 28/30
20/20 - 0s - 12ms/step - accuracy: 0.8285 - loss: 0.4766
Epoch 29/30
20/20 - 0s - 13ms/step - accuracy: 0.8281 - loss: 0.4772
Epoch 30/30
20/20 - 0s - 12ms/step - accuracy: 0.8317 - loss: 0.4634
5/5 - 0s - 45ms/step
Epoch 1/30

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 4s - 199ms/step - accuracy: 0.6223 - loss: 1.2016
Epoch 2/30
20/20 - 0s - 14ms/step - accuracy: 0.7055 - loss: 0.8721
Epoch 3/30
20/20 - 0s - 14ms/step - accuracy: 0.7391 - loss: 0.7882
Epoch 4/30
20/20 - 0s - 15ms/step - accuracy: 0.7563 - loss: 0.7352
Epoch 5/30
20/20 - 0s - 14ms/step - accuracy: 0.7643 - loss: 0.7000
Epoch 6/30
20/20 - 0s - 13ms/step - accuracy: 0.7717 - loss: 0.6710
Epoch 7/30
20/20 - 0s - 14ms/step - accuracy: 0.7781 - loss: 0.6471
Epoch 8/30
20/20 - 0s - 14ms/step - accuracy: 0.7794 - loss: 0.6354
Epoch 9/30
20/20 - 0s - 14ms/step - accuracy: 0.7868 - loss: 0.6115
Epoch 10/30
20/20 - 0s - 13ms/step - accuracy: 0.7929 - loss: 0.5929
Epoch 11/30
20/20 - 0s - 13ms/step - accuracy: 0.7950 - loss: 0.5808
Epoch 12/30
20/20 - 0s - 14ms/step - accuracy: 0.8009 - loss: 0.5653
Epoch 13/30
20/20 - 0s - 13ms/step - accuracy: 0.8015 - loss: 0.5572
Epoch 14/30
20/20 - 0s - 14ms/step - accuracy: 0.8072 - loss: 0.5447
Epoch 15/30
20/20 - 0s - 14ms/step - accuracy: 0.8094 - loss: 0.5362
Epoch 16/30
20/20 - 0s - 13ms/step - accuracy: 0.8104 - loss: 0.5278
Epoch 17/30
20/20 - 0s - 13ms/step - accuracy: 0.8147 - loss: 0.5147
Epoch 18/30
20/20 - 0s - 13ms/step - accuracy: 0.8199 - loss: 0.5009
Epoch 19/30
20/20 - 0s - 13ms/step - accuracy: 0.8218 - loss: 0.4942
Epoch 20/30
20/20 - 0s - 13ms/step - accuracy: 0.8250 - loss: 0.4833
Epoch 21/30
20/20 - 0s - 13ms/step - accuracy: 0.8210 - loss: 0.4970
Epoch 22/30
20/20 - 0s - 15ms/step - accuracy: 0.8286 - loss: 0.4715
Epoch 23/30
20/20 - 0s - 16ms/step - accuracy: 0.8344 - loss: 0.4596
Epoch 24/30
20/20 - 0s - 15ms/step - accuracy: 0.8311 - loss: 0.4610
Epoch 25/30
20/20 - 0s - 17ms/step - accuracy: 0.8386 - loss: 0.4459
Epoch 26/30
20/20 - 0s - 16ms/step - accuracy: 0.8403 - loss: 0.4442
Epoch 27/30
20/20 - 0s - 13ms/step - accuracy: 0.8401 - loss: 0.4337
Epoch 28/30
20/20 - 0s - 14ms/step - accuracy: 0.8468 - loss: 0.4230
Epoch 29/30
20/20 - 0s - 11ms/step - accuracy: 0.8446 - loss: 0.4291
Epoch 30/30
20/20 - 0s - 13ms/step - accuracy: 0.8466 - loss: 0.4215
5/5 - 0s - 60ms/step
Epoch 1/30

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 168ms/step - accuracy: 0.5894 - loss: 1.3248
Epoch 2/30
20/20 - 0s - 13ms/step - accuracy: 0.6913 - loss: 0.9020
Epoch 3/30
20/20 - 0s - 12ms/step - accuracy: 0.7240 - loss: 0.8193
Epoch 4/30
20/20 - 0s - 12ms/step - accuracy: 0.7416 - loss: 0.7649
Epoch 5/30
20/20 - 0s - 12ms/step - accuracy: 0.7586 - loss: 0.7226
Epoch 6/30
20/20 - 0s - 14ms/step - accuracy: 0.7653 - loss: 0.6903
Epoch 7/30
20/20 - 0s - 11ms/step - accuracy: 0.7712 - loss: 0.6688
Epoch 8/30
20/20 - 0s - 12ms/step - accuracy: 0.7746 - loss: 0.6523
Epoch 9/30
20/20 - 0s - 12ms/step - accuracy: 0.7813 - loss: 0.6301
Epoch 10/30
20/20 - 1s - 26ms/step - accuracy: 0.7904 - loss: 0.6108
Epoch 11/30
20/20 - 0s - 18ms/step - accuracy: 0.7869 - loss: 0.6081
Epoch 12/30
20/20 - 0s - 13ms/step - accuracy: 0.7944 - loss: 0.5846
Epoch 13/30
20/20 - 0s - 14ms/step - accuracy: 0.7996 - loss: 0.5755
Epoch 14/30
20/20 - 0s - 15ms/step - accuracy: 0.8020 - loss: 0.5625
Epoch 15/30
20/20 - 0s - 22ms/step - accuracy: 0.8012 - loss: 0.5561
Epoch 16/30
20/20 - 0s - 14ms/step - accuracy: 0.8073 - loss: 0.5422
Epoch 17/30
20/20 - 0s - 13ms/step - accuracy: 0.8115 - loss: 0.5303
Epoch 18/30
20/20 - 0s - 13ms/step - accuracy: 0.8145 - loss: 0.5211
Epoch 19/30
20/20 - 0s - 14ms/step - accuracy: 0.8172 - loss: 0.5147
Epoch 20/30
20/20 - 0s - 14ms/step - accuracy: 0.8209 - loss: 0.5031
Epoch 21/30
20/20 - 0s - 13ms/step - accuracy: 0.8228 - loss: 0.4954
Epoch 22/30
20/20 - 0s - 14ms/step - accuracy: 0.8250 - loss: 0.4903
Epoch 23/30
20/20 - 0s - 15ms/step - accuracy: 0.8288 - loss: 0.4792
Epoch 24/30
20/20 - 0s - 12ms/step - accuracy: 0.8301 - loss: 0.4712
Epoch 25/30
20/20 - 0s - 15ms/step - accuracy: 0.8301 - loss: 0.4679
Epoch 26/30
20/20 - 0s - 24ms/step - accuracy: 0.8346 - loss: 0.4563
Epoch 27/30
20/20 - 0s - 24ms/step - accuracy: 0.8365 - loss: 0.4550
Epoch 28/30
20/20 - 0s - 13ms/step - accuracy: 0.8403 - loss: 0.4445
Epoch 29/30
20/20 - 0s - 10ms/step - accuracy: 0.8412 - loss: 0.4396
Epoch 30/30
20/20 - 0s - 14ms/step - accuracy: 0.8455 - loss: 0.4270
5/5 - 0s - 54ms/step
Epoch 1/30

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 5s - 242ms/step - accuracy: 0.6120 - loss: 1.2624
Epoch 2/30
20/20 - 1s - 28ms/step - accuracy: 0.6977 - loss: 0.9082
Epoch 3/30
20/20 - 0s - 24ms/step - accuracy: 0.7260 - loss: 0.8181
Epoch 4/30
20/20 - 1s - 35ms/step - accuracy: 0.7425 - loss: 0.7577
Epoch 5/30
20/20 - 0s - 19ms/step - accuracy: 0.7552 - loss: 0.7185
Epoch 6/30
20/20 - 0s - 23ms/step - accuracy: 0.7638 - loss: 0.6871
Epoch 7/30
20/20 - 1s - 34ms/step - accuracy: 0.7704 - loss: 0.6629
Epoch 8/30
20/20 - 1s - 31ms/step - accuracy: 0.7774 - loss: 0.6414
Epoch 9/30
20/20 - 1s - 34ms/step - accuracy: 0.7741 - loss: 0.6360
Epoch 10/30
20/20 - 0s - 24ms/step - accuracy: 0.7871 - loss: 0.6068
Epoch 11/30
20/20 - 0s - 24ms/step - accuracy: 0.7921 - loss: 0.5957
Epoch 12/30
20/20 - 0s - 21ms/step - accuracy: 0.7923 - loss: 0.5818
Epoch 13/30
20/20 - 0s - 21ms/step - accuracy: 0.7939 - loss: 0.5682
Epoch 14/30
20/20 - 1s - 28ms/step - accuracy: 0.8004 - loss: 0.5606
Epoch 15/30
20/20 - 1s - 25ms/step - accuracy: 0.8009 - loss: 0.5524
Epoch 16/30
20/20 - 1s - 31ms/step - accuracy: 0.8076 - loss: 0.5332
Epoch 17/30
20/20 - 1s - 25ms/step - accuracy: 0.8108 - loss: 0.5262
Epoch 18/30
20/20 - 1s - 31ms/step - accuracy: 0.8084 - loss: 0.5264
Epoch 19/30
20/20 - 0s - 22ms/step - accuracy: 0.8142 - loss: 0.5109
Epoch 20/30
20/20 - 1s - 34ms/step - accuracy: 0.8172 - loss: 0.5035
Epoch 21/30
20/20 - 1s - 33ms/step - accuracy: 0.8176 - loss: 0.4985
Epoch 22/30
20/20 - 1s - 33ms/step - accuracy: 0.8220 - loss: 0.4844
Epoch 23/30
20/20 - 0s - 23ms/step - accuracy: 0.8261 - loss: 0.4789
Epoch 24/30
20/20 - 0s - 22ms/step - accuracy: 0.8245 - loss: 0.4722
Epoch 25/30
20/20 - 1s - 34ms/step - accuracy: 0.8263 - loss: 0.4711
Epoch 26/30
20/20 - 1s - 35ms/step - accuracy: 0.8325 - loss: 0.4579
Epoch 27/30
20/20 - 0s - 22ms/step - accuracy: 0.8331 - loss: 0.4578
Epoch 28/30
20/20 - 1s - 34ms/step - accuracy: 0.8367 - loss: 0.4425
Epoch 29/30
20/20 - 1s - 36ms/step - accuracy: 0.8416 - loss: 0.4338
Epoch 30/30
20/20 - 1s - 29ms/step - accuracy: 0.8465 - loss: 0.4257
5/5 - 0s - 82ms/step
Epoch 1/30

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 4s - 215ms/step - accuracy: 0.6215 - loss: 1.2613
Epoch 2/30
20/20 - 0s - 24ms/step - accuracy: 0.6955 - loss: 0.9109
Epoch 3/30
20/20 - 0s - 22ms/step - accuracy: 0.7131 - loss: 0.8281
Epoch 4/30
20/20 - 1s - 35ms/step - accuracy: 0.7307 - loss: 0.7804
Epoch 5/30
20/20 - 1s - 35ms/step - accuracy: 0.7440 - loss: 0.7392
Epoch 6/30
20/20 - 1s - 29ms/step - accuracy: 0.7574 - loss: 0.7095
Epoch 7/30
20/20 - 1s - 25ms/step - accuracy: 0.7636 - loss: 0.6894
Epoch 8/30
20/20 - 1s - 29ms/step - accuracy: 0.7709 - loss: 0.6656
Epoch 9/30
20/20 - 1s - 36ms/step - accuracy: 0.7758 - loss: 0.6470
Epoch 10/30
20/20 - 1s - 34ms/step - accuracy: 0.7827 - loss: 0.6314
Epoch 11/30
20/20 - 0s - 22ms/step - accuracy: 0.7858 - loss: 0.6184
Epoch 12/30
20/20 - 1s - 34ms/step - accuracy: 0.7858 - loss: 0.6117
Epoch 13/30
20/20 - 0s - 21ms/step - accuracy: 0.7933 - loss: 0.5924
Epoch 14/30
20/20 - 0s - 23ms/step - accuracy: 0.7983 - loss: 0.5777
Epoch 15/30
20/20 - 1s - 37ms/step - accuracy: 0.8010 - loss: 0.5674
Epoch 16/30
20/20 - 1s - 30ms/step - accuracy: 0.8052 - loss: 0.5587
Epoch 17/30
20/20 - 0s - 17ms/step - accuracy: 0.8073 - loss: 0.5489
Epoch 18/30
20/20 - 1s - 41ms/step - accuracy: 0.8080 - loss: 0.5414
Epoch 19/30
20/20 - 1s - 34ms/step - accuracy: 0.8114 - loss: 0.5291
Epoch 20/30
20/20 - 1s - 31ms/step - accuracy: 0.8101 - loss: 0.5336
Epoch 21/30
20/20 - 0s - 21ms/step - accuracy: 0.8163 - loss: 0.5152
Epoch 22/30
20/20 - 1s - 38ms/step - accuracy: 0.8203 - loss: 0.5061
Epoch 23/30
20/20 - 0s - 23ms/step - accuracy: 0.8225 - loss: 0.4989
Epoch 24/30
20/20 - 0s - 22ms/step - accuracy: 0.8257 - loss: 0.4893
Epoch 25/30
20/20 - 0s - 18ms/step - accuracy: 0.8241 - loss: 0.4936
Epoch 26/30
20/20 - 0s - 23ms/step - accuracy: 0.8290 - loss: 0.4784
Epoch 27/30
20/20 - 0s - 23ms/step - accuracy: 0.8330 - loss: 0.4683
Epoch 28/30
20/20 - 1s - 35ms/step - accuracy: 0.8355 - loss: 0.4636
Epoch 29/30
20/20 - 1s - 32ms/step - accuracy: 0.8332 - loss: 0.4661
Epoch 30/30
20/20 - 1s - 34ms/step - accuracy: 0.8364 - loss: 0.4548
5/5 - 0s - 69ms/step
| 7         | 0.8152    | 6.305     | 721.6     | 0.04646   | 0.05919   | 29.92     | 2.505     | 1.73      | 2.062     | 0.3606    | 56.32     | 0.2617    | 5.962     |
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 - 3s - 103ms/step - accuracy: 0.6205 - loss: 1.1517
Epoch 2/42
32/32 - 1s - 43ms/step - accuracy: 0.6936 - loss: 0.8882
Epoch 3/42
32/32 - 1s - 39ms/step - accuracy: 0.7222 - loss: 0.7912
Epoch 4/42
32/32 - 1s - 38ms/step - accuracy: 0.7406 - loss: 0.7392
Epoch 5/42
32/32 - 1s - 22ms/step - accuracy: 0.7480 - loss: 0.7077
Epoch 6/42
32/32 - 1s - 19ms/step - accuracy: 0.7620 - loss: 0.6705
Epoch 7/42
32/32 - 1s - 29ms/step - accuracy: 0.7676 - loss: 0.6533
Epoch 8/42
32/32 - 1s - 19ms/step - accuracy: 0.7751 - loss: 0.6361
Epoch 9/42
32/32 - 1s - 18ms/step - accuracy: 0.7782 - loss: 0.6171
Epoch 10/42
32/32 - 1s - 19ms/step - accuracy: 0.7829 - loss: 0.6035
Epoch 11/42
32/32 - 1s - 29ms/step - accuracy: 0.7875 - loss: 0.5858
Epoch 12/42
32/32 - 1s - 39ms/step - accuracy: 0.7919 - loss: 0.5825
Epoch 13/42
32/32 - 1s - 26ms/step - accuracy: 0.7957 - loss: 0.5635
Epoch 14/42
32/32 - 1s - 44ms/step - accuracy: 0.8015 - loss: 0.5495
Epoch 15/42
32/32 - 1s - 31ms/step - accuracy: 0.8043 - loss: 0.5475
Epoch 16/42
32/32 - 1s - 39ms/step - accuracy: 0.8093 - loss: 0.5234
Epoch 17/42
32/32 - 1s - 43ms/step - accuracy: 0.8107 - loss: 0.5175
Epoch 18/42
32/32 - 1s - 39ms/step - accuracy: 0.8170 - loss: 0.5081
Epoch 19/42
32/32 - 1s - 44ms/step - accuracy: 0.8193 - loss: 0.5045
Epoch 20/42
32/32 - 1s - 41ms/step - accuracy: 0.8181 - loss: 0.5017
Epoch 21/42
32/32 - 1s - 43ms/step - accuracy: 0.8210 - loss: 0.4875
Epoch 22/42
32/32 - 1s - 26ms/step - accuracy: 0.8254 - loss: 0.4787
Epoch 23/42
32/32 - 1s - 44ms/step - accuracy: 0.8315 - loss: 0.4663
Epoch 24/42
32/32 - 1s - 46ms/step - accuracy: 0.8292 - loss: 0.4628
Epoch 25/42
32/32 - 1s - 35ms/step - accuracy: 0.8327 - loss: 0.4594
Epoch 26/42
32/32 - 1s - 31ms/step - accuracy: 0.8364 - loss: 0.4454
Epoch 27/42
32/32 - 1s - 40ms/step - accuracy: 0.8343 - loss: 0.4536
Epoch 28/42
32/32 - 1s - 41ms/step - accuracy: 0.8389 - loss: 0.4395
Epoch 29/42
32/32 - 1s - 40ms/step - accuracy: 0.8404 - loss: 0.4354
Epoch 30/42
32/32 - 1s - 43ms/step - accuracy: 0.8422 - loss: 0.4333
Epoch 31/42
32/32 - 1s - 39ms/step - accuracy: 0.8453 - loss: 0.4229
Epoch 32/42
32/32 - 1s - 46ms/step - accuracy: 0.8473 - loss: 0.4139
Epoch 33/42
32/32 - 1s - 38ms/step - accuracy: 0.8461 - loss: 0.4193
Epoch 34/42
32/32 - 1s - 29ms/step - accuracy: 0.8460 - loss: 0.4108
Epoch 35/42
32/32 - 1s - 41ms/step - accuracy: 0.8476 - loss: 0.4177
Epoch 36/42
32/32 - 1s - 43ms/step - accuracy: 0.8495 - loss: 0.4011
Epoch 37/42
32/32 - 1s - 43ms/step - accuracy: 0.8529 - loss: 0.3993
Epoch 38/42
32/32 - 1s - 41ms/step - accuracy: 0.8533 - loss: 0.4026
Epoch 39/42
32/32 - 1s - 37ms/step - accuracy: 0.8565 - loss: 0.3891
Epoch 40/42
32/32 - 1s - 39ms/step - accuracy: 0.8553 - loss: 0.3937
Epoch 41/42
32/32 - 1s - 29ms/step - accuracy: 0.8577 - loss: 0.3807
Epoch 42/42
32/32 - 1s - 44ms/step - accuracy: 0.8620 - loss: 0.3799
8/8 - 1s - 65ms/step

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/42
32/32 - 4s - 140ms/step - accuracy: 0.6210 - loss: 1.1880
Epoch 2/42
32/32 - 1s - 45ms/step - accuracy: 0.6940 - loss: 0.8915
Epoch 3/42
32/32 - 1s - 29ms/step - accuracy: 0.7291 - loss: 0.7906
Epoch 4/42
32/32 - 1s - 44ms/step - accuracy: 0.7400 - loss: 0.7339
Epoch 5/42
32/32 - 1s - 41ms/step - accuracy: 0.7519 - loss: 0.7042
Epoch 6/42
32/32 - 1s - 41ms/step - accuracy: 0.7615 - loss: 0.6757
Epoch 7/42
32/32 - 1s - 31ms/step - accuracy: 0.7615 - loss: 0.6649
Epoch 8/42
32/32 - 1s - 30ms/step - accuracy: 0.7730 - loss: 0.6349
Epoch 9/42
32/32 - 1s - 28ms/step - accuracy: 0.7755 - loss: 0.6244
Epoch 10/42
32/32 - 1s - 46ms/step - accuracy: 0.7800 - loss: 0.6008
Epoch 11/42
32/32 - 1s - 39ms/step - accuracy: 0.7780 - loss: 0.5996
Epoch 12/42
32/32 - 1s - 44ms/step - accuracy: 0.7913 - loss: 0.5751
Epoch 13/42
32/32 - 1s - 28ms/step - accuracy: 0.7885 - loss: 0.5648
Epoch 14/42
32/32 - 1s - 45ms/step - accuracy: 0.7967 - loss: 0.5593
Epoch 15/42
32/32 - 1s - 35ms/step - accuracy: 0.7959 - loss: 0.5601
Epoch 16/42
32/32 - 1s - 28ms/step - accuracy: 0.7969 - loss: 0.5359
Epoch 17/42
32/32 - 1s - 33ms/step - accuracy: 0.8090 - loss: 0.5228
Epoch 18/42
32/32 - 1s - 23ms/step - accuracy: 0.8144 - loss: 0.5072
Epoch 19/42
32/32 - 1s - 24ms/step - accuracy: 0.8062 - loss: 0.5202
Epoch 20/42
32/32 - 1s - 22ms/step - accuracy: 0.8150 - loss: 0.4999
Epoch 21/42
32/32 - 1s - 24ms/step - accuracy: 0.8161 - loss: 0.4985
Epoch 22/42
32/32 - 1s - 23ms/step - accuracy: 0.8204 - loss: 0.4856
Epoch 23/42
32/32 - 1s - 19ms/step - accuracy: 0.8263 - loss: 0.4686
Epoch 24/42
32/32 - 1s - 22ms/step - accuracy: 0.8243 - loss: 0.4767
Epoch 25/42
32/32 - 1s - 23ms/step - accuracy: 0.8326 - loss: 0.4532
Epoch 26/42
32/32 - 1s - 28ms/step - accuracy: 0.8287 - loss: 0.4682
Epoch 27/42
32/32 - 1s - 43ms/step - accuracy: 0.8383 - loss: 0.4461
Epoch 28/42
32/32 - 1s - 29ms/step - accuracy: 0.8332 - loss: 0.4459
Epoch 29/42
32/32 - 1s - 29ms/step - accuracy: 0.8423 - loss: 0.4379
Epoch 30/42
32/32 - 1s - 32ms/step - accuracy: 0.8372 - loss: 0.4425
Epoch 31/42
32/32 - 1s - 38ms/step - accuracy: 0.8489 - loss: 0.4158
Epoch 32/42
32/32 - 1s - 43ms/step - accuracy: 0.8404 - loss: 0.4235
Epoch 33/42
32/32 - 1s - 43ms/step - accuracy: 0.8478 - loss: 0.4145
Epoch 34/42
32/32 - 1s - 40ms/step - accuracy: 0.8475 - loss: 0.4122
Epoch 35/42
32/32 - 1s - 41ms/step - accuracy: 0.8497 - loss: 0.4017
Epoch 36/42
32/32 - 1s - 41ms/step - accuracy: 0.8511 - loss: 0.3939
Epoch 37/42
32/32 - 1s - 43ms/step - accuracy: 0.8439 - loss: 0.4147
Epoch 38/42
32/32 - 1s - 40ms/step - accuracy: 0.8529 - loss: 0.3907
Epoch 39/42
32/32 - 1s - 42ms/step - accuracy: 0.8512 - loss: 0.4060
Epoch 40/42
32/32 - 1s - 31ms/step - accuracy: 0.8578 - loss: 0.3911
Epoch 41/42
32/32 - 1s - 31ms/step - accuracy: 0.8596 - loss: 0.3810
Epoch 42/42
32/32 - 1s - 32ms/step - accuracy: 0.8590 - loss: 0.3785
8/8 - 1s - 63ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 - 3s - 103ms/step - accuracy: 0.6275 - loss: 1.1244
Epoch 2/42
32/32 - 1s - 26ms/step - accuracy: 0.7029 - loss: 0.8946
Epoch 3/42
32/32 - 2s - 48ms/step - accuracy: 0.7267 - loss: 0.7858
Epoch 4/42
32/32 - 1s - 40ms/step - accuracy: 0.7446 - loss: 0.7411
Epoch 5/42
32/32 - 1s - 40ms/step - accuracy: 0.7523 - loss: 0.6944
Epoch 6/42
32/32 - 1s - 43ms/step - accuracy: 0.7627 - loss: 0.6686
Epoch 7/42
32/32 - 1s - 40ms/step - accuracy: 0.7694 - loss: 0.6502
Epoch 8/42
32/32 - 1s - 30ms/step - accuracy: 0.7747 - loss: 0.6294
Epoch 9/42
32/32 - 1s - 43ms/step - accuracy: 0.7770 - loss: 0.6172
Epoch 10/42
32/32 - 1s - 31ms/step - accuracy: 0.7816 - loss: 0.6048
Epoch 11/42
32/32 - 1s - 30ms/step - accuracy: 0.7840 - loss: 0.5946
Epoch 12/42
32/32 - 1s - 43ms/step - accuracy: 0.7850 - loss: 0.5856
Epoch 13/42
32/32 - 1s - 42ms/step - accuracy: 0.7951 - loss: 0.5689
Epoch 14/42
32/32 - 1s - 41ms/step - accuracy: 0.7969 - loss: 0.5538
Epoch 15/42
32/32 - 1s - 38ms/step - accuracy: 0.7985 - loss: 0.5490
Epoch 16/42
32/32 - 2s - 47ms/step - accuracy: 0.7998 - loss: 0.5453
Epoch 17/42
32/32 - 1s - 33ms/step - accuracy: 0.8024 - loss: 0.5373
Epoch 18/42
32/32 - 1s - 47ms/step - accuracy: 0.8055 - loss: 0.5240
Epoch 19/42
32/32 - 1s - 40ms/step - accuracy: 0.8107 - loss: 0.5199
Epoch 20/42
32/32 - 1s - 41ms/step - accuracy: 0.8113 - loss: 0.5149
Epoch 21/42
32/32 - 1s - 41ms/step - accuracy: 0.8219 - loss: 0.4905
Epoch 22/42
32/32 - 1s - 40ms/step - accuracy: 0.8248 - loss: 0.4901
Epoch 23/42
32/32 - 1s - 29ms/step - accuracy: 0.8222 - loss: 0.4819
Epoch 24/42
32/32 - 1s - 45ms/step - accuracy: 0.8264 - loss: 0.4790
Epoch 25/42
32/32 - 1s - 19ms/step - accuracy: 0.8278 - loss: 0.4724
Epoch 26/42
32/32 - 1s - 21ms/step - accuracy: 0.8276 - loss: 0.4650
Epoch 27/42
32/32 - 1s - 41ms/step - accuracy: 0.8297 - loss: 0.4640
Epoch 28/42
32/32 - 1s - 24ms/step - accuracy: 0.8362 - loss: 0.4519
Epoch 29/42
32/32 - 1s - 22ms/step - accuracy: 0.8291 - loss: 0.4602
Epoch 30/42
32/32 - 1s - 21ms/step - accuracy: 0.8318 - loss: 0.4509
Epoch 31/42
32/32 - 1s - 46ms/step - accuracy: 0.8354 - loss: 0.4452
Epoch 32/42
32/32 - 1s - 45ms/step - accuracy: 0.8382 - loss: 0.4313
Epoch 33/42
32/32 - 1s - 31ms/step - accuracy: 0.8351 - loss: 0.4379
Epoch 34/42
32/32 - 1s - 40ms/step - accuracy: 0.8470 - loss: 0.4156
Epoch 35/42
32/32 - 1s - 42ms/step - accuracy: 0.8436 - loss: 0.4257
Epoch 36/42
32/32 - 1s - 42ms/step - accuracy: 0.8415 - loss: 0.4267
Epoch 37/42
32/32 - 1s - 42ms/step - accuracy: 0.8531 - loss: 0.3995
Epoch 38/42
32/32 - 1s - 34ms/step - accuracy: 0.8441 - loss: 0.4334
Epoch 39/42
32/32 - 1s - 32ms/step - accuracy: 0.8531 - loss: 0.3973
Epoch 40/42
32/32 - 1s - 27ms/step - accuracy: 0.8511 - loss: 0.4015
Epoch 41/42
32/32 - 1s - 45ms/step - accuracy: 0.8554 - loss: 0.3968
Epoch 42/42
32/32 - 1s - 26ms/step - accuracy: 0.8550 - loss: 0.3920
8/8 - 0s - 59ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 - 3s - 108ms/step - accuracy: 0.6203 - loss: 1.1713
Epoch 2/42
32/32 - 1s - 39ms/step - accuracy: 0.6919 - loss: 0.8897
Epoch 3/42
32/32 - 1s - 42ms/step - accuracy: 0.7129 - loss: 0.8141
Epoch 4/42
32/32 - 1s - 43ms/step - accuracy: 0.7328 - loss: 0.7449
Epoch 5/42
32/32 - 1s - 32ms/step - accuracy: 0.7500 - loss: 0.7079
Epoch 6/42
32/32 - 1s - 27ms/step - accuracy: 0.7593 - loss: 0.6720
Epoch 7/42
32/32 - 1s - 30ms/step - accuracy: 0.7665 - loss: 0.6541
Epoch 8/42
32/32 - 1s - 25ms/step - accuracy: 0.7768 - loss: 0.6257
Epoch 9/42
32/32 - 1s - 29ms/step - accuracy: 0.7813 - loss: 0.6082
Epoch 10/42
32/32 - 1s - 37ms/step - accuracy: 0.7810 - loss: 0.5973
Epoch 11/42
32/32 - 2s - 49ms/step - accuracy: 0.7827 - loss: 0.5979
Epoch 12/42
32/32 - 1s - 26ms/step - accuracy: 0.7912 - loss: 0.5741
Epoch 13/42
32/32 - 1s - 46ms/step - accuracy: 0.7979 - loss: 0.5586
Epoch 14/42
32/32 - 1s - 35ms/step - accuracy: 0.8031 - loss: 0.5503
Epoch 15/42
32/32 - 1s - 25ms/step - accuracy: 0.8052 - loss: 0.5353
Epoch 16/42
32/32 - 1s - 26ms/step - accuracy: 0.8108 - loss: 0.5217
Epoch 17/42
32/32 - 1s - 43ms/step - accuracy: 0.8093 - loss: 0.5209
Epoch 18/42
32/32 - 1s - 39ms/step - accuracy: 0.8127 - loss: 0.5134
Epoch 19/42
32/32 - 1s - 44ms/step - accuracy: 0.8161 - loss: 0.4962
Epoch 20/42
32/32 - 1s - 32ms/step - accuracy: 0.8176 - loss: 0.5010
Epoch 21/42
32/32 - 1s - 35ms/step - accuracy: 0.8209 - loss: 0.4856
Epoch 22/42
32/32 - 1s - 43ms/step - accuracy: 0.8236 - loss: 0.4842
Epoch 23/42
32/32 - 1s - 43ms/step - accuracy: 0.8236 - loss: 0.4723
Epoch 24/42
32/32 - 1s - 40ms/step - accuracy: 0.8303 - loss: 0.4608
Epoch 25/42
32/32 - 1s - 29ms/step - accuracy: 0.8291 - loss: 0.4701
Epoch 26/42
32/32 - 1s - 41ms/step - accuracy: 0.8278 - loss: 0.4575
Epoch 27/42
32/32 - 1s - 41ms/step - accuracy: 0.8346 - loss: 0.4458
Epoch 28/42
32/32 - 1s - 42ms/step - accuracy: 0.8346 - loss: 0.4481
Epoch 29/42
32/32 - 1s - 30ms/step - accuracy: 0.8376 - loss: 0.4413
Epoch 30/42
32/32 - 1s - 29ms/step - accuracy: 0.8374 - loss: 0.4402
Epoch 31/42
32/32 - 1s - 43ms/step - accuracy: 0.8445 - loss: 0.4260
Epoch 32/42
32/32 - 1s - 43ms/step - accuracy: 0.8439 - loss: 0.4225
Epoch 33/42
32/32 - 1s - 21ms/step - accuracy: 0.8407 - loss: 0.4239
Epoch 34/42
32/32 - 1s - 19ms/step - accuracy: 0.8470 - loss: 0.4142
Epoch 35/42
32/32 - 1s - 19ms/step - accuracy: 0.8543 - loss: 0.4086
Epoch 36/42
32/32 - 1s - 19ms/step - accuracy: 0.8489 - loss: 0.4061
Epoch 37/42
32/32 - 1s - 21ms/step - accuracy: 0.8533 - loss: 0.3940
Epoch 38/42
32/32 - 1s - 40ms/step - accuracy: 0.8508 - loss: 0.4025
Epoch 39/42
32/32 - 1s - 19ms/step - accuracy: 0.8557 - loss: 0.3906
Epoch 40/42
32/32 - 1s - 22ms/step - accuracy: 0.8571 - loss: 0.3957
Epoch 41/42
32/32 - 1s - 27ms/step - accuracy: 0.8527 - loss: 0.4136
Epoch 42/42
32/32 - 1s - 45ms/step - accuracy: 0.8590 - loss: 0.3772
8/8 - 0s - 53ms/step
Epoch 1/42

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 - 4s - 123ms/step - accuracy: 0.6181 - loss: 1.1687
Epoch 2/42
32/32 - 2s - 48ms/step - accuracy: 0.6986 - loss: 0.8817
Epoch 3/42
32/32 - 1s - 41ms/step - accuracy: 0.7211 - loss: 0.7965
Epoch 4/42
32/32 - 1s - 34ms/step - accuracy: 0.7435 - loss: 0.7385
Epoch 5/42
32/32 - 2s - 51ms/step - accuracy: 0.7553 - loss: 0.6938
Epoch 6/42
32/32 - 1s - 38ms/step - accuracy: 0.7661 - loss: 0.6733
Epoch 7/42
32/32 - 1s - 42ms/step - accuracy: 0.7688 - loss: 0.6488
Epoch 8/42
32/32 - 1s - 31ms/step - accuracy: 0.7709 - loss: 0.6374
Epoch 9/42
32/32 - 1s - 42ms/step - accuracy: 0.7728 - loss: 0.6227
Epoch 10/42
32/32 - 1s - 42ms/step - accuracy: 0.7847 - loss: 0.6064
Epoch 11/42
32/32 - 1s - 31ms/step - accuracy: 0.7842 - loss: 0.5922
Epoch 12/42
32/32 - 1s - 41ms/step - accuracy: 0.7921 - loss: 0.5765
Epoch 13/42
32/32 - 1s - 45ms/step - accuracy: 0.7932 - loss: 0.5693
Epoch 14/42
32/32 - 1s - 42ms/step - accuracy: 0.8009 - loss: 0.5587
Epoch 15/42
32/32 - 1s - 34ms/step - accuracy: 0.8001 - loss: 0.5477
Epoch 16/42
32/32 - 1s - 25ms/step - accuracy: 0.7993 - loss: 0.5432
Epoch 17/42
32/32 - 2s - 49ms/step - accuracy: 0.8089 - loss: 0.5398
Epoch 18/42
32/32 - 1s - 37ms/step - accuracy: 0.8102 - loss: 0.5147
Epoch 19/42
32/32 - 1s - 33ms/step - accuracy: 0.8145 - loss: 0.5136
Epoch 20/42
32/32 - 1s - 38ms/step - accuracy: 0.8171 - loss: 0.5130
Epoch 21/42
32/32 - 1s - 41ms/step - accuracy: 0.8191 - loss: 0.4958
Epoch 22/42
32/32 - 1s - 25ms/step - accuracy: 0.8209 - loss: 0.4889
Epoch 23/42
32/32 - 2s - 48ms/step - accuracy: 0.8251 - loss: 0.4804
Epoch 24/42
32/32 - 1s - 36ms/step - accuracy: 0.8257 - loss: 0.4780
Epoch 25/42
32/32 - 1s - 28ms/step - accuracy: 0.8321 - loss: 0.4550
Epoch 26/42
32/32 - 1s - 26ms/step - accuracy: 0.8234 - loss: 0.4814
Epoch 27/42
32/32 - 1s - 27ms/step - accuracy: 0.8346 - loss: 0.4518
Epoch 28/42
32/32 - 1s - 45ms/step - accuracy: 0.8361 - loss: 0.4572
Epoch 29/42
32/32 - 1s - 31ms/step - accuracy: 0.8358 - loss: 0.4377
Epoch 30/42
32/32 - 1s - 43ms/step - accuracy: 0.8380 - loss: 0.4417
Epoch 31/42
32/32 - 1s - 31ms/step - accuracy: 0.8399 - loss: 0.4438
Epoch 32/42
32/32 - 1s - 43ms/step - accuracy: 0.8397 - loss: 0.4469
Epoch 33/42
32/32 - 1s - 33ms/step - accuracy: 0.8407 - loss: 0.4240
Epoch 34/42
32/32 - 1s - 32ms/step - accuracy: 0.8481 - loss: 0.4106
Epoch 35/42
32/32 - 1s - 42ms/step - accuracy: 0.8436 - loss: 0.4272
Epoch 36/42
32/32 - 1s - 32ms/step - accuracy: 0.8550 - loss: 0.3994
Epoch 37/42
32/32 - 1s - 39ms/step - accuracy: 0.8542 - loss: 0.3992
Epoch 38/42
32/32 - 1s - 44ms/step - accuracy: 0.8553 - loss: 0.3978
Epoch 39/42
32/32 - 1s - 28ms/step - accuracy: 0.8521 - loss: 0.3994
Epoch 40/42
32/32 - 1s - 37ms/step - accuracy: 0.8589 - loss: 0.3789
Epoch 41/42
32/32 - 1s - 20ms/step - accuracy: 0.8584 - loss: 0.3846
Epoch 42/42
32/32 - 1s - 17ms/step - accuracy: 0.8553 - loss: 0.3831
8/8 - 0s - 38ms/step
| 8         | 0.764     | 5.609     | 443.6     | 0.7755    | 0.2687    | 42.12     | 2.711     | 2.64      | 2.73      | 0.3883    | 65.03     | 0.4155    | 1.695     |
Epoch 1/31

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 2s - 119ms/step - accuracy: 0.0167 - loss: 2.7709
Epoch 2/31
17/17 - 0s - 19ms/step - accuracy: 0.0167 - loss: 2.7581
Epoch 3/31
17/17 - 0s - 20ms/step - accuracy: 0.0167 - loss: 2.7450
Epoch 4/31
17/17 - 0s - 18ms/step - accuracy: 0.0167 - loss: 2.7317
Epoch 5/31
17/17 - 0s - 17ms/step - accuracy: 0.0167 - loss: 2.7183
Epoch 6/31
17/17 - 0s - 17ms/step - accuracy: 0.0167 - loss: 2.7047
Epoch 7/31
17/17 - 0s - 22ms/step - accuracy: 0.0167 - loss: 2.6910
Epoch 8/31
17/17 - 0s - 21ms/step - accuracy: 0.0167 - loss: 2.6772
Epoch 9/31
17/17 - 0s - 17ms/step - accuracy: 0.0167 - loss: 2.6632
Epoch 10/31
17/17 - 0s - 25ms/step - accuracy: 0.0167 - loss: 2.6492
Epoch 11/31
17/17 - 0s - 19ms/step - accuracy: 0.0167 - loss: 2.6350
Epoch 12/31
17/17 - 0s - 24ms/step - accuracy: 0.0167 - loss: 2.6207
Epoch 13/31
17/17 - 0s - 19ms/step - accuracy: 0.0167 - loss: 2.6063
Epoch 14/31
17/17 - 1s - 41ms/step - accuracy: 0.0167 - loss: 2.5918
Epoch 15/31
17/17 - 0s - 24ms/step - accuracy: 0.0167 - loss: 2.5773
Epoch 16/31
17/17 - 0s - 16ms/step - accuracy: 0.0167 - loss: 2.5626
Epoch 17/31
17/17 - 0s - 22ms/step - accuracy: 0.0167 - loss: 2.5480
Epoch 18/31
17/17 - 0s - 21ms/step - accuracy: 0.0167 - loss: 2.5331
Epoch 19/31
17/17 - 0s - 19ms/step - accuracy: 0.0167 - loss: 2.5183
Epoch 20/31
17/17 - 0s - 16ms/step - accuracy: 0.0167 - loss: 2.5033
Epoch 21/31
17/17 - 0s - 21ms/step - accuracy: 0.0167 - loss: 2.4884
Epoch 22/31
17/17 - 0s - 17ms/step - accuracy: 0.0167 - loss: 2.4733
Epoch 23/31
17/17 - 0s - 24ms/step - accuracy: 0.0167 - loss: 2.4583
Epoch 24/31
17/17 - 0s - 24ms/step - accuracy: 0.0167 - loss: 2.4431
Epoch 25/31
17/17 - 0s - 18ms/step - accuracy: 0.0167 - loss: 2.4280
Epoch 26/31
17/17 - 0s - 20ms/step - accuracy: 0.0167 - loss: 2.4128
Epoch 27/31
17/17 - 0s - 29ms/step - accuracy: 0.0167 - loss: 2.3976
Epoch 28/31
17/17 - 0s - 24ms/step - accuracy: 0.0167 - loss: 2.3824
Epoch 29/31
17/17 - 0s - 23ms/step - accuracy: 0.0167 - loss: 2.3672
Epoch 30/31
17/17 - 0s - 21ms/step - accuracy: 0.0167 - loss: 2.3520
Epoch 31/31
17/17 - 0s - 24ms/step - accuracy: 0.0167 - loss: 2.3368
5/5 - 0s - 58ms/step
Epoch 1/31

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 168ms/step - accuracy: 0.0017 - loss: 2.5028
Epoch 2/31
17/17 - 0s - 22ms/step - accuracy: 0.0017 - loss: 2.4912
Epoch 3/31
17/17 - 1s - 43ms/step - accuracy: 0.0017 - loss: 2.4793
Epoch 4/31
17/17 - 1s - 39ms/step - accuracy: 0.0017 - loss: 2.4673
Epoch 5/31
17/17 - 1s - 44ms/step - accuracy: 0.0017 - loss: 2.4551
Epoch 6/31
17/17 - 0s - 24ms/step - accuracy: 0.0017 - loss: 2.4429
Epoch 7/31
17/17 - 0s - 19ms/step - accuracy: 0.0017 - loss: 2.4307
Epoch 8/31
17/17 - 0s - 19ms/step - accuracy: 0.0017 - loss: 2.4183
Epoch 9/31
17/17 - 0s - 22ms/step - accuracy: 0.0017 - loss: 2.4058
Epoch 10/31
17/17 - 0s - 20ms/step - accuracy: 0.0017 - loss: 2.3933
Epoch 11/31
17/17 - 0s - 27ms/step - accuracy: 0.0017 - loss: 2.3808
Epoch 12/31
17/17 - 1s - 36ms/step - accuracy: 0.0017 - loss: 2.3682
Epoch 13/31
17/17 - 0s - 23ms/step - accuracy: 0.0017 - loss: 2.3556
Epoch 14/31
17/17 - 0s - 18ms/step - accuracy: 0.0017 - loss: 2.3428
Epoch 15/31
17/17 - 0s - 16ms/step - accuracy: 0.0017 - loss: 2.3300
Epoch 16/31
17/17 - 0s - 24ms/step - accuracy: 0.0017 - loss: 2.3172
Epoch 17/31
17/17 - 0s - 27ms/step - accuracy: 0.0017 - loss: 2.3044
Epoch 18/31
17/17 - 0s - 20ms/step - accuracy: 0.0017 - loss: 2.2915
Epoch 19/31
17/17 - 0s - 24ms/step - accuracy: 0.0017 - loss: 2.2786
Epoch 20/31
17/17 - 1s - 41ms/step - accuracy: 0.0017 - loss: 2.2656
Epoch 21/31
17/17 - 0s - 20ms/step - accuracy: 0.0017 - loss: 2.2527
Epoch 22/31
17/17 - 0s - 24ms/step - accuracy: 0.0017 - loss: 2.2398
Epoch 23/31
17/17 - 0s - 25ms/step - accuracy: 0.0017 - loss: 2.2268
Epoch 24/31
17/17 - 0s - 19ms/step - accuracy: 0.0017 - loss: 2.2139
Epoch 25/31
17/17 - 0s - 24ms/step - accuracy: 0.0017 - loss: 2.2010
Epoch 26/31
17/17 - 0s - 21ms/step - accuracy: 0.0237 - loss: 2.1880
Epoch 27/31
17/17 - 0s - 20ms/step - accuracy: 0.1922 - loss: 2.1751
Epoch 28/31
17/17 - 0s - 20ms/step - accuracy: 0.1935 - loss: 2.1622
Epoch 29/31
17/17 - 0s - 19ms/step - accuracy: 0.1935 - loss: 2.1492
Epoch 30/31
17/17 - 0s - 23ms/step - accuracy: 0.1935 - loss: 2.1364
Epoch 31/31
17/17 - 1s - 35ms/step - accuracy: 0.1935 - loss: 2.1235
5/5 - 0s - 58ms/step
Epoch 1/31

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 2s - 145ms/step - accuracy: 0.0013 - loss: 2.8618
Epoch 2/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.8490
Epoch 3/31
17/17 - 1s - 42ms/step - accuracy: 0.0013 - loss: 2.8360
Epoch 4/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.8229
Epoch 5/31
17/17 - 0s - 28ms/step - accuracy: 0.0013 - loss: 2.8095
Epoch 6/31
17/17 - 0s - 17ms/step - accuracy: 0.0013 - loss: 2.7960
Epoch 7/31
17/17 - 0s - 25ms/step - accuracy: 0.0013 - loss: 2.7824
Epoch 8/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.7686
Epoch 9/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.7547
Epoch 10/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.7407
Epoch 11/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.7266
Epoch 12/31
17/17 - 0s - 24ms/step - accuracy: 0.0013 - loss: 2.7123
Epoch 13/31
17/17 - 0s - 19ms/step - accuracy: 0.0013 - loss: 2.6979
Epoch 14/31
17/17 - 0s - 23ms/step - accuracy: 0.0013 - loss: 2.6835
Epoch 15/31
17/17 - 1s - 39ms/step - accuracy: 0.0013 - loss: 2.6689
Epoch 16/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.6543
Epoch 17/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.6396
Epoch 18/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.6248
Epoch 19/31
17/17 - 1s - 43ms/step - accuracy: 0.0013 - loss: 2.6099
Epoch 20/31
17/17 - 0s - 24ms/step - accuracy: 0.0013 - loss: 2.5950
Epoch 21/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.5800
Epoch 22/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.5649
Epoch 23/31
17/17 - 0s - 19ms/step - accuracy: 0.0013 - loss: 2.5498
Epoch 24/31
17/17 - 0s - 25ms/step - accuracy: 0.0013 - loss: 2.5346
Epoch 25/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.5194
Epoch 26/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.5041
Epoch 27/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.4889
Epoch 28/31
17/17 - 0s - 25ms/step - accuracy: 0.0013 - loss: 2.4735
Epoch 29/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.4582
Epoch 30/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.4428
Epoch 31/31
17/17 - 0s - 22ms/step - accuracy: 0.0013 - loss: 2.4274
5/5 - 0s - 69ms/step
Epoch 1/31

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 2s - 141ms/step - accuracy: 0.0013 - loss: 2.8086
Epoch 2/31
17/17 - 0s - 20ms/step - accuracy: 0.0013 - loss: 2.7966
Epoch 3/31
17/17 - 1s - 39ms/step - accuracy: 0.0013 - loss: 2.7844
Epoch 4/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.7721
Epoch 5/31
17/17 - 0s - 24ms/step - accuracy: 0.0013 - loss: 2.7596
Epoch 6/31
17/17 - 0s - 19ms/step - accuracy: 0.0013 - loss: 2.7471
Epoch 7/31
17/17 - 0s - 23ms/step - accuracy: 0.0013 - loss: 2.7343
Epoch 8/31
17/17 - 0s - 24ms/step - accuracy: 0.0013 - loss: 2.7214
Epoch 9/31
17/17 - 1s - 37ms/step - accuracy: 0.0013 - loss: 2.7085
Epoch 10/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.6954
Epoch 11/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.6822
Epoch 12/31
17/17 - 0s - 23ms/step - accuracy: 0.0013 - loss: 2.6690
Epoch 13/31
17/17 - 1s - 44ms/step - accuracy: 0.0013 - loss: 2.6556
Epoch 14/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.6422
Epoch 15/31
17/17 - 0s - 19ms/step - accuracy: 0.0013 - loss: 2.6287
Epoch 16/31
17/17 - 0s - 17ms/step - accuracy: 0.0013 - loss: 2.6150
Epoch 17/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.6014
Epoch 18/31
17/17 - 0s - 17ms/step - accuracy: 0.0013 - loss: 2.5876
Epoch 19/31
17/17 - 0s - 16ms/step - accuracy: 0.0013 - loss: 2.5738
Epoch 20/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.5599
Epoch 21/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.5460
Epoch 22/31
17/17 - 0s - 22ms/step - accuracy: 0.0013 - loss: 2.5320
Epoch 23/31
17/17 - 0s - 29ms/step - accuracy: 0.0013 - loss: 2.5179
Epoch 24/31
17/17 - 0s - 21ms/step - accuracy: 0.0013 - loss: 2.5039
Epoch 25/31
17/17 - 0s - 19ms/step - accuracy: 0.0013 - loss: 2.4898
Epoch 26/31
17/17 - 0s - 16ms/step - accuracy: 0.0013 - loss: 2.4757
Epoch 27/31
17/17 - 0s - 23ms/step - accuracy: 0.0013 - loss: 2.4616
Epoch 28/31
17/17 - 0s - 16ms/step - accuracy: 0.0013 - loss: 2.4475
Epoch 29/31
17/17 - 0s - 18ms/step - accuracy: 0.0013 - loss: 2.4334
Epoch 30/31
17/17 - 0s - 19ms/step - accuracy: 0.0013 - loss: 2.4192
Epoch 31/31
17/17 - 0s - 18ms/step - accuracy: 0.0850 - loss: 2.4050
5/5 - 0s - 44ms/step
Epoch 1/31

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 160ms/step - accuracy: 0.0143 - loss: 3.3693
Epoch 2/31
17/17 - 0s - 17ms/step - accuracy: 0.0143 - loss: 3.3548
Epoch 3/31
17/17 - 0s - 17ms/step - accuracy: 0.0143 - loss: 3.3400
Epoch 4/31
17/17 - 0s - 17ms/step - accuracy: 0.0143 - loss: 3.3250
Epoch 5/31
17/17 - 0s - 24ms/step - accuracy: 0.0143 - loss: 3.3098
Epoch 6/31
17/17 - 0s - 19ms/step - accuracy: 0.0143 - loss: 3.2944
Epoch 7/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 3.2787
Epoch 8/31
17/17 - 0s - 19ms/step - accuracy: 0.0143 - loss: 3.2629
Epoch 9/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 3.2470
Epoch 10/31
17/17 - 0s - 17ms/step - accuracy: 0.0143 - loss: 3.2308
Epoch 11/31
17/17 - 0s - 25ms/step - accuracy: 0.0143 - loss: 3.2146
Epoch 12/31
17/17 - 0s - 21ms/step - accuracy: 0.0143 - loss: 3.1981
Epoch 13/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 3.1816
Epoch 14/31
17/17 - 0s - 19ms/step - accuracy: 0.0143 - loss: 3.1648
Epoch 15/31
17/17 - 0s - 19ms/step - accuracy: 0.0143 - loss: 3.1480
Epoch 16/31
17/17 - 0s - 17ms/step - accuracy: 0.0143 - loss: 3.1310
Epoch 17/31
17/17 - 0s - 23ms/step - accuracy: 0.0143 - loss: 3.1139
Epoch 18/31
17/17 - 0s - 21ms/step - accuracy: 0.0143 - loss: 3.0967
Epoch 19/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 3.0794
Epoch 20/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 3.0620
Epoch 21/31
17/17 - 0s - 20ms/step - accuracy: 0.0143 - loss: 3.0445
Epoch 22/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 3.0269
Epoch 23/31
17/17 - 0s - 22ms/step - accuracy: 0.0143 - loss: 3.0092
Epoch 24/31
17/17 - 0s - 19ms/step - accuracy: 0.0143 - loss: 2.9914
Epoch 25/31
17/17 - 0s - 18ms/step - accuracy: 0.0143 - loss: 2.9735
Epoch 26/31
17/17 - 0s - 22ms/step - accuracy: 0.0143 - loss: 2.9556
Epoch 27/31
17/17 - 0s - 25ms/step - accuracy: 0.0143 - loss: 2.9376
Epoch 28/31
17/17 - 0s - 19ms/step - accuracy: 0.0143 - loss: 2.9194
Epoch 29/31
17/17 - 0s - 17ms/step - accuracy: 0.0143 - loss: 2.9013
Epoch 30/31
17/17 - 0s - 26ms/step - accuracy: 0.0143 - loss: 2.8830
Epoch 31/31
17/17 - 0s - 21ms/step - accuracy: 0.0143 - loss: 2.8648
5/5 - 0s - 73ms/step
| 9         | 0.08383   | 0.5513    | 854.0     | 0.3836    | 0.2937    | 31.46     | 2.26      | 1.887     | 1.051     | 0.2409    | 80.13     | 0.17      | 2.902     |
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 164ms/step - accuracy: 0.0200 - loss: 6.2311
Epoch 2/21
15/15 - 1s - 45ms/step - accuracy: 0.0235 - loss: 6.1637
Epoch 3/21
15/15 - 1s - 45ms/step - accuracy: 0.0234 - loss: 6.1237
Epoch 4/21
15/15 - 1s - 44ms/step - accuracy: 0.0227 - loss: 6.0677
Epoch 5/21
15/15 - 0s - 25ms/step - accuracy: 0.0264 - loss: 5.9996
Epoch 6/21
15/15 - 1s - 47ms/step - accuracy: 0.0285 - loss: 5.9549
Epoch 7/21
15/15 - 1s - 47ms/step - accuracy: 0.0306 - loss: 5.8841
Epoch 8/21
15/15 - 1s - 39ms/step - accuracy: 0.0319 - loss: 5.8018
Epoch 9/21
15/15 - 0s - 27ms/step - accuracy: 0.0346 - loss: 5.7412
Epoch 10/21
15/15 - 1s - 48ms/step - accuracy: 0.0370 - loss: 5.6724
Epoch 11/21
15/15 - 1s - 38ms/step - accuracy: 0.0389 - loss: 5.6325
Epoch 12/21
15/15 - 0s - 28ms/step - accuracy: 0.0410 - loss: 5.5633
Epoch 13/21
15/15 - 0s - 28ms/step - accuracy: 0.0450 - loss: 5.5075
Epoch 14/21
15/15 - 1s - 42ms/step - accuracy: 0.0456 - loss: 5.4470
Epoch 15/21
15/15 - 1s - 45ms/step - accuracy: 0.0520 - loss: 5.3657
Epoch 16/21
15/15 - 1s - 46ms/step - accuracy: 0.0532 - loss: 5.3210
Epoch 17/21
15/15 - 1s - 46ms/step - accuracy: 0.0574 - loss: 5.2525
Epoch 18/21
15/15 - 0s - 29ms/step - accuracy: 0.0614 - loss: 5.1889
Epoch 19/21
15/15 - 1s - 46ms/step - accuracy: 0.0679 - loss: 5.1125
Epoch 20/21
15/15 - 1s - 45ms/step - accuracy: 0.0690 - loss: 5.0508
Epoch 21/21
15/15 - 1s - 39ms/step - accuracy: 0.0751 - loss: 4.9843
4/4 - 0s - 88ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 161ms/step - accuracy: 0.1207 - loss: 3.3894
Epoch 2/21
15/15 - 1s - 44ms/step - accuracy: 0.1270 - loss: 3.3237
Epoch 3/21
15/15 - 1s - 42ms/step - accuracy: 0.1320 - loss: 3.3231
Epoch 4/21
15/15 - 0s - 27ms/step - accuracy: 0.1439 - loss: 3.2416
Epoch 5/21
15/15 - 0s - 24ms/step - accuracy: 0.1449 - loss: 3.2171
Epoch 6/21
15/15 - 1s - 49ms/step - accuracy: 0.1556 - loss: 3.1586
Epoch 7/21
15/15 - 1s - 44ms/step - accuracy: 0.1576 - loss: 3.1094
Epoch 8/21
15/15 - 1s - 43ms/step - accuracy: 0.1622 - loss: 3.0744
Epoch 9/21
15/15 - 1s - 44ms/step - accuracy: 0.1745 - loss: 3.0415
Epoch 10/21
15/15 - 1s - 44ms/step - accuracy: 0.1805 - loss: 2.9841
Epoch 11/21
15/15 - 0s - 23ms/step - accuracy: 0.1836 - loss: 2.9537
Epoch 12/21
15/15 - 0s - 23ms/step - accuracy: 0.1946 - loss: 2.9250
Epoch 13/21
15/15 - 0s - 27ms/step - accuracy: 0.1988 - loss: 2.8839
Epoch 14/21
15/15 - 1s - 47ms/step - accuracy: 0.2113 - loss: 2.8284
Epoch 15/21
15/15 - 1s - 43ms/step - accuracy: 0.2152 - loss: 2.8118
Epoch 16/21
15/15 - 1s - 42ms/step - accuracy: 0.2258 - loss: 2.7570
Epoch 17/21
15/15 - 1s - 48ms/step - accuracy: 0.2262 - loss: 2.7308
Epoch 18/21
15/15 - 1s - 45ms/step - accuracy: 0.2402 - loss: 2.6735
Epoch 19/21
15/15 - 1s - 46ms/step - accuracy: 0.2427 - loss: 2.6532
Epoch 20/21
15/15 - 1s - 42ms/step - accuracy: 0.2570 - loss: 2.6109
Epoch 21/21
15/15 - 0s - 24ms/step - accuracy: 0.2598 - loss: 2.5921
4/4 - 0s - 83ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 3s - 171ms/step - accuracy: 0.0630 - loss: 5.4320
Epoch 2/21
15/15 - 1s - 45ms/step - accuracy: 0.0611 - loss: 5.3802
Epoch 3/21
15/15 - 0s - 17ms/step - accuracy: 0.0646 - loss: 5.2986
Epoch 4/21
15/15 - 0s - 26ms/step - accuracy: 0.0649 - loss: 5.2415
Epoch 5/21
15/15 - 1s - 45ms/step - accuracy: 0.0662 - loss: 5.1906
Epoch 6/21
15/15 - 1s - 45ms/step - accuracy: 0.0664 - loss: 5.1161
Epoch 7/21
15/15 - 1s - 37ms/step - accuracy: 0.0658 - loss: 5.0659
Epoch 8/21
15/15 - 0s - 25ms/step - accuracy: 0.0671 - loss: 5.0077
Epoch 9/21
15/15 - 1s - 40ms/step - accuracy: 0.0673 - loss: 4.9352
Epoch 10/21
15/15 - 0s - 24ms/step - accuracy: 0.0702 - loss: 4.8644
Epoch 11/21
15/15 - 1s - 47ms/step - accuracy: 0.0662 - loss: 4.8161
Epoch 12/21
15/15 - 0s - 23ms/step - accuracy: 0.0704 - loss: 4.7737
Epoch 13/21
15/15 - 1s - 49ms/step - accuracy: 0.0739 - loss: 4.6846
Epoch 14/21
15/15 - 0s - 27ms/step - accuracy: 0.0742 - loss: 4.6393
Epoch 15/21
15/15 - 1s - 44ms/step - accuracy: 0.0744 - loss: 4.5714
Epoch 16/21
15/15 - 1s - 36ms/step - accuracy: 0.0773 - loss: 4.5022
Epoch 17/21
15/15 - 0s - 31ms/step - accuracy: 0.0791 - loss: 4.4451
Epoch 18/21
15/15 - 1s - 45ms/step - accuracy: 0.0794 - loss: 4.3756
Epoch 19/21
15/15 - 0s - 27ms/step - accuracy: 0.0850 - loss: 4.3058
Epoch 20/21
15/15 - 0s - 21ms/step - accuracy: 0.0856 - loss: 4.2516
Epoch 21/21
15/15 - 0s - 25ms/step - accuracy: 0.0871 - loss: 4.1775
4/4 - 0s - 86ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 163ms/step - accuracy: 0.0203 - loss: 12.7590
Epoch 2/21
15/15 - 1s - 39ms/step - accuracy: 0.0211 - loss: 12.6887
Epoch 3/21
15/15 - 0s - 18ms/step - accuracy: 0.0210 - loss: 12.6082
Epoch 4/21
15/15 - 0s - 17ms/step - accuracy: 0.0219 - loss: 12.5229
Epoch 5/21
15/15 - 0s - 17ms/step - accuracy: 0.0204 - loss: 12.4405
Epoch 6/21
15/15 - 0s - 18ms/step - accuracy: 0.0212 - loss: 12.3651
Epoch 7/21
15/15 - 0s - 13ms/step - accuracy: 0.0219 - loss: 12.2913
Epoch 8/21
15/15 - 0s - 28ms/step - accuracy: 0.0228 - loss: 12.1583
Epoch 9/21
15/15 - 0s - 24ms/step - accuracy: 0.0232 - loss: 12.1104
Epoch 10/21
15/15 - 0s - 24ms/step - accuracy: 0.0234 - loss: 11.9859
Epoch 11/21
15/15 - 0s - 21ms/step - accuracy: 0.0238 - loss: 11.9365
Epoch 12/21
15/15 - 0s - 20ms/step - accuracy: 0.0229 - loss: 11.8596
Epoch 13/21
15/15 - 0s - 19ms/step - accuracy: 0.0237 - loss: 11.7388
Epoch 14/21
15/15 - 0s - 21ms/step - accuracy: 0.0252 - loss: 11.6592
Epoch 15/21
15/15 - 0s - 19ms/step - accuracy: 0.0245 - loss: 11.5849
Epoch 16/21
15/15 - 0s - 27ms/step - accuracy: 0.0245 - loss: 11.4943
Epoch 17/21
15/15 - 0s - 23ms/step - accuracy: 0.0257 - loss: 11.4014
Epoch 18/21
15/15 - 0s - 16ms/step - accuracy: 0.0251 - loss: 11.3029
Epoch 19/21
15/15 - 0s - 24ms/step - accuracy: 0.0271 - loss: 11.2116
Epoch 20/21
15/15 - 0s - 31ms/step - accuracy: 0.0272 - loss: 11.1196
Epoch 21/21
15/15 - 1s - 44ms/step - accuracy: 0.0267 - loss: 11.0361
4/4 - 0s - 67ms/step
Epoch 1/21

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 3s - 223ms/step - accuracy: 0.1121 - loss: 4.2255
Epoch 2/21
15/15 - 1s - 43ms/step - accuracy: 0.1137 - loss: 4.1647
Epoch 3/21
15/15 - 1s - 42ms/step - accuracy: 0.1171 - loss: 4.1399
Epoch 4/21
15/15 - 1s - 46ms/step - accuracy: 0.1188 - loss: 4.0885
Epoch 5/21
15/15 - 1s - 46ms/step - accuracy: 0.1229 - loss: 4.0485
Epoch 6/21
15/15 - 1s - 42ms/step - accuracy: 0.1198 - loss: 3.9844
Epoch 7/21
15/15 - 1s - 47ms/step - accuracy: 0.1274 - loss: 3.9405
Epoch 8/21
15/15 - 1s - 45ms/step - accuracy: 0.1286 - loss: 3.8993
Epoch 9/21
15/15 - 0s - 25ms/step - accuracy: 0.1304 - loss: 3.8359
Epoch 10/21
15/15 - 0s - 25ms/step - accuracy: 0.1324 - loss: 3.8125
Epoch 11/21
15/15 - 0s - 27ms/step - accuracy: 0.1383 - loss: 3.7489
Epoch 12/21
15/15 - 0s - 27ms/step - accuracy: 0.1408 - loss: 3.7001
Epoch 13/21
15/15 - 1s - 44ms/step - accuracy: 0.1431 - loss: 3.6577
Epoch 14/21
15/15 - 0s - 28ms/step - accuracy: 0.1471 - loss: 3.6228
Epoch 15/21
15/15 - 0s - 24ms/step - accuracy: 0.1499 - loss: 3.5541
Epoch 16/21
15/15 - 1s - 45ms/step - accuracy: 0.1523 - loss: 3.5327
Epoch 17/21
15/15 - 0s - 27ms/step - accuracy: 0.1607 - loss: 3.4943
Epoch 18/21
15/15 - 1s - 38ms/step - accuracy: 0.1604 - loss: 3.4316
Epoch 19/21
15/15 - 0s - 29ms/step - accuracy: 0.1664 - loss: 3.4084
Epoch 20/21
15/15 - 1s - 43ms/step - accuracy: 0.1695 - loss: 3.3523
Epoch 21/21
15/15 - 0s - 20ms/step - accuracy: 0.1718 - loss: 3.3008
4/4 - 0s - 68ms/step
| 10        | nan       | 5.353     | 928.7     | 0.5064    | 0.1316    | 20.97     | 1.457     | 1.363     | 1.485     | 0.8114    | 56.74     | 0.3686    | 3.236     |
Epoch 1/22

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 4s - 171ms/step - accuracy: 0.6016 - loss: 1.3796
Epoch 2/22
22/22 - 0s - 21ms/step - accuracy: 0.7012 - loss: 0.8915
Epoch 3/22
22/22 - 1s - 28ms/step - accuracy: 0.7215 - loss: 0.8246
Epoch 4/22
22/22 - 0s - 22ms/step - accuracy: 0.7362 - loss: 0.7815
Epoch 5/22
22/22 - 1s - 25ms/step - accuracy: 0.7433 - loss: 0.7499
Epoch 6/22
22/22 - 0s - 20ms/step - accuracy: 0.7550 - loss: 0.7225
Epoch 7/22
22/22 - 1s - 29ms/step - accuracy: 0.7611 - loss: 0.7017
Epoch 8/22
22/22 - 1s - 30ms/step - accuracy: 0.7656 - loss: 0.6862
Epoch 9/22
22/22 - 1s - 25ms/step - accuracy: 0.7717 - loss: 0.6701
Epoch 10/22
22/22 - 1s - 25ms/step - accuracy: 0.7718 - loss: 0.6581
Epoch 11/22
22/22 - 1s - 24ms/step - accuracy: 0.7749 - loss: 0.6454
Epoch 12/22
22/22 - 1s - 33ms/step - accuracy: 0.7797 - loss: 0.6331
Epoch 13/22
22/22 - 1s - 58ms/step - accuracy: 0.7846 - loss: 0.6227
Epoch 14/22
22/22 - 1s - 31ms/step - accuracy: 0.7870 - loss: 0.6129
Epoch 15/22
22/22 - 1s - 58ms/step - accuracy: 0.7898 - loss: 0.6047
Epoch 16/22
22/22 - 1s - 23ms/step - accuracy: 0.7941 - loss: 0.5933
Epoch 17/22
22/22 - 1s - 30ms/step - accuracy: 0.7958 - loss: 0.5847
Epoch 18/22
22/22 - 1s - 23ms/step - accuracy: 0.7977 - loss: 0.5771
Epoch 19/22
22/22 - 0s - 22ms/step - accuracy: 0.8001 - loss: 0.5709
Epoch 20/22
22/22 - 1s - 32ms/step - accuracy: 0.8021 - loss: 0.5618
Epoch 21/22
22/22 - 1s - 30ms/step - accuracy: 0.8059 - loss: 0.5547
Epoch 22/22
22/22 - 1s - 27ms/step - accuracy: 0.8088 - loss: 0.5510
6/6 - 0s - 75ms/step
Epoch 1/22

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 4s - 176ms/step - accuracy: 0.6045 - loss: 1.4105
Epoch 2/22
22/22 - 1s - 24ms/step - accuracy: 0.6852 - loss: 0.9217
Epoch 3/22
22/22 - 1s - 35ms/step - accuracy: 0.7015 - loss: 0.8670
Epoch 4/22
22/22 - 1s - 34ms/step - accuracy: 0.7111 - loss: 0.8329
Epoch 5/22
22/22 - 1s - 51ms/step - accuracy: 0.7210 - loss: 0.8070
Epoch 6/22
22/22 - 1s - 31ms/step - accuracy: 0.7290 - loss: 0.7849
Epoch 7/22
22/22 - 1s - 61ms/step - accuracy: 0.7358 - loss: 0.7665
Epoch 8/22
22/22 - 1s - 24ms/step - accuracy: 0.7388 - loss: 0.7508
Epoch 9/22
22/22 - 1s - 31ms/step - accuracy: 0.7422 - loss: 0.7353
Epoch 10/22
22/22 - 1s - 54ms/step - accuracy: 0.7477 - loss: 0.7223
Epoch 11/22
22/22 - 1s - 28ms/step - accuracy: 0.7535 - loss: 0.7083
Epoch 12/22
22/22 - 1s - 28ms/step - accuracy: 0.7564 - loss: 0.6962
Epoch 13/22
22/22 - 1s - 32ms/step - accuracy: 0.7603 - loss: 0.6861
Epoch 14/22
22/22 - 1s - 26ms/step - accuracy: 0.7640 - loss: 0.6730
Epoch 15/22
22/22 - 1s - 31ms/step - accuracy: 0.7687 - loss: 0.6617
Epoch 16/22
22/22 - 1s - 62ms/step - accuracy: 0.7714 - loss: 0.6523
Epoch 17/22
22/22 - 0s - 22ms/step - accuracy: 0.7752 - loss: 0.6433
Epoch 18/22
22/22 - 1s - 26ms/step - accuracy: 0.7797 - loss: 0.6330
Epoch 19/22
22/22 - 0s - 22ms/step - accuracy: 0.7774 - loss: 0.6262
Epoch 20/22
22/22 - 1s - 24ms/step - accuracy: 0.7812 - loss: 0.6154
Epoch 21/22
22/22 - 1s - 31ms/step - accuracy: 0.7846 - loss: 0.6075
Epoch 22/22
22/22 - 1s - 52ms/step - accuracy: 0.7876 - loss: 0.5945
6/6 - 0s - 57ms/step
Epoch 1/22

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 4s - 172ms/step - accuracy: 0.6073 - loss: 1.3630
Epoch 2/22
22/22 - 0s - 20ms/step - accuracy: 0.6946 - loss: 0.9176
Epoch 3/22
22/22 - 1s - 26ms/step - accuracy: 0.7101 - loss: 0.8573
Epoch 4/22
22/22 - 1s - 30ms/step - accuracy: 0.7208 - loss: 0.8171
Epoch 5/22
22/22 - 0s - 21ms/step - accuracy: 0.7340 - loss: 0.7859
Epoch 6/22
22/22 - 1s - 39ms/step - accuracy: 0.7407 - loss: 0.7649
Epoch 7/22
22/22 - 1s - 26ms/step - accuracy: 0.7463 - loss: 0.7427
Epoch 8/22
22/22 - 1s - 33ms/step - accuracy: 0.7547 - loss: 0.7224
Epoch 9/22
22/22 - 1s - 29ms/step - accuracy: 0.7602 - loss: 0.7087
Epoch 10/22
22/22 - 1s - 27ms/step - accuracy: 0.7644 - loss: 0.6929
Epoch 11/22
22/22 - 1s - 26ms/step - accuracy: 0.7699 - loss: 0.6771
Epoch 12/22
22/22 - 1s - 23ms/step - accuracy: 0.7710 - loss: 0.6637
Epoch 13/22
22/22 - 1s - 25ms/step - accuracy: 0.7772 - loss: 0.6496
Epoch 14/22
22/22 - 0s - 22ms/step - accuracy: 0.7788 - loss: 0.6423
Epoch 15/22
22/22 - 1s - 30ms/step - accuracy: 0.7829 - loss: 0.6287
Epoch 16/22
22/22 - 1s - 60ms/step - accuracy: 0.7877 - loss: 0.6195
Epoch 17/22
22/22 - 1s - 31ms/step - accuracy: 0.7875 - loss: 0.6097
Epoch 18/22
22/22 - 1s - 31ms/step - accuracy: 0.7922 - loss: 0.5992
Epoch 19/22
22/22 - 1s - 25ms/step - accuracy: 0.7952 - loss: 0.5928
Epoch 20/22
22/22 - 1s - 29ms/step - accuracy: 0.7950 - loss: 0.5856
Epoch 21/22
22/22 - 1s - 24ms/step - accuracy: 0.7989 - loss: 0.5776
Epoch 22/22
22/22 - 1s - 29ms/step - accuracy: 0.8052 - loss: 0.5686
6/6 - 0s - 62ms/step

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/22
22/22 - 4s - 179ms/step - accuracy: 0.6009 - loss: 1.3238
Epoch 2/22
22/22 - 0s - 21ms/step - accuracy: 0.6901 - loss: 0.8994
Epoch 3/22
22/22 - 1s - 28ms/step - accuracy: 0.7142 - loss: 0.8371
Epoch 4/22
22/22 - 1s - 33ms/step - accuracy: 0.7270 - loss: 0.7972
Epoch 5/22
22/22 - 1s - 57ms/step - accuracy: 0.7397 - loss: 0.7659
Epoch 6/22
22/22 - 1s - 27ms/step - accuracy: 0.7468 - loss: 0.7407
Epoch 7/22
22/22 - 1s - 35ms/step - accuracy: 0.7572 - loss: 0.7163
Epoch 8/22
22/22 - 1s - 29ms/step - accuracy: 0.7601 - loss: 0.6984
Epoch 9/22
22/22 - 0s - 21ms/step - accuracy: 0.7683 - loss: 0.6789
Epoch 10/22
22/22 - 1s - 33ms/step - accuracy: 0.7678 - loss: 0.6666
Epoch 11/22
22/22 - 1s - 28ms/step - accuracy: 0.7733 - loss: 0.6538
Epoch 12/22
22/22 - 1s - 29ms/step - accuracy: 0.7797 - loss: 0.6371
Epoch 13/22
22/22 - 0s - 21ms/step - accuracy: 0.7828 - loss: 0.6238
Epoch 14/22
22/22 - 0s - 21ms/step - accuracy: 0.7866 - loss: 0.6118
Epoch 15/22
22/22 - 1s - 24ms/step - accuracy: 0.7889 - loss: 0.6064
Epoch 16/22
22/22 - 1s - 24ms/step - accuracy: 0.7901 - loss: 0.5953
Epoch 17/22
22/22 - 1s - 23ms/step - accuracy: 0.7964 - loss: 0.5839
Epoch 18/22
22/22 - 1s - 31ms/step - accuracy: 0.7970 - loss: 0.5748
Epoch 19/22
22/22 - 1s - 28ms/step - accuracy: 0.8007 - loss: 0.5684
Epoch 20/22
22/22 - 1s - 34ms/step - accuracy: 0.8031 - loss: 0.5596
Epoch 21/22
22/22 - 0s - 21ms/step - accuracy: 0.8061 - loss: 0.5510
Epoch 22/22
22/22 - 1s - 34ms/step - accuracy: 0.8087 - loss: 0.5434
6/6 - 0s - 58ms/step
Epoch 1/22

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 4s - 164ms/step - accuracy: 0.6334 - loss: 1.1500
Epoch 2/22
22/22 - 1s - 23ms/step - accuracy: 0.7125 - loss: 0.8535
Epoch 3/22
22/22 - 0s - 21ms/step - accuracy: 0.7338 - loss: 0.7903
Epoch 4/22
22/22 - 1s - 28ms/step - accuracy: 0.7429 - loss: 0.7545
Epoch 5/22
22/22 - 1s - 26ms/step - accuracy: 0.7567 - loss: 0.7254
Epoch 6/22
22/22 - 1s - 27ms/step - accuracy: 0.7667 - loss: 0.7015
Epoch 7/22
22/22 - 1s - 36ms/step - accuracy: 0.7675 - loss: 0.6854
Epoch 8/22
22/22 - 1s - 23ms/step - accuracy: 0.7733 - loss: 0.6693
Epoch 9/22
22/22 - 1s - 32ms/step - accuracy: 0.7755 - loss: 0.6501
Epoch 10/22
22/22 - 1s - 29ms/step - accuracy: 0.7812 - loss: 0.6348
Epoch 11/22
22/22 - 1s - 23ms/step - accuracy: 0.7821 - loss: 0.6233
Epoch 12/22
22/22 - 1s - 28ms/step - accuracy: 0.7864 - loss: 0.6122
Epoch 13/22
22/22 - 1s - 32ms/step - accuracy: 0.7923 - loss: 0.5996
Epoch 14/22
22/22 - 1s - 29ms/step - accuracy: 0.7920 - loss: 0.5896
Epoch 15/22
22/22 - 1s - 28ms/step - accuracy: 0.7956 - loss: 0.5815
Epoch 16/22
22/22 - 0s - 21ms/step - accuracy: 0.7973 - loss: 0.5733
Epoch 17/22
22/22 - 0s - 21ms/step - accuracy: 0.8057 - loss: 0.5575
Epoch 18/22
22/22 - 1s - 24ms/step - accuracy: 0.8065 - loss: 0.5472
Epoch 19/22
22/22 - 1s - 23ms/step - accuracy: 0.8091 - loss: 0.5419
Epoch 20/22
22/22 - 1s - 27ms/step - accuracy: 0.8123 - loss: 0.5302
Epoch 21/22
22/22 - 0s - 23ms/step - accuracy: 0.8174 - loss: 0.5242
Epoch 22/22
22/22 - 1s - 25ms/step - accuracy: 0.8171 - loss: 0.5170
6/6 - 1s - 84ms/step
| 11        | 0.796     | 5.444     | 645.9     | 0.03305   | 0.1197    | 22.5      | 1.966     | 2.713     | 2.696     | 0.3766    | 74.63     | 0.004611  | 5.349     |
Epoch 1/39

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 190ms/step - accuracy: 0.6442 - loss: nan
Epoch 2/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/39
16/16 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/39
16/16 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/39
16/16 - 1s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/39
16/16 - 0s - 10ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/39
16/16 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/39
16/16 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/39
16/16 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/39
16/16 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/39
16/16 - 0s - 17ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/39
16/16 - 0s - 17ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/39
16/16 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/39
16/16 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/39
16/16 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/39
16/16 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/39
16/16 - 1s - 43ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/39
16/16 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/39
16/16 - 1s - 39ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 86ms/step
Epoch 1/39

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 4s - 239ms/step - accuracy: 0.6048 - loss: nan
Epoch 2/39
16/16 - 0s - 19ms/step - accuracy: 0.6443 - loss: nan
Epoch 3/39
16/16 - 0s - 27ms/step - accuracy: 0.6443 - loss: nan
Epoch 4/39
16/16 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 5/39
16/16 - 1s - 42ms/step - accuracy: 0.6443 - loss: nan
Epoch 6/39
16/16 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 7/39
16/16 - 0s - 20ms/step - accuracy: 0.6443 - loss: nan
Epoch 8/39
16/16 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 9/39
16/16 - 1s - 42ms/step - accuracy: 0.6443 - loss: nan
Epoch 10/39
16/16 - 1s - 39ms/step - accuracy: 0.6443 - loss: nan
Epoch 11/39
16/16 - 0s - 22ms/step - accuracy: 0.6443 - loss: nan
Epoch 12/39
16/16 - 1s - 41ms/step - accuracy: 0.6443 - loss: nan
Epoch 13/39
16/16 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 14/39
16/16 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 15/39
16/16 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 16/39
16/16 - 0s - 16ms/step - accuracy: 0.6443 - loss: nan
Epoch 17/39
16/16 - 0s - 29ms/step - accuracy: 0.6443 - loss: nan
Epoch 18/39
16/16 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 19/39
16/16 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 20/39
16/16 - 1s - 41ms/step - accuracy: 0.6443 - loss: nan
Epoch 21/39
16/16 - 1s - 43ms/step - accuracy: 0.6443 - loss: nan
Epoch 22/39
16/16 - 1s - 41ms/step - accuracy: 0.6443 - loss: nan
Epoch 23/39
16/16 - 1s - 38ms/step - accuracy: 0.6443 - loss: nan
Epoch 24/39
16/16 - 0s - 25ms/step - accuracy: 0.6443 - loss: nan
Epoch 25/39
16/16 - 1s - 37ms/step - accuracy: 0.6443 - loss: nan
Epoch 26/39
16/16 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
Epoch 27/39
16/16 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 28/39
16/16 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 29/39
16/16 - 1s - 38ms/step - accuracy: 0.6443 - loss: nan
Epoch 30/39
16/16 - 0s - 19ms/step - accuracy: 0.6443 - loss: nan
Epoch 31/39
16/16 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 32/39
16/16 - 0s - 15ms/step - accuracy: 0.6443 - loss: nan
Epoch 33/39
16/16 - 0s - 26ms/step - accuracy: 0.6443 - loss: nan
Epoch 34/39
16/16 - 0s - 23ms/step - accuracy: 0.6443 - loss: nan
Epoch 35/39
16/16 - 1s - 43ms/step - accuracy: 0.6443 - loss: nan
Epoch 36/39
16/16 - 0s - 24ms/step - accuracy: 0.6443 - loss: nan
Epoch 37/39
16/16 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 38/39
16/16 - 1s - 40ms/step - accuracy: 0.6443 - loss: nan
Epoch 39/39
16/16 - 0s - 21ms/step - accuracy: 0.6443 - loss: nan
4/4 - 0s - 88ms/step
Epoch 1/39

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 194ms/step - accuracy: 0.6155 - loss: nan
Epoch 2/39
16/16 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/39
16/16 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/39
16/16 - 0s - 26ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/39
16/16 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/39
16/16 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/39
16/16 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/39
16/16 - 1s - 32ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/39
16/16 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/39
16/16 - 0s - 24ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/39
16/16 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/39
16/16 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/39
16/16 - 1s - 43ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/39
16/16 - 1s - 46ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/39
16/16 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/39
16/16 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/39
16/16 - 1s - 46ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/39
16/16 - 1s - 39ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/39
16/16 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/39
16/16 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/39
16/16 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/39
16/16 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/39
16/16 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/39
16/16 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/39
16/16 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/39
16/16 - 0s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/39
16/16 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/39
16/16 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/39
16/16 - 0s - 17ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/39
16/16 - 0s - 29ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/39
16/16 - 1s - 39ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/39
16/16 - 0s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/39
16/16 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 86ms/step
Epoch 1/39

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 193ms/step - accuracy: 0.6132 - loss: nan
Epoch 2/39
16/16 - 1s - 35ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/39
16/16 - 0s - 10ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/39
16/16 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/39
16/16 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/39
16/16 - 0s - 17ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/39
16/16 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/39
16/16 - 0s - 30ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/39
16/16 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/39
16/16 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/39
16/16 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/39
16/16 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/39
16/16 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/39
16/16 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/39
16/16 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/39
16/16 - 1s - 42ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/39
16/16 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/39
16/16 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/39
16/16 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 79ms/step
Epoch 1/39

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 201ms/step - accuracy: 0.6076 - loss: nan
Epoch 2/39
16/16 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 3/39
16/16 - 0s - 18ms/step - accuracy: 0.6442 - loss: nan
Epoch 4/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 5/39
16/16 - 0s - 20ms/step - accuracy: 0.6442 - loss: nan
Epoch 6/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 7/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 8/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 9/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 10/39
16/16 - 0s - 27ms/step - accuracy: 0.6442 - loss: nan
Epoch 11/39
16/16 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 12/39
16/16 - 0s - 11ms/step - accuracy: 0.6442 - loss: nan
Epoch 13/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 14/39
16/16 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 15/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 16/39
16/16 - 0s - 15ms/step - accuracy: 0.6442 - loss: nan
Epoch 17/39
16/16 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 18/39
16/16 - 0s - 21ms/step - accuracy: 0.6442 - loss: nan
Epoch 19/39
16/16 - 1s - 41ms/step - accuracy: 0.6442 - loss: nan
Epoch 20/39
16/16 - 0s - 14ms/step - accuracy: 0.6442 - loss: nan
Epoch 21/39
16/16 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 22/39
16/16 - 0s - 28ms/step - accuracy: 0.6442 - loss: nan
Epoch 23/39
16/16 - 1s - 38ms/step - accuracy: 0.6442 - loss: nan
Epoch 24/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 25/39
16/16 - 1s - 37ms/step - accuracy: 0.6442 - loss: nan
Epoch 26/39
16/16 - 0s - 22ms/step - accuracy: 0.6442 - loss: nan
Epoch 27/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 28/39
16/16 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 29/39
16/16 - 1s - 39ms/step - accuracy: 0.6442 - loss: nan
Epoch 30/39
16/16 - 0s - 19ms/step - accuracy: 0.6442 - loss: nan
Epoch 31/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
Epoch 32/39
16/16 - 1s - 40ms/step - accuracy: 0.6442 - loss: nan
Epoch 33/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 34/39
16/16 - 0s - 12ms/step - accuracy: 0.6442 - loss: nan
Epoch 35/39
16/16 - 0s - 16ms/step - accuracy: 0.6442 - loss: nan
Epoch 36/39
16/16 - 0s - 23ms/step - accuracy: 0.6442 - loss: nan
Epoch 37/39
16/16 - 1s - 36ms/step - accuracy: 0.6442 - loss: nan
Epoch 38/39
16/16 - 0s - 13ms/step - accuracy: 0.6442 - loss: nan
Epoch 39/39
16/16 - 0s - 25ms/step - accuracy: 0.6442 - loss: nan
4/4 - 0s - 74ms/step
| 12        | 0.6442    | 6.72      | 887.1     | 0.4568    | 0.2843    | 39.12     | 1.995     | 1.378     | 2.52      | 0.3775    | 28.83     | 0.3226    | 1.443     |
Epoch 1/40

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

45/45 - 5s - 110ms/step - accuracy: 0.4450 - loss: 2.1410
Epoch 2/40
45/45 - 2s - 51ms/step - accuracy: 0.6097 - loss: 1.4597
Epoch 3/40
45/45 - 1s - 18ms/step - accuracy: 0.6316 - loss: 1.2451
Epoch 4/40
45/45 - 1s - 30ms/step - accuracy: 0.6502 - loss: 1.1500
Epoch 5/40
45/45 - 1s - 29ms/step - accuracy: 0.6581 - loss: 1.0924
Epoch 6/40
45/45 - 3s - 61ms/step - accuracy: 0.6650 - loss: 1.0576
Epoch 7/40
45/45 - 2s - 55ms/step - accuracy: 0.6666 - loss: 1.0331
Epoch 8/40
45/45 - 1s - 31ms/step - accuracy: 0.6698 - loss: 1.0144
Epoch 9/40
45/45 - 1s - 24ms/step - accuracy: 0.6719 - loss: 0.9952
Epoch 10/40
45/45 - 1s - 27ms/step - accuracy: 0.6765 - loss: 0.9818
Epoch 11/40
45/45 - 2s - 34ms/step - accuracy: 0.6777 - loss: 0.9681
Epoch 12/40
45/45 - 1s - 30ms/step - accuracy: 0.6824 - loss: 0.9559
Epoch 13/40
45/45 - 1s - 29ms/step - accuracy: 0.6817 - loss: 0.9481
Epoch 14/40
45/45 - 1s - 23ms/step - accuracy: 0.6855 - loss: 0.9383
Epoch 15/40
45/45 - 1s - 24ms/step - accuracy: 0.6873 - loss: 0.9312
Epoch 16/40
45/45 - 2s - 37ms/step - accuracy: 0.6906 - loss: 0.9208
Epoch 17/40
45/45 - 1s - 16ms/step - accuracy: 0.6952 - loss: 0.9139
Epoch 18/40
45/45 - 1s - 19ms/step - accuracy: 0.6967 - loss: 0.9050
Epoch 19/40
45/45 - 1s - 17ms/step - accuracy: 0.6979 - loss: 0.8983
Epoch 20/40
45/45 - 1s - 18ms/step - accuracy: 0.7010 - loss: 0.8903
Epoch 21/40
45/45 - 1s - 17ms/step - accuracy: 0.7035 - loss: 0.8862
Epoch 22/40
45/45 - 1s - 22ms/step - accuracy: 0.7043 - loss: 0.8779
Epoch 23/40
45/45 - 1s - 20ms/step - accuracy: 0.7075 - loss: 0.8728
Epoch 24/40
45/45 - 1s - 20ms/step - accuracy: 0.7084 - loss: 0.8691
Epoch 25/40
45/45 - 1s - 21ms/step - accuracy: 0.7088 - loss: 0.8630
Epoch 26/40
45/45 - 1s - 26ms/step - accuracy: 0.7115 - loss: 0.8571
Epoch 27/40
45/45 - 1s - 31ms/step - accuracy: 0.7141 - loss: 0.8521
Epoch 28/40
45/45 - 3s - 57ms/step - accuracy: 0.7147 - loss: 0.8457
Epoch 29/40
45/45 - 1s - 26ms/step - accuracy: 0.7155 - loss: 0.8451
Epoch 30/40
45/45 - 2s - 36ms/step - accuracy: 0.7172 - loss: 0.8408
Epoch 31/40
45/45 - 2s - 55ms/step - accuracy: 0.7178 - loss: 0.8347
Epoch 32/40
45/45 - 3s - 58ms/step - accuracy: 0.7189 - loss: 0.8313
Epoch 33/40
45/45 - 3s - 57ms/step - accuracy: 0.7229 - loss: 0.8280
Epoch 34/40
45/45 - 1s - 32ms/step - accuracy: 0.7253 - loss: 0.8240
Epoch 35/40
45/45 - 3s - 60ms/step - accuracy: 0.7263 - loss: 0.8188
Epoch 36/40
45/45 - 1s - 31ms/step - accuracy: 0.7259 - loss: 0.8169
Epoch 37/40
45/45 - 1s - 29ms/step - accuracy: 0.7298 - loss: 0.8127
Epoch 38/40
45/45 - 1s - 29ms/step - accuracy: 0.7295 - loss: 0.8096
Epoch 39/40
45/45 - 3s - 59ms/step - accuracy: 0.7301 - loss: 0.8050
Epoch 40/40
45/45 - 3s - 62ms/step - accuracy: 0.7312 - loss: 0.8014
12/12 - 1s - 45ms/step

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/40
45/45 - 4s - 90ms/step - accuracy: 0.3994 - loss: 2.1043
Epoch 2/40
45/45 - 1s - 32ms/step - accuracy: 0.5914 - loss: 1.4775
Epoch 3/40
45/45 - 3s - 58ms/step - accuracy: 0.6226 - loss: 1.2762
Epoch 4/40
45/45 - 3s - 58ms/step - accuracy: 0.6402 - loss: 1.1739
Epoch 5/40
45/45 - 3s - 58ms/step - accuracy: 0.6460 - loss: 1.1136
Epoch 6/40
45/45 - 1s - 30ms/step - accuracy: 0.6529 - loss: 1.0692
Epoch 7/40
45/45 - 1s - 28ms/step - accuracy: 0.6528 - loss: 1.0413
Epoch 8/40
45/45 - 1s - 31ms/step - accuracy: 0.6547 - loss: 1.0197
Epoch 9/40
45/45 - 1s - 19ms/step - accuracy: 0.6582 - loss: 1.0038
Epoch 10/40
45/45 - 1s - 21ms/step - accuracy: 0.6568 - loss: 0.9891
Epoch 11/40
45/45 - 1s - 20ms/step - accuracy: 0.6613 - loss: 0.9775
Epoch 12/40
45/45 - 1s - 16ms/step - accuracy: 0.6647 - loss: 0.9652
Epoch 13/40
45/45 - 1s - 21ms/step - accuracy: 0.6639 - loss: 0.9578
Epoch 14/40
45/45 - 1s - 28ms/step - accuracy: 0.6662 - loss: 0.9499
Epoch 15/40
45/45 - 1s - 22ms/step - accuracy: 0.6675 - loss: 0.9425
Epoch 16/40
45/45 - 1s - 16ms/step - accuracy: 0.6704 - loss: 0.9357
Epoch 17/40
45/45 - 1s - 21ms/step - accuracy: 0.6733 - loss: 0.9264
Epoch 18/40
45/45 - 1s - 29ms/step - accuracy: 0.6730 - loss: 0.9229
Epoch 19/40
45/45 - 1s - 31ms/step - accuracy: 0.6768 - loss: 0.9168
Epoch 20/40
45/45 - 1s - 33ms/step - accuracy: 0.6795 - loss: 0.9091
Epoch 21/40
45/45 - 3s - 58ms/step - accuracy: 0.6827 - loss: 0.9037
Epoch 22/40
45/45 - 1s - 32ms/step - accuracy: 0.6824 - loss: 0.9005
Epoch 23/40
45/45 - 2s - 48ms/step - accuracy: 0.6885 - loss: 0.8946
Epoch 24/40
45/45 - 1s - 30ms/step - accuracy: 0.6886 - loss: 0.8906
Epoch 25/40
45/45 - 3s - 58ms/step - accuracy: 0.6921 - loss: 0.8839
Epoch 26/40
45/45 - 1s - 25ms/step - accuracy: 0.6929 - loss: 0.8805
Epoch 27/40
45/45 - 1s - 27ms/step - accuracy: 0.6922 - loss: 0.8759
Epoch 28/40
45/45 - 1s - 16ms/step - accuracy: 0.6945 - loss: 0.8704
Epoch 29/40
45/45 - 1s - 28ms/step - accuracy: 0.6931 - loss: 0.8705
Epoch 30/40
45/45 - 1s - 25ms/step - accuracy: 0.6961 - loss: 0.8652
Epoch 31/40
45/45 - 2s - 38ms/step - accuracy: 0.6953 - loss: 0.8623
Epoch 32/40
45/45 - 1s - 30ms/step - accuracy: 0.7003 - loss: 0.8564
Epoch 33/40
45/45 - 2s - 54ms/step - accuracy: 0.7021 - loss: 0.8542
Epoch 34/40
45/45 - 2s - 36ms/step - accuracy: 0.7032 - loss: 0.8512
Epoch 35/40
45/45 - 2s - 42ms/step - accuracy: 0.7052 - loss: 0.8458
Epoch 36/40
45/45 - 1s - 32ms/step - accuracy: 0.7075 - loss: 0.8437
Epoch 37/40
45/45 - 1s - 32ms/step - accuracy: 0.7080 - loss: 0.8403
Epoch 38/40
45/45 - 1s - 29ms/step - accuracy: 0.7091 - loss: 0.8365
Epoch 39/40
45/45 - 1s - 30ms/step - accuracy: 0.7138 - loss: 0.8334
Epoch 40/40
45/45 - 1s - 28ms/step - accuracy: 0.7105 - loss: 0.8318
12/12 - 0s - 34ms/step
Epoch 1/40

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

45/45 - 4s - 83ms/step - accuracy: 0.4876 - loss: 2.0456
Epoch 2/40
45/45 - 1s - 31ms/step - accuracy: 0.6328 - loss: 1.4648
Epoch 3/40
45/45 - 2s - 51ms/step - accuracy: 0.6414 - loss: 1.2663
Epoch 4/40
45/45 - 1s - 33ms/step - accuracy: 0.6481 - loss: 1.1723
Epoch 5/40
45/45 - 1s - 28ms/step - accuracy: 0.6489 - loss: 1.1172
Epoch 6/40
45/45 - 2s - 36ms/step - accuracy: 0.6501 - loss: 1.0800
Epoch 7/40
45/45 - 3s - 57ms/step - accuracy: 0.6528 - loss: 1.0518
Epoch 8/40
45/45 - 3s - 56ms/step - accuracy: 0.6577 - loss: 1.0303
Epoch 9/40
45/45 - 2s - 53ms/step - accuracy: 0.6613 - loss: 1.0124
Epoch 10/40
45/45 - 2s - 38ms/step - accuracy: 0.6583 - loss: 0.9949
Epoch 11/40
45/45 - 1s - 25ms/step - accuracy: 0.6648 - loss: 0.9818
Epoch 12/40
45/45 - 1s - 26ms/step - accuracy: 0.6661 - loss: 0.9719
Epoch 13/40
45/45 - 2s - 34ms/step - accuracy: 0.6685 - loss: 0.9639
Epoch 14/40
45/45 - 1s - 33ms/step - accuracy: 0.6728 - loss: 0.9542
Epoch 15/40
45/45 - 2s - 52ms/step - accuracy: 0.6723 - loss: 0.9451
Epoch 16/40
45/45 - 1s - 31ms/step - accuracy: 0.6779 - loss: 0.9379
Epoch 17/40
45/45 - 3s - 59ms/step - accuracy: 0.6785 - loss: 0.9315
Epoch 18/40
45/45 - 3s - 61ms/step - accuracy: 0.6810 - loss: 0.9243
Epoch 19/40
45/45 - 1s - 30ms/step - accuracy: 0.6832 - loss: 0.9176
Epoch 20/40
45/45 - 1s - 30ms/step - accuracy: 0.6837 - loss: 0.9116
Epoch 21/40
45/45 - 2s - 34ms/step - accuracy: 0.6872 - loss: 0.9064
Epoch 22/40
45/45 - 2s - 54ms/step - accuracy: 0.6882 - loss: 0.9014
Epoch 23/40
45/45 - 2s - 34ms/step - accuracy: 0.6885 - loss: 0.8967
Epoch 24/40
45/45 - 2s - 54ms/step - accuracy: 0.6935 - loss: 0.8907
Epoch 25/40
45/45 - 3s - 61ms/step - accuracy: 0.6919 - loss: 0.8867
Epoch 26/40
45/45 - 3s - 59ms/step - accuracy: 0.6969 - loss: 0.8848
Epoch 27/40
45/45 - 3s - 59ms/step - accuracy: 0.6990 - loss: 0.8771
Epoch 28/40
45/45 - 3s - 57ms/step - accuracy: 0.7003 - loss: 0.8727
Epoch 29/40
45/45 - 3s - 57ms/step - accuracy: 0.7019 - loss: 0.8690
Epoch 30/40
45/45 - 1s - 29ms/step - accuracy: 0.7013 - loss: 0.8650
Epoch 31/40
45/45 - 1s - 29ms/step - accuracy: 0.7042 - loss: 0.8619
Epoch 32/40
45/45 - 1s - 29ms/step - accuracy: 0.7069 - loss: 0.8581
Epoch 33/40
45/45 - 1s - 33ms/step - accuracy: 0.7056 - loss: 0.8553
Epoch 34/40
45/45 - 2s - 56ms/step - accuracy: 0.7097 - loss: 0.8516
Epoch 35/40
45/45 - 2s - 34ms/step - accuracy: 0.7120 - loss: 0.8466
Epoch 36/40
45/45 - 1s - 32ms/step - accuracy: 0.7108 - loss: 0.8459
Epoch 37/40
45/45 - 3s - 60ms/step - accuracy: 0.7146 - loss: 0.8429
Epoch 38/40
45/45 - 2s - 52ms/step - accuracy: 0.7124 - loss: 0.8377
Epoch 39/40
45/45 - 1s - 31ms/step - accuracy: 0.7187 - loss: 0.8331
Epoch 40/40
45/45 - 2s - 34ms/step - accuracy: 0.7151 - loss: 0.8324
12/12 - 1s - 46ms/step
Epoch 1/40

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

45/45 - 4s - 90ms/step - accuracy: 0.4144 - loss: 2.1078
Epoch 2/40
45/45 - 1s - 33ms/step - accuracy: 0.6139 - loss: 1.4531
Epoch 3/40
45/45 - 2s - 55ms/step - accuracy: 0.6410 - loss: 1.2230
Epoch 4/40
45/45 - 1s - 29ms/step - accuracy: 0.6536 - loss: 1.1253
Epoch 5/40
45/45 - 3s - 62ms/step - accuracy: 0.6550 - loss: 1.0748
Epoch 6/40
45/45 - 2s - 56ms/step - accuracy: 0.6581 - loss: 1.0399
Epoch 7/40
45/45 - 3s - 59ms/step - accuracy: 0.6600 - loss: 1.0188
Epoch 8/40
45/45 - 3s - 59ms/step - accuracy: 0.6609 - loss: 1.0004
Epoch 9/40
45/45 - 3s - 59ms/step - accuracy: 0.6631 - loss: 0.9857
Epoch 10/40
45/45 - 3s - 58ms/step - accuracy: 0.6627 - loss: 0.9753
Epoch 11/40
45/45 - 2s - 55ms/step - accuracy: 0.6693 - loss: 0.9646
Epoch 12/40
45/45 - 3s - 61ms/step - accuracy: 0.6667 - loss: 0.9553
Epoch 13/40
45/45 - 3s - 58ms/step - accuracy: 0.6728 - loss: 0.9461
Epoch 14/40
45/45 - 3s - 58ms/step - accuracy: 0.6722 - loss: 0.9377
Epoch 15/40
45/45 - 2s - 55ms/step - accuracy: 0.6769 - loss: 0.9311
Epoch 16/40
45/45 - 1s - 32ms/step - accuracy: 0.6763 - loss: 0.9247
Epoch 17/40
45/45 - 2s - 35ms/step - accuracy: 0.6799 - loss: 0.9209
Epoch 18/40
45/45 - 3s - 57ms/step - accuracy: 0.6829 - loss: 0.9134
Epoch 19/40
45/45 - 3s - 58ms/step - accuracy: 0.6837 - loss: 0.9083
Epoch 20/40
45/45 - 3s - 58ms/step - accuracy: 0.6869 - loss: 0.9031
Epoch 21/40
45/45 - 1s - 33ms/step - accuracy: 0.6899 - loss: 0.8964
Epoch 22/40
45/45 - 3s - 59ms/step - accuracy: 0.6925 - loss: 0.8921
Epoch 23/40
45/45 - 3s - 60ms/step - accuracy: 0.6948 - loss: 0.8861
Epoch 24/40
45/45 - 3s - 57ms/step - accuracy: 0.6959 - loss: 0.8816
Epoch 25/40
45/45 - 3s - 56ms/step - accuracy: 0.6979 - loss: 0.8765
Epoch 26/40
45/45 - 1s - 33ms/step - accuracy: 0.7009 - loss: 0.8705
Epoch 27/40
45/45 - 3s - 60ms/step - accuracy: 0.7009 - loss: 0.8673
Epoch 28/40
45/45 - 3s - 61ms/step - accuracy: 0.7062 - loss: 0.8634
Epoch 29/40
45/45 - 2s - 55ms/step - accuracy: 0.7061 - loss: 0.8583
Epoch 30/40
45/45 - 1s - 32ms/step - accuracy: 0.7110 - loss: 0.8514
Epoch 31/40
45/45 - 1s - 31ms/step - accuracy: 0.7112 - loss: 0.8488
Epoch 32/40
45/45 - 3s - 60ms/step - accuracy: 0.7163 - loss: 0.8432
Epoch 33/40
45/45 - 2s - 55ms/step - accuracy: 0.7192 - loss: 0.8371
Epoch 34/40
45/45 - 1s - 33ms/step - accuracy: 0.7155 - loss: 0.8339
Epoch 35/40
45/45 - 1s - 29ms/step - accuracy: 0.7184 - loss: 0.8323
Epoch 36/40
45/45 - 3s - 60ms/step - accuracy: 0.7184 - loss: 0.8286
Epoch 37/40
45/45 - 1s - 33ms/step - accuracy: 0.7216 - loss: 0.8234
Epoch 38/40
45/45 - 3s - 58ms/step - accuracy: 0.7233 - loss: 0.8185
Epoch 39/40
45/45 - 1s - 31ms/step - accuracy: 0.7259 - loss: 0.8158
Epoch 40/40
45/45 - 2s - 34ms/step - accuracy: 0.7270 - loss: 0.8123
12/12 - 1s - 47ms/step
Epoch 1/40

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

45/45 - 4s - 84ms/step - accuracy: 0.4879 - loss: 2.0633
Epoch 2/40
45/45 - 3s - 56ms/step - accuracy: 0.6361 - loss: 1.4557
Epoch 3/40
45/45 - 1s - 31ms/step - accuracy: 0.6373 - loss: 1.2544
Epoch 4/40
45/45 - 3s - 58ms/step - accuracy: 0.6458 - loss: 1.1634
Epoch 5/40
45/45 - 3s - 60ms/step - accuracy: 0.6521 - loss: 1.1121
Epoch 6/40
45/45 - 3s - 60ms/step - accuracy: 0.6580 - loss: 1.0756
Epoch 7/40
45/45 - 3s - 58ms/step - accuracy: 0.6595 - loss: 1.0494
Epoch 8/40
45/45 - 1s - 32ms/step - accuracy: 0.6627 - loss: 1.0294
Epoch 9/40
45/45 - 1s - 30ms/step - accuracy: 0.6660 - loss: 1.0138
Epoch 10/40
45/45 - 3s - 61ms/step - accuracy: 0.6666 - loss: 0.9987
Epoch 11/40
45/45 - 3s - 56ms/step - accuracy: 0.6670 - loss: 0.9892
Epoch 12/40
45/45 - 2s - 47ms/step - accuracy: 0.6701 - loss: 0.9787
Epoch 13/40
45/45 - 1s - 23ms/step - accuracy: 0.6699 - loss: 0.9705
Epoch 14/40
45/45 - 1s - 24ms/step - accuracy: 0.6720 - loss: 0.9636
Epoch 15/40
45/45 - 1s - 32ms/step - accuracy: 0.6750 - loss: 0.9530
Epoch 16/40
45/45 - 3s - 60ms/step - accuracy: 0.6763 - loss: 0.9473
Epoch 17/40
45/45 - 3s - 58ms/step - accuracy: 0.6796 - loss: 0.9397
Epoch 18/40
45/45 - 1s - 30ms/step - accuracy: 0.6763 - loss: 0.9363
Epoch 19/40
45/45 - 2s - 55ms/step - accuracy: 0.6797 - loss: 0.9289
Epoch 20/40
45/45 - 1s - 24ms/step - accuracy: 0.6832 - loss: 0.9243
Epoch 21/40
45/45 - 1s - 29ms/step - accuracy: 0.6847 - loss: 0.9183
Epoch 22/40
45/45 - 1s - 31ms/step - accuracy: 0.6861 - loss: 0.9141
Epoch 23/40
45/45 - 3s - 61ms/step - accuracy: 0.6890 - loss: 0.9091
Epoch 24/40
45/45 - 1s - 29ms/step - accuracy: 0.6873 - loss: 0.9053
Epoch 25/40
45/45 - 1s - 28ms/step - accuracy: 0.6882 - loss: 0.9009
Epoch 26/40
45/45 - 1s - 32ms/step - accuracy: 0.6930 - loss: 0.8959
Epoch 27/40
45/45 - 3s - 58ms/step - accuracy: 0.6899 - loss: 0.8945
Epoch 28/40
45/45 - 1s - 31ms/step - accuracy: 0.6974 - loss: 0.8892
Epoch 29/40
45/45 - 3s - 62ms/step - accuracy: 0.6979 - loss: 0.8845
Epoch 30/40
45/45 - 3s - 57ms/step - accuracy: 0.6978 - loss: 0.8824
Epoch 31/40
45/45 - 3s - 59ms/step - accuracy: 0.6990 - loss: 0.8785
Epoch 32/40
45/45 - 1s - 30ms/step - accuracy: 0.7007 - loss: 0.8735
Epoch 33/40
45/45 - 3s - 61ms/step - accuracy: 0.7023 - loss: 0.8694
Epoch 34/40
45/45 - 1s - 31ms/step - accuracy: 0.7048 - loss: 0.8674
Epoch 35/40
45/45 - 2s - 54ms/step - accuracy: 0.7038 - loss: 0.8637
Epoch 36/40
45/45 - 1s - 32ms/step - accuracy: 0.7074 - loss: 0.8581
Epoch 37/40
45/45 - 3s - 57ms/step - accuracy: 0.7084 - loss: 0.8556
Epoch 38/40
45/45 - 2s - 36ms/step - accuracy: 0.7111 - loss: 0.8521
Epoch 39/40
45/45 - 2s - 54ms/step - accuracy: 0.7094 - loss: 0.8490
Epoch 40/40
45/45 - 3s - 58ms/step - accuracy: 0.7131 - loss: 0.8447
12/12 - 0s - 41ms/step
| 13        | 0.7208    | 3.689     | 308.4     | 0.8164    | 0.1915    | 40.27     | 1.017     | 2.475     | 2.534     | 0.1706    | 96.46     | 0.7979    | 4.089     |
Epoch 1/24

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 3s - 114ms/step - accuracy: 0.4567 - loss: 2.2340
Epoch 2/24
30/30 - 1s - 23ms/step - accuracy: 0.6442 - loss: 1.2702
Epoch 3/24
30/30 - 1s - 20ms/step - accuracy: 0.6449 - loss: 1.1067
Epoch 4/24
30/30 - 1s - 18ms/step - accuracy: 0.6468 - loss: 1.0536
Epoch 5/24
30/30 - 1s - 22ms/step - accuracy: 0.6499 - loss: 1.0259
Epoch 6/24
30/30 - 1s - 18ms/step - accuracy: 0.6529 - loss: 1.0047
Epoch 7/24
30/30 - 0s - 12ms/step - accuracy: 0.6560 - loss: 0.9879
Epoch 8/24
30/30 - 1s - 27ms/step - accuracy: 0.6605 - loss: 0.9713
Epoch 9/24
30/30 - 1s - 25ms/step - accuracy: 0.6635 - loss: 0.9573
Epoch 10/24
30/30 - 1s - 20ms/step - accuracy: 0.6680 - loss: 0.9429
Epoch 11/24
30/30 - 1s - 19ms/step - accuracy: 0.6704 - loss: 0.9302
Epoch 12/24
30/30 - 1s - 21ms/step - accuracy: 0.6775 - loss: 0.9160
Epoch 13/24
30/30 - 1s - 19ms/step - accuracy: 0.6840 - loss: 0.9051
Epoch 14/24
30/30 - 1s - 21ms/step - accuracy: 0.6883 - loss: 0.8951
Epoch 15/24
30/30 - 1s - 20ms/step - accuracy: 0.6927 - loss: 0.8851
Epoch 16/24
30/30 - 1s - 17ms/step - accuracy: 0.6971 - loss: 0.8766
Epoch 17/24
30/30 - 1s - 22ms/step - accuracy: 0.6987 - loss: 0.8691
Epoch 18/24
30/30 - 1s - 22ms/step - accuracy: 0.7039 - loss: 0.8620
Epoch 19/24
30/30 - 1s - 19ms/step - accuracy: 0.7046 - loss: 0.8548
Epoch 20/24
30/30 - 1s - 23ms/step - accuracy: 0.7054 - loss: 0.8483
Epoch 21/24
30/30 - 1s - 21ms/step - accuracy: 0.7075 - loss: 0.8450
Epoch 22/24
30/30 - 1s - 21ms/step - accuracy: 0.7079 - loss: 0.8400
Epoch 23/24
30/30 - 1s - 22ms/step - accuracy: 0.7095 - loss: 0.8330
Epoch 24/24
30/30 - 1s - 24ms/step - accuracy: 0.7129 - loss: 0.8260
8/8 - 0s - 55ms/step
Epoch 1/24

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 65ms/step - accuracy: 0.5376 - loss: 1.9048
Epoch 2/24
30/30 - 0s - 16ms/step - accuracy: 0.6443 - loss: 1.2753
Epoch 3/24
30/30 - 1s - 29ms/step - accuracy: 0.6443 - loss: 1.1130
Epoch 4/24
30/30 - 1s - 22ms/step - accuracy: 0.6444 - loss: 1.0681
Epoch 5/24
30/30 - 1s - 20ms/step - accuracy: 0.6471 - loss: 1.0424
Epoch 6/24
30/30 - 1s - 21ms/step - accuracy: 0.6514 - loss: 1.0243
Epoch 7/24
30/30 - 1s - 21ms/step - accuracy: 0.6570 - loss: 1.0078
Epoch 8/24
30/30 - 1s - 22ms/step - accuracy: 0.6629 - loss: 0.9934
Epoch 9/24
30/30 - 1s - 18ms/step - accuracy: 0.6698 - loss: 0.9795
Epoch 10/24
30/30 - 1s - 26ms/step - accuracy: 0.6754 - loss: 0.9662
Epoch 11/24
30/30 - 1s - 18ms/step - accuracy: 0.6785 - loss: 0.9532
Epoch 12/24
30/30 - 1s - 23ms/step - accuracy: 0.6831 - loss: 0.9391
Epoch 13/24
30/30 - 1s - 21ms/step - accuracy: 0.6869 - loss: 0.9274
Epoch 14/24
30/30 - 1s - 25ms/step - accuracy: 0.6892 - loss: 0.9160
Epoch 15/24
30/30 - 1s - 18ms/step - accuracy: 0.6922 - loss: 0.9006
Epoch 16/24
30/30 - 1s - 22ms/step - accuracy: 0.6940 - loss: 0.8896
Epoch 17/24
30/30 - 1s - 25ms/step - accuracy: 0.6962 - loss: 0.8776
Epoch 18/24
30/30 - 0s - 15ms/step - accuracy: 0.7011 - loss: 0.8681
Epoch 19/24
30/30 - 1s - 27ms/step - accuracy: 0.7061 - loss: 0.8584
Epoch 20/24
30/30 - 1s - 21ms/step - accuracy: 0.7099 - loss: 0.8495
Epoch 21/24
30/30 - 1s - 24ms/step - accuracy: 0.7125 - loss: 0.8410
Epoch 22/24
30/30 - 1s - 24ms/step - accuracy: 0.7134 - loss: 0.8356
Epoch 23/24
30/30 - 1s - 19ms/step - accuracy: 0.7184 - loss: 0.8265
Epoch 24/24
30/30 - 1s - 19ms/step - accuracy: 0.7223 - loss: 0.8223
8/8 - 1s - 64ms/step
Epoch 1/24

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 72ms/step - accuracy: 0.5982 - loss: 2.0076
Epoch 2/24
30/30 - 1s - 22ms/step - accuracy: 0.6442 - loss: 1.3310
Epoch 3/24
30/30 - 0s - 15ms/step - accuracy: 0.6442 - loss: 1.1616
Epoch 4/24
30/30 - 1s - 20ms/step - accuracy: 0.6443 - loss: 1.0839
Epoch 5/24
30/30 - 1s - 23ms/step - accuracy: 0.6450 - loss: 1.0458
Epoch 6/24
30/30 - 1s - 20ms/step - accuracy: 0.6484 - loss: 1.0231
Epoch 7/24
30/30 - 1s - 22ms/step - accuracy: 0.6550 - loss: 1.0048
Epoch 8/24
30/30 - 1s - 20ms/step - accuracy: 0.6621 - loss: 0.9890
Epoch 9/24
30/30 - 1s - 23ms/step - accuracy: 0.6680 - loss: 0.9739
Epoch 10/24
30/30 - 1s - 21ms/step - accuracy: 0.6724 - loss: 0.9583
Epoch 11/24
30/30 - 0s - 16ms/step - accuracy: 0.6802 - loss: 0.9436
Epoch 12/24
30/30 - 0s - 15ms/step - accuracy: 0.6852 - loss: 0.9286
Epoch 13/24
30/30 - 1s - 24ms/step - accuracy: 0.6877 - loss: 0.9142
Epoch 14/24
30/30 - 1s - 25ms/step - accuracy: 0.6925 - loss: 0.8992
Epoch 15/24
30/30 - 1s - 20ms/step - accuracy: 0.6948 - loss: 0.8875
Epoch 16/24
30/30 - 1s - 21ms/step - accuracy: 0.6984 - loss: 0.8765
Epoch 17/24
30/30 - 1s - 25ms/step - accuracy: 0.7012 - loss: 0.8679
Epoch 18/24
30/30 - 1s - 18ms/step - accuracy: 0.7027 - loss: 0.8590
Epoch 19/24
30/30 - 1s - 22ms/step - accuracy: 0.7064 - loss: 0.8530
Epoch 20/24
30/30 - 1s - 24ms/step - accuracy: 0.7097 - loss: 0.8453
Epoch 21/24
30/30 - 1s - 22ms/step - accuracy: 0.7101 - loss: 0.8398
Epoch 22/24
30/30 - 1s - 21ms/step - accuracy: 0.7133 - loss: 0.8339
Epoch 23/24
30/30 - 1s - 25ms/step - accuracy: 0.7140 - loss: 0.8289
Epoch 24/24
30/30 - 1s - 21ms/step - accuracy: 0.7153 - loss: 0.8231
8/8 - 1s - 63ms/step
Epoch 1/24

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 67ms/step - accuracy: 0.5409 - loss: 1.7851
Epoch 2/24
30/30 - 1s - 19ms/step - accuracy: 0.6443 - loss: 1.1951
Epoch 3/24
30/30 - 1s - 22ms/step - accuracy: 0.6481 - loss: 1.0981
Epoch 4/24
30/30 - 1s - 22ms/step - accuracy: 0.6522 - loss: 1.0648
Epoch 5/24
30/30 - 1s - 22ms/step - accuracy: 0.6556 - loss: 1.0419
Epoch 6/24
30/30 - 1s - 26ms/step - accuracy: 0.6580 - loss: 1.0236
Epoch 7/24
30/30 - 1s - 20ms/step - accuracy: 0.6631 - loss: 1.0085
Epoch 8/24
30/30 - 1s - 24ms/step - accuracy: 0.6633 - loss: 0.9942
Epoch 9/24
30/30 - 1s - 17ms/step - accuracy: 0.6656 - loss: 0.9818
Epoch 10/24
30/30 - 1s - 26ms/step - accuracy: 0.6682 - loss: 0.9693
Epoch 11/24
30/30 - 1s - 21ms/step - accuracy: 0.6759 - loss: 0.9570
Epoch 12/24
30/30 - 1s - 19ms/step - accuracy: 0.6816 - loss: 0.9467
Epoch 13/24
30/30 - 1s - 26ms/step - accuracy: 0.6826 - loss: 0.9354
Epoch 14/24
30/30 - 1s - 26ms/step - accuracy: 0.6857 - loss: 0.9246
Epoch 15/24
30/30 - 1s - 36ms/step - accuracy: 0.6882 - loss: 0.9153
Epoch 16/24
30/30 - 1s - 26ms/step - accuracy: 0.6914 - loss: 0.9036
Epoch 17/24
30/30 - 1s - 24ms/step - accuracy: 0.6935 - loss: 0.8945
Epoch 18/24
30/30 - 1s - 18ms/step - accuracy: 0.6976 - loss: 0.8855
Epoch 19/24
30/30 - 0s - 16ms/step - accuracy: 0.7032 - loss: 0.8751
Epoch 20/24
30/30 - 1s - 20ms/step - accuracy: 0.7048 - loss: 0.8682
Epoch 21/24
30/30 - 1s - 21ms/step - accuracy: 0.7085 - loss: 0.8609
Epoch 22/24
30/30 - 1s - 22ms/step - accuracy: 0.7099 - loss: 0.8537
Epoch 23/24
30/30 - 1s - 24ms/step - accuracy: 0.7137 - loss: 0.8457
Epoch 24/24
30/30 - 1s - 21ms/step - accuracy: 0.7126 - loss: 0.8409
8/8 - 1s - 67ms/step

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/24
30/30 - 2s - 63ms/step - accuracy: 0.5157 - loss: 2.0037
Epoch 2/24
30/30 - 1s - 22ms/step - accuracy: 0.6440 - loss: 1.2694
Epoch 3/24
30/30 - 1s - 27ms/step - accuracy: 0.6439 - loss: 1.1539
Epoch 4/24
30/30 - 1s - 22ms/step - accuracy: 0.6441 - loss: 1.1073
Epoch 5/24
30/30 - 1s - 25ms/step - accuracy: 0.6455 - loss: 1.0774
Epoch 6/24
30/30 - 0s - 14ms/step - accuracy: 0.6460 - loss: 1.0543
Epoch 7/24
30/30 - 1s - 28ms/step - accuracy: 0.6471 - loss: 1.0371
Epoch 8/24
30/30 - 1s - 23ms/step - accuracy: 0.6488 - loss: 1.0218
Epoch 9/24
30/30 - 1s - 21ms/step - accuracy: 0.6484 - loss: 1.0097
Epoch 10/24
30/30 - 1s - 22ms/step - accuracy: 0.6521 - loss: 0.9985
Epoch 11/24
30/30 - 1s - 25ms/step - accuracy: 0.6518 - loss: 0.9895
Epoch 12/24
30/30 - 1s - 24ms/step - accuracy: 0.6536 - loss: 0.9786
Epoch 13/24
30/30 - 1s - 20ms/step - accuracy: 0.6557 - loss: 0.9692
Epoch 14/24
30/30 - 1s - 24ms/step - accuracy: 0.6567 - loss: 0.9619
Epoch 15/24
30/30 - 1s - 21ms/step - accuracy: 0.6590 - loss: 0.9546
Epoch 16/24
30/30 - 1s - 20ms/step - accuracy: 0.6610 - loss: 0.9479
Epoch 17/24
30/30 - 0s - 16ms/step - accuracy: 0.6678 - loss: 0.9403
Epoch 18/24
30/30 - 1s - 27ms/step - accuracy: 0.6690 - loss: 0.9341
Epoch 19/24
30/30 - 1s - 21ms/step - accuracy: 0.6739 - loss: 0.9276
Epoch 20/24
30/30 - 1s - 17ms/step - accuracy: 0.6747 - loss: 0.9209
Epoch 21/24
30/30 - 1s - 27ms/step - accuracy: 0.6782 - loss: 0.9154
Epoch 22/24
30/30 - 1s - 25ms/step - accuracy: 0.6814 - loss: 0.9093
Epoch 23/24
30/30 - 1s - 20ms/step - accuracy: 0.6835 - loss: 0.9053
Epoch 24/24
30/30 - 1s - 23ms/step - accuracy: 0.6853 - loss: 0.9001
8/8 - 0s - 55ms/step
| 14        | 0.6961    | 0.3827    | 474.2     | 0.3677    | 0.2657    | 23.75     | 1.397     | 2.915     | 2.037     | 0.5005    | 31.29     | 0.9203    | 0.4407    |
Epoch 1/38

C:\Users\andyc\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

36/36 - 3s - 95ms/step - accuracy: 0.5204 - loss: 1.7769
Epoch 2/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.3593
Epoch 3/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.2661
Epoch 4/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.2293
Epoch 5/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.2101
Epoch 6/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1986
Epoch 7/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1911
Epoch 8/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1857
Epoch 9/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1820
Epoch 10/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1790
Epoch 11/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1769
Epoch 12/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1751
Epoch 13/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1736
Epoch 14/38
36/36 - 1s - 33ms/step - accuracy: 0.6442 - loss: 1.1724
Epoch 15/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1715
Epoch 16/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1706
Epoch 17/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1699
Epoch 18/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.1692
Epoch 19/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.1687
Epoch 20/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1682
Epoch 21/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1678
Epoch 22/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1673
Epoch 23/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1669
Epoch 24/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1666
Epoch 25/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1663
Epoch 26/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1660
Epoch 27/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1658
Epoch 28/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1656
Epoch 29/38
36/36 - 1s - 33ms/step - accuracy: 0.6442 - loss: 1.1653
Epoch 30/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.1651
Epoch 31/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1649
Epoch 32/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1648
Epoch 33/38
36/36 - 1s - 32ms/step - accuracy: 0.6442 - loss: 1.1646
Epoch 34/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1644
Epoch 35/38
36/36 - 1s - 31ms/step - accuracy: 0.6442 - loss: 1.1643
Epoch 36/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1641
Epoch 37/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1641
Epoch 38/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1639
9/9 - 0s - 50ms/step
Epoch 1/38

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

36/36 - 3s - 97ms/step - accuracy: 0.5347 - loss: 1.9609
Epoch 2/38
36/36 - 1s - 24ms/step - accuracy: 0.6443 - loss: 1.4070
Epoch 3/38
36/36 - 1s - 27ms/step - accuracy: 0.6443 - loss: 1.2831
Epoch 4/38
36/36 - 1s - 33ms/step - accuracy: 0.6443 - loss: 1.2393
Epoch 5/38
36/36 - 2s - 43ms/step - accuracy: 0.6443 - loss: 1.2181
Epoch 6/38
36/36 - 1s - 33ms/step - accuracy: 0.6443 - loss: 1.2057
Epoch 7/38
36/36 - 1s - 36ms/step - accuracy: 0.6443 - loss: 1.1975
Epoch 8/38
36/36 - 1s - 41ms/step - accuracy: 0.6443 - loss: 1.1918
Epoch 9/38
36/36 - 1s - 31ms/step - accuracy: 0.6443 - loss: 1.1875
Epoch 10/38
36/36 - 1s - 21ms/step - accuracy: 0.6443 - loss: 1.1841
Epoch 11/38
36/36 - 2s - 44ms/step - accuracy: 0.6443 - loss: 1.1814
Epoch 12/38
36/36 - 1s - 33ms/step - accuracy: 0.6443 - loss: 1.1793
Epoch 13/38
36/36 - 1s - 37ms/step - accuracy: 0.6443 - loss: 1.1775
Epoch 14/38
36/36 - 1s - 26ms/step - accuracy: 0.6443 - loss: 1.1759
Epoch 15/38
36/36 - 1s - 38ms/step - accuracy: 0.6443 - loss: 1.1746
Epoch 16/38
36/36 - 1s - 26ms/step - accuracy: 0.6443 - loss: 1.1734
Epoch 17/38
36/36 - 1s - 40ms/step - accuracy: 0.6443 - loss: 1.1725
Epoch 18/38
36/36 - 1s - 37ms/step - accuracy: 0.6443 - loss: 1.1716
Epoch 19/38
36/36 - 1s - 35ms/step - accuracy: 0.6443 - loss: 1.1708
Epoch 20/38
36/36 - 1s - 37ms/step - accuracy: 0.6443 - loss: 1.1701
Epoch 21/38
36/36 - 1s - 39ms/step - accuracy: 0.6443 - loss: 1.1695
Epoch 22/38
36/36 - 1s - 36ms/step - accuracy: 0.6443 - loss: 1.1690
Epoch 23/38
36/36 - 1s - 34ms/step - accuracy: 0.6443 - loss: 1.1684
Epoch 24/38
36/36 - 2s - 42ms/step - accuracy: 0.6443 - loss: 1.1680
Epoch 25/38
36/36 - 1s - 36ms/step - accuracy: 0.6443 - loss: 1.1676
Epoch 26/38
36/36 - 1s - 26ms/step - accuracy: 0.6443 - loss: 1.1672
Epoch 27/38
36/36 - 1s - 39ms/step - accuracy: 0.6443 - loss: 1.1669
Epoch 28/38
36/36 - 1s - 28ms/step - accuracy: 0.6443 - loss: 1.1666
Epoch 29/38
36/36 - 1s - 27ms/step - accuracy: 0.6443 - loss: 1.1663
Epoch 30/38
36/36 - 1s - 38ms/step - accuracy: 0.6443 - loss: 1.1660
Epoch 31/38
36/36 - 1s - 26ms/step - accuracy: 0.6443 - loss: 1.1657
Epoch 32/38
36/36 - 1s - 39ms/step - accuracy: 0.6443 - loss: 1.1655
Epoch 33/38
36/36 - 1s - 38ms/step - accuracy: 0.6443 - loss: 1.1653
Epoch 34/38
36/36 - 1s - 36ms/step - accuracy: 0.6443 - loss: 1.1651
Epoch 35/38
36/36 - 1s - 25ms/step - accuracy: 0.6443 - loss: 1.1649
Epoch 36/38
36/36 - 1s - 27ms/step - accuracy: 0.6443 - loss: 1.1647
Epoch 37/38
36/36 - 1s - 38ms/step - accuracy: 0.6443 - loss: 1.1646
Epoch 38/38
36/36 - 1s - 38ms/step - accuracy: 0.6443 - loss: 1.1644
9/9 - 0s - 55ms/step
Epoch 1/38

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

36/36 - 5s - 138ms/step - accuracy: 0.5776 - loss: 1.9895
Epoch 2/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.4387
Epoch 3/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.3043
Epoch 4/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.2506
Epoch 5/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.2241
Epoch 6/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.2089
Epoch 7/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1992
Epoch 8/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1926
Epoch 9/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1878
Epoch 10/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1842
Epoch 11/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1815
Epoch 12/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1792
Epoch 13/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1774
Epoch 14/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1759
Epoch 15/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1746
Epoch 16/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1735
Epoch 17/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1726
Epoch 18/38
36/36 - 1s - 22ms/step - accuracy: 0.6442 - loss: 1.1717
Epoch 19/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1710
Epoch 20/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1704
Epoch 21/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1698
Epoch 22/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1693
Epoch 23/38
36/36 - 1s - 31ms/step - accuracy: 0.6442 - loss: 1.1688
Epoch 24/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1684
Epoch 25/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1679
Epoch 26/38
36/36 - 1s - 31ms/step - accuracy: 0.6442 - loss: 1.1676
Epoch 27/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1673
Epoch 28/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1670
Epoch 29/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1667
Epoch 30/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1664
Epoch 31/38
36/36 - 1s - 25ms/step - accuracy: 0.6442 - loss: 1.1662
Epoch 32/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1660
Epoch 33/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.1657
Epoch 34/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1656
Epoch 35/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1654
Epoch 36/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1652
Epoch 37/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1651
Epoch 38/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1649
9/9 - 0s - 45ms/step
Epoch 1/38

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

36/36 - 3s - 79ms/step - accuracy: 0.5026 - loss: 1.9769
Epoch 2/38
36/36 - 1s - 23ms/step - accuracy: 0.6442 - loss: 1.4342
Epoch 3/38
36/36 - 1s - 19ms/step - accuracy: 0.6442 - loss: 1.3037
Epoch 4/38
36/36 - 1s - 22ms/step - accuracy: 0.6442 - loss: 1.2536
Epoch 5/38
36/36 - 2s - 43ms/step - accuracy: 0.6442 - loss: 1.2282
Epoch 6/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.2132
Epoch 7/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.2034
Epoch 8/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1965
Epoch 9/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1914
Epoch 10/38
36/36 - 1s - 26ms/step - accuracy: 0.6442 - loss: 1.1875
Epoch 11/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1845
Epoch 12/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1821
Epoch 13/38
36/36 - 2s - 42ms/step - accuracy: 0.6442 - loss: 1.1801
Epoch 14/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1784
Epoch 15/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1769
Epoch 16/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1757
Epoch 17/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1746
Epoch 18/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1737
Epoch 19/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1728
Epoch 20/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1721
Epoch 21/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1714
Epoch 22/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1708
Epoch 23/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1703
Epoch 24/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1698
Epoch 25/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1693
Epoch 26/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1689
Epoch 27/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1685
Epoch 28/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1682
Epoch 29/38
36/36 - 1s - 31ms/step - accuracy: 0.6442 - loss: 1.1679
Epoch 30/38
36/36 - 2s - 46ms/step - accuracy: 0.6442 - loss: 1.1675
Epoch 31/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1673
Epoch 32/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1670
Epoch 33/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1668
Epoch 34/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1666
Epoch 35/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1663
Epoch 36/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1661
Epoch 37/38
36/36 - 1s - 27ms/step - accuracy: 0.6442 - loss: 1.1659
Epoch 38/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1658
9/9 - 1s - 62ms/step
Epoch 1/38

C:\Users\andyc\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

36/36 - 3s - 87ms/step - accuracy: 0.3012 - loss: 2.1699
Epoch 2/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.4903
Epoch 3/38
36/36 - 1s - 25ms/step - accuracy: 0.6442 - loss: 1.3143
Epoch 4/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.2538
Epoch 5/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.2260
Epoch 6/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.2104
Epoch 7/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.2006
Epoch 8/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1939
Epoch 9/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1890
Epoch 10/38
36/36 - 1s - 33ms/step - accuracy: 0.6442 - loss: 1.1853
Epoch 11/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.1824
Epoch 12/38
36/36 - 1s - 31ms/step - accuracy: 0.6442 - loss: 1.1801
Epoch 13/38
36/36 - 2s - 44ms/step - accuracy: 0.6442 - loss: 1.1781
Epoch 14/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1765
Epoch 15/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1752
Epoch 16/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1740
Epoch 17/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1730
Epoch 18/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1721
Epoch 19/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1712
Epoch 20/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1706
Epoch 21/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1700
Epoch 22/38
36/36 - 1s - 41ms/step - accuracy: 0.6442 - loss: 1.1694
Epoch 23/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1689
Epoch 24/38
36/36 - 1s - 37ms/step - accuracy: 0.6442 - loss: 1.1685
Epoch 25/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1680
Epoch 26/38
36/36 - 1s - 32ms/step - accuracy: 0.6442 - loss: 1.1676
Epoch 27/38
36/36 - 1s - 39ms/step - accuracy: 0.6442 - loss: 1.1674
Epoch 28/38
36/36 - 1s - 36ms/step - accuracy: 0.6442 - loss: 1.1670
Epoch 29/38
36/36 - 1s - 30ms/step - accuracy: 0.6442 - loss: 1.1667
Epoch 30/38
36/36 - 1s - 29ms/step - accuracy: 0.6442 - loss: 1.1664
Epoch 31/38
36/36 - 1s - 34ms/step - accuracy: 0.6442 - loss: 1.1662
Epoch 32/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1660
Epoch 33/38
36/36 - 1s - 28ms/step - accuracy: 0.6442 - loss: 1.1658
Epoch 34/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1656
Epoch 35/38
36/36 - 1s - 38ms/step - accuracy: 0.6442 - loss: 1.1654
Epoch 36/38
36/36 - 1s - 26ms/step - accuracy: 0.6442 - loss: 1.1652
Epoch 37/38
36/36 - 1s - 40ms/step - accuracy: 0.6442 - loss: 1.1650
Epoch 38/38
36/36 - 1s - 35ms/step - accuracy: 0.6442 - loss: 1.1649
9/9 - 1s - 63ms/step
| 15        | 0.6442    | 1.27      | 383.8     | 0.07658   | 0.2589    | 37.63     | 2.789     | 1.995     | 2.559     | 0.1361    | 65.05     | 0.9107    | 3.561     |

ValueError: Input y contains NaN.

In [62]:
optimum = nn_opt.max['params']
learning_rate = optimum['learning_rate']

activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu', 'elu', 'exponential', LeakyReLU, 'relu']
optimum['activation'] = activationL[round(optimum['activation'])]

optimum['batch_size'] = round(optimum['batch_size'])
optimum['epochs'] = round(optimum['epochs'])
optimum['layers1'] = round(optimum['layers1'])
optimum['layers2'] = round(optimum['layers2'])
optimum['neurons'] = round(optimum['neurons'])

optimizerL = ['Adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl', 'Adam']
optimizerD = {
    'Adam': Adam(learning_rate=learning_rate),
    'SGD': SGD(learning_rate=learning_rate),
    'RMSprop': RMSprop(learning_rate=learning_rate),
    'Adadelta': Adadelta(learning_rate=learning_rate),
    'Adagrad': Adagrad(learning_rate=learning_rate),
    'Adamax': Adamax(learning_rate=learning_rate),
    'Nadam': Nadam(learning_rate=learning_rate),
    'Ftrl': Ftrl(learning_rate=learning_rate)
}
optimum['optimizer'] = optimizerD[optimizerL[round(optimum['optimizer'])]]
optimum

{'activation': 'selu',
 'batch_size': 929,
 'dropout': 0.5063915685439514,
 'dropout_rate': 0.131589960443724,
 'epochs': 21,
 'kernel': 1.4568184424104407,
 'layers1': 1,
 'layers2': 1,
 'learning_rate': 0.8113610465649194,
 'neurons': 57,
 'normalization': 0.36861752031667094,
 'optimizer': <keras.src.optimizers.adadelta.Adadelta at 0x18f2a2ccb30>}

# 6. Running CNN with New Parameters

In [65]:
# Setting the model with optimized hyperparameters

epochs = 47
batch_size = 460

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15

layers1 = 1
layers2 = 2
activation = 'softsign'
kernel = int(round(1.9444298503238986))  # Rounded kernel size for Conv1D
neurons = 61
normalization = 0.770967179954561
dropout = 0.7296061783380641
dropout_rate = 0.19126724140656393
optimizer = Adadelta(learning_rate=0.7631771981307285)  # Instantiate RMSprop with learning rate

model = Sequential()
model.add(Conv1D(neurons, kernel_size=kernel, activation=activation, input_shape=(timesteps, input_dim)))

if normalization > 0.5:
    model.add(BatchNormalization())

for i in range(layers1):
    model.add(Dense(neurons, activation=activation))

if dropout > 0.5:
    model.add(Dropout(dropout_rate))

for i in range(layers2):
    model.add(Dense(neurons, activation=activation))

model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) 

model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
model.summary()

Model: "sequential_75"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_75 (Conv1D)                   │ (None, 14, 61)              │           1,159 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_35               │ (None, 14, 61)              │             244 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_410 (Dense)                    │ (None, 14, 61)              │           3,782 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_35 (Dropout)                 │ (None, 14, 61)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_411 (Dense)                    │ (None, 14, 61)              │           3,782 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_412 (Dense)                    │ (None, 14, 61)              │           3,782 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_75 (MaxPooling1D)      │ (None, 7, 61)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_75 (Flatten)                 │ (None, 427)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_413 (Dense)                    │ (None, 15)                  │           6,420 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,169 (74.88 KB)

 Trainable params: 19,047 (74.40 KB)

 Non-trainable params: 122 (488.00 B)

In [69]:
# Putting the y_test set back into a one-hot configuration

y_train_one_hot = to_categorical(y_train, num_classes=15)

In [71]:
# Checking both shapes

print(f'X_train shape: {X_train.shape}')
print(f'y_train_one_hot shape: {y_train_one_hot.shape}')

X_train shape: (17212, 15, 9)
y_train_one_hot shape: (17212, 15)

In [73]:
# Compiling the model with categorical_crossentropy

model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [75]:
# Fitting the model to the data

model.fit(X_train, y_train_one_hot, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/47
38/38 - 4s - 97ms/step - accuracy: 0.6014 - loss: 1.3535
Epoch 2/47
38/38 - 1s - 38ms/step - accuracy: 0.6831 - loss: 0.9219
Epoch 3/47
38/38 - 1s - 33ms/step - accuracy: 0.7143 - loss: 0.8309
Epoch 4/47
38/38 - 1s - 36ms/step - accuracy: 0.7344 - loss: 0.7754
Epoch 5/47
38/38 - 1s - 33ms/step - accuracy: 0.7511 - loss: 0.7324
Epoch 6/47
38/38 - 1s - 34ms/step - accuracy: 0.7588 - loss: 0.6976
Epoch 7/47
38/38 - 1s - 36ms/step - accuracy: 0.7703 - loss: 0.6661
Epoch 8/47
38/38 - 1s - 31ms/step - accuracy: 0.7831 - loss: 0.6397
Epoch 9/47
38/38 - 1s - 23ms/step - accuracy: 0.7914 - loss: 0.6089
Epoch 10/47
38/38 - 1s - 19ms/step - accuracy: 0.7979 - loss: 0.5843
Epoch 11/47
38/38 - 1s - 35ms/step - accuracy: 0.8059 - loss: 0.5602
Epoch 12/47
38/38 - 1s - 24ms/step - accuracy: 0.8126 - loss: 0.5428
Epoch 13/47
38/38 - 1s - 22ms/step - accuracy: 0.8193 - loss: 0.5159
Epoch 14/47
38/38 - 1s - 22ms/step - accuracy: 0.8264 - loss: 0.5011
Epoch 15/47
38/38 - 1s - 34ms/step - accuracy: 0.8313 - loss: 0.4833
Epoch 16/47
38/38 - 1s - 30ms/step - accuracy: 0.8384 - loss: 0.4679
Epoch 17/47
38/38 - 1s - 20ms/step - accuracy: 0.8401 - loss: 0.4549
Epoch 18/47
38/38 - 1s - 34ms/step - accuracy: 0.8475 - loss: 0.4410
Epoch 19/47
38/38 - 1s - 24ms/step - accuracy: 0.8538 - loss: 0.4273
Epoch 20/47
38/38 - 1s - 22ms/step - accuracy: 0.8538 - loss: 0.4137
Epoch 21/47
38/38 - 1s - 19ms/step - accuracy: 0.8546 - loss: 0.4175
Epoch 22/47
38/38 - 1s - 25ms/step - accuracy: 0.8634 - loss: 0.3915
Epoch 23/47
38/38 - 1s - 21ms/step - accuracy: 0.8668 - loss: 0.3839
Epoch 24/47
38/38 - 1s - 22ms/step - accuracy: 0.8714 - loss: 0.3719
Epoch 25/47
38/38 - 1s - 18ms/step - accuracy: 0.8765 - loss: 0.3594
Epoch 26/47
38/38 - 1s - 21ms/step - accuracy: 0.8764 - loss: 0.3557
Epoch 27/47
38/38 - 1s - 17ms/step - accuracy: 0.8807 - loss: 0.3482
Epoch 28/47
38/38 - 1s - 24ms/step - accuracy: 0.8847 - loss: 0.3378
Epoch 29/47
38/38 - 1s - 30ms/step - accuracy: 0.8871 - loss: 0.3230
Epoch 30/47
38/38 - 2s - 42ms/step - accuracy: 0.8882 - loss: 0.3222
Epoch 31/47
38/38 - 1s - 34ms/step - accuracy: 0.8949 - loss: 0.3086
Epoch 32/47
38/38 - 1s - 33ms/step - accuracy: 0.8917 - loss: 0.3112
Epoch 33/47
38/38 - 1s - 20ms/step - accuracy: 0.8952 - loss: 0.3018
Epoch 34/47
38/38 - 2s - 40ms/step - accuracy: 0.9025 - loss: 0.2846
Epoch 35/47
38/38 - 1s - 37ms/step - accuracy: 0.9029 - loss: 0.2822
Epoch 36/47
38/38 - 1s - 28ms/step - accuracy: 0.9081 - loss: 0.2736
Epoch 37/47
38/38 - 1s - 38ms/step - accuracy: 0.9054 - loss: 0.2709
Epoch 38/47
38/38 - 1s - 37ms/step - accuracy: 0.9054 - loss: 0.2750
Epoch 39/47
38/38 - 1s - 32ms/step - accuracy: 0.9117 - loss: 0.2560
Epoch 40/47
38/38 - 1s - 34ms/step - accuracy: 0.9122 - loss: 0.2588
Epoch 41/47
38/38 - 1s - 24ms/step - accuracy: 0.9141 - loss: 0.2490
Epoch 42/47
38/38 - 1s - 21ms/step - accuracy: 0.9181 - loss: 0.2418
Epoch 43/47
38/38 - 1s - 15ms/step - accuracy: 0.9180 - loss: 0.2394
Epoch 44/47
38/38 - 1s - 17ms/step - accuracy: 0.9196 - loss: 0.2362
Epoch 45/47
38/38 - 1s - 25ms/step - accuracy: 0.9213 - loss: 0.2276
Epoch 46/47
38/38 - 1s - 24ms/step - accuracy: 0.9196 - loss: 0.2335
Epoch 47/47
38/38 - 1s - 38ms/step - accuracy: 0.9240 - loss: 0.2204

# 7. Creating the Confusion Matrix

In [78]:
# Defining the list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'
}

In [80]:
def confusion_matrix(y_true, y_pred, stations):
    # Check if y_true and y_pred are one-hot encoded or already class indices
    if y_true.ndim == 1:
        y_true_labels = y_true
    else:
        y_true_labels = np.argmax(y_true, axis=1)
    
    if y_pred.ndim == 1:
        y_pred_labels = y_pred
    else:
        y_pred_labels = np.argmax(y_pred, axis=1)
        
    # Map numeric labels to activity names
    y_true_series = pd.Series([stations[y] for y in y_true_labels])
    y_pred_series = pd.Series([stations[y] for y in y_pred_labels])
    
    return pd.crosstab(y_true_series, y_pred_series, rownames=['True'], colnames=['Pred'])

In [82]:
y_pred = model.predict(X_test)

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

In [84]:
# Evaluate

print(confusion_matrix(y_test, y_pred, stations))

Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL        3522        67        12       5           2         2       0
BELGRADE      116       993         1       1           0         0       0
BUDAPEST       25        36       134       1           0         0       0
DEBILT          7         8         8      59           1         0       0
DUSSELDORF      5         1         3      16           8         5       0
HEATHROW       16         5         2       3           4        61       0
KASSEL          1         6         3       0           1         0       3
LJUBLJANA       7         5         2       1           0         2       2
MAASTRICHT      3         0         0       0           0         0       0
MADRID         13        19        12       2           1        22       0
MUNCHENB        6         1         0       0           0         0       1
OSLO            0         0         0       1           0         0       0
STOCKHOLM       1         0         0       0           0         2       0
VALENTIA        1         0         0       0           0         1       0

Pred        LJUBLJANA  MAASTRICHT  MADRID  OSLO  STOCKHOLM
True
BASEL               3           1      64     0          0
BELGRADE            0           0       0     0          0
BUDAPEST            0           0       1     0          0
DEBILT              0           0       0     0          0
DUSSELDORF          0           0       0     0          0
HEATHROW            0           0       0     0          0
KASSEL              2           0       0     0          0
LJUBLJANA          30           0       0     0          0
MAASTRICHT          0           0       2     0          0
MADRID              7           0     375     0          0
MUNCHENB            0           0       1     0          0
OSLO                1           0       1     1          0
STOCKHOLM           0           0       0     0          1
VALENTIA            0           0       0     0          0