### 1. Importing libraries and data
### 2. Data Cleaning
### 3. Reshaping the data
### 4. Splitting the data
### 5. Creating the Keras Model
### 6. Compiling and running the RNN Model
### 7. Creating the Confusion Matrix
### 8. Adjusting hyperparamters for the RNN Model
### 9. Creating the Confusion Matrix
### 10. Compiling and running the CNN Model
### 11. Creating the Confusion Matrix
### 11. Adjusting hyperparamters for the CNN Model
### 13. Creating the Confusion Matrix

# 1. Importing libraries and data

In [151]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout, LSTM
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [152]:
# Identifying a path to where data is stored
path = 'C:/Users/andyc/Machine Learning - ClimateWins'

In [153]:
# Importing the unscaled Climatewins data set
unscaled = pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-weather-prediction-dataset-processed.csv'), index_col = False)

In [154]:
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [155]:
unscaled.shape

(22950, 170)

In [156]:
# Importing the pleasant_weather data set
pw_pred = pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_weather.csv'), index_col = False)

In [157]:
pw_pred.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# 2. Data Cleaning

In [159]:
# Dropping the date and month columns from the unscaled dataframe

unscaled = unscaled.drop(columns=['DATE', 'MONTH'], axis=1)

In [160]:
unscaled.head()

,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [161]:
# Dropping the date column from the pw_pred dataframe

pw_pred = pw_pred.drop(columns=['DATE'], axis=1)

In [162]:
pw_pred.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [163]:
# Dropping 'Gdansk', 'Roma', and 'Tours' columns from the unscaled dataframe

drop_cols = [col for col in unscaled.columns if col.startswith(('GDANSK', 'ROMA', 'TOURS'))]
unscaled = unscaled.drop(columns=drop_cols)

In [164]:
# Dropping columns for 'wind_speed' and 'snow_depth'

drop_cols = [col for col in unscaled.columns if col.endswith(('wind_speed', 'snow_depth'))]

unscaled = unscaled.drop(columns=drop_cols)

In [165]:
unscaled.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [166]:
# Finding all the different measurement types for each weather station

# Extracting station names 
stations = set([col.split('_')[0] for col in unscaled.columns])

# Creating a dictionary to store measurement counts for each station
measurement_counts = {location: {} for location in stations}

# Counting occurrences of each measurement type for each station
for col in unscaled.columns:
    parts = col.split('_') 
    location = parts[0] 
    measurement = '_'.join(parts[1:])

    if measurement not in measurement_counts[location]:
        measurement_counts[location][measurement] = 1
    else:
        measurement_counts[location][measurement] += 1

# Printing the measurement counts for each station
for location, measurements in measurement_counts.items():
    print(f"Location: {location}")
    for measurement, count in measurements.items():
        print(f"  - {measurement}: {count}")
    print()

Location: STOCKHOLM
  - cloud_cover: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: DUSSELDORF
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: LJUBLJANA
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MADRID
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MUNCHENB
  - cloud_cover: 1
  - humidity: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: OSLO
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: VALENTIA
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: SONNBLICK
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: KASSEL
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: BASEL
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: DEBILT
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: BUDAPEST
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: BELGRADE
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: HEATHROW
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MAASTRICHT
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

In [167]:
# There is missing data for Kassel's cloud cover, Stockholm's humidity, and Munchenb's pressure

# Defining relationships between stations
# Using similar stations to fill in missing data
location_pairs = {
    'KASSEL': 'LJUBLJANA',
    'STOCKHOLM': 'OSLO',
    'MUNCHENB': 'SONNBLICK'
}

# Defining the desired order of measurements
measurement_order = ['cloud_cover', 'humidity', 'pressure', 'global_radiation', 
                     'precipitation', 'sunshine', 'temp_mean', 'temp_min', 'temp_max']

# Function to fill in missing values and inserting it in the proper position
def fill_missing_values(unscaled, location, measurement, neighbor):
    """
    Fills missing values for a given location and measurement using data from a neighbor location.
    Inserts the new column in the correct position based on the measurement order.

    Args:
        df_unscaled: The DataFrame containing the weather data.
        location: The location with missing values.
        measurement: The measurement with missing values.
        neighbor: The neighboring location to use for filling.

    Returns:
        The updated DataFrame with filled missing values and columns in the correct order.
    """
    source_col = f'{neighbor}_{measurement}'
    target_col = f'{location}_{measurement}'

    # Determining the insertion index 
    if measurement == measurement_order[0]:
        location_columns = [col for col in unscaled.columns if col.startswith(location)]
        if location_columns:
            insert_index = unscaled.columns.get_loc(location_columns[0]) 
        else:
            insert_index = 0
    else:
        insert_index = unscaled.columns.get_loc(f'{location}_{measurement_order[measurement_order.index(measurement) - 1]}') + 1 

    # Creating the new column with missing values and inserting it in the proper position
    unscaled.insert(insert_index, target_col, np.nan) 

    # Filling in the missing values in the new column
    unscaled[target_col].fillna(unscaled[source_col], inplace=True) 

    return unscaled

# Filling in the missing values for each location and measurement
for location, neighbor in location_pairs.items():
    for measurement in measurement_order:
        if f'{location}_{measurement}' not in unscaled.columns:
            unscaled = fill_missing_values(unscaled, location, measurement, neighbor)

# Checking the new columns for existence and location
added_columns = [col for col in unscaled.columns if col.startswith(('KASSEL', 'STOCKHOLM', 'MUNCHENB'))]
print(unscaled[added_columns])

       KASSEL_cloud_cover  KASSEL_humidity  KASSEL_pressure  \
0                     8.0             0.82           1.0094
1                     6.0             0.86           1.0086
2                     8.0             0.91           1.0129
3                     6.0             0.87           1.0290
4                     7.0             0.86           1.0262
...                   ...              ...              ...
22945                 4.0             0.77           1.0161
22946                 3.0             0.77           1.0161
22947                 3.0             0.77           1.0161
22948                 3.0             0.77           1.0161
22949                 3.0             0.77           1.0161

       KASSEL_global_radiation  KASSEL_precipitation  KASSEL_sunshine  \
0                         0.28                  0.48              1.6
1                         0.12                  0.27              0.0
2                         0.12                  0.60              0.0
3                         0.12                  0.00              0.0
4                         0.13                  0.71              0.0
...                        ...                   ...              ...
22945                     1.14                  0.19              4.0
22946                     1.14                  0.19              4.0
22947                     1.14                  0.19              4.0
22948                     1.14                  0.19              4.0
22949                     1.14                  0.19              4.0

       KASSEL_temp_mean  KASSEL_temp_min  KASSEL_temp_max  \
0                   7.9              3.9              9.4
1                   7.7              6.8              9.1
2                   6.5              6.0              8.0
3                   5.8              5.2              6.5
4                   5.4              3.7              6.0
...                 ...              ...              ...
22945               9.1              5.4             13.1
22946               9.1              5.4             13.1
22947               9.1              5.4             13.1
22948               9.1              5.4             13.1
22949               9.1              5.4             13.1

       MUNCHENB_cloud_cover  ...  MUNCHENB_temp_max  STOCKHOLM_cloud_cover  \
0                         5  ...               10.4                      5
1                         6  ...               10.2                      5
2                         6  ...                8.0                      5
3                         6  ...                5.4                      5
4                         5  ...                6.0                      5
...                     ...  ...                ...                    ...
22945                     2  ...               22.2                      5
22946                     6  ...               26.1                      5
22947                     7  ...               26.2                      5
22948                     6  ...               23.5                      5
22949                     5  ...               19.6                      5

       STOCKHOLM_humidity  STOCKHOLM_pressure  STOCKHOLM_global_radiation  \
0                    0.98              1.0114                        0.05
1                    0.62              1.0114                        0.05
2                    0.69              1.0114                        0.05
3                    0.98              1.0114                        0.05
4                    0.96              1.0114                        0.05
...                   ...                 ...                         ...
22945                0.98              1.0161                        1.11
22946                1.00              1.0122                        1.11
22947                0.85              1.0059                        1.11
22948                0.94              1.0160                        1.11
22949                0.97              1.0164                        1.11

       STOCKHOLM_precipitation  STOCKHOLM_sunshine  STOCKHOLM_temp_mean  \
0                         0.32                 0.0                  4.2
1                         0.06                 0.0                  4.0
2                         0.02                 0.0                  2.4
3                         0.00                 0.0                  1.2
4                         1.32                 0.0                  3.3
...                        ...                 ...                  ...
22945                     0.14                 3.2                 11.5
22946                     0.14                 0.8                 12.5
22947                     0.14                 6.9                 13.1
22948                     0.14                 8.4                  7.5
22949                     0.14                 0.4                  9.7

       STOCKHOLM_temp_min  STOCKHOLM_temp_max
0                     2.2                 4.9
1                     3.0                 5.0
2                     1.3                 4.1
3                     0.4                 2.3
4                     0.8                 4.3
...                   ...                 ...
22945                 8.2                14.2
22946                11.0                14.3
22947                12.1                14.4
22948                 5.1                12.4
22949                 5.0                12.6

[22950 rows x 27 columns]

C:\Users\andyc\AppData\Local\Temp\ipykernel_47340\4151646558.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unscaled[target_col].fillna(unscaled[source_col], inplace=True)
C:\Users\andyc\AppData\Local\Temp\ipykernel_47340\4151646558.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unscaled[target_col].fillna(unscaled[source_col], inplace=True)
C:\Users\andyc\AppData\Local\Temp\ipykernel_47340\4151646558.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unscaled[target_col].fillna(unscaled[source_col], inplace=True)

In [168]:
unscaled.columns

Index(['BASEL_cloud_cover', 'BASEL_humidity', 'BASEL_pressure',
       'BASEL_global_radiation', 'BASEL_precipitation', 'BASEL_sunshine',
       'BASEL_temp_mean', 'BASEL_temp_min', 'BASEL_temp_max',
       'BELGRADE_cloud_cover',
       ...
       'STOCKHOLM_temp_max', 'VALENTIA_cloud_cover', 'VALENTIA_humidity',
       'VALENTIA_pressure', 'VALENTIA_global_radiation',
       'VALENTIA_precipitation', 'VALENTIA_sunshine', 'VALENTIA_temp_mean',
       'VALENTIA_temp_min', 'VALENTIA_temp_max'],
      dtype='object', length=135)

In [169]:
# Exporting the cleaned unscaled weather data
unscaled.to_csv(os.path.join(path, 'cleaned_weather.csv'), index=False)

# 3. Reshaping the data

In [171]:
X = unscaled
y = pw_pred

In [172]:
X.shape

(22950, 135)

In [173]:
y.shape

(22950, 15)

In [174]:
# Turning X and y from dataframes to arrays

X = np.array(X)
y = np.array(y)

In [175]:
X.shape

(22950, 135)

In [176]:
X = X.reshape(-1,15,9)

In [177]:
X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   0.98  ,   1.0114, ...,   4.2   ,   2.2   ,
           4.9   ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   0.62  ,   1.0114, ...,   4.    ,   3.    ,
           5.    ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   0.69  ,   1.0114, ...,   2.4   ,   1.3   ,
           4.1   ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   0.85  ,   1.0059, ...,  13.1   ,  12.1   ,
          14.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   0.94  ,   1.016 , ...,   7.5   ,   5.1   ,
          12.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   0.97  ,   1.0164, ...,   9.7   ,   5.    ,
          12.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

In [178]:
X.shape

(22950, 15, 9)

In [179]:
y.shape

(22950, 15)

# 4. Splitting the data

In [181]:
# Splitting the data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 28)

In [182]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

# 5. Creating the Keras Model

In [184]:
epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [185]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                        │ (None, 32)                  │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 15)                  │             495 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,871 (22.93 KB)

 Trainable params: 5,871 (22.93 KB)

 Non-trainable params: 0 (0.00 B)

# 6. Compiling and Running the RNN Model

In [187]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [188]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=2)

Epoch 1/30
1076/1076 - 7s - 7ms/step - accuracy: 0.1827 - loss: 9.9514
Epoch 2/30
1076/1076 - 5s - 5ms/step - accuracy: 0.2927 - loss: 10.2110
Epoch 3/30
1076/1076 - 4s - 4ms/step - accuracy: 0.3015 - loss: 10.5157
Epoch 4/30
1076/1076 - 5s - 5ms/step - accuracy: 0.4551 - loss: 10.7810
Epoch 5/30
1076/1076 - 4s - 4ms/step - accuracy: 0.5892 - loss: 11.0610
Epoch 6/30
1076/1076 - 6s - 6ms/step - accuracy: 0.6336 - loss: 11.3942
Epoch 7/30
1076/1076 - 10s - 10ms/step - accuracy: 0.6405 - loss: 11.7811
Epoch 8/30
1076/1076 - 11s - 11ms/step - accuracy: 0.6437 - loss: 12.0621
Epoch 9/30
1076/1076 - 10s - 9ms/step - accuracy: 0.6439 - loss: 12.3585
Epoch 10/30
1076/1076 - 10s - 9ms/step - accuracy: 0.6441 - loss: 12.7205
Epoch 11/30
1076/1076 - 10s - 9ms/step - accuracy: 0.6432 - loss: 13.1453
Epoch 12/30
1076/1076 - 9s - 8ms/step - accuracy: 0.6436 - loss: 13.4148
Epoch 13/30
1076/1076 - 4s - 4ms/step - accuracy: 0.6440 - loss: 13.6584
Epoch 14/30
1076/1076 - 6s - 6ms/step - accuracy: 0.6443 - loss: 14.0864
Epoch 15/30
1076/1076 - 11s - 10ms/step - accuracy: 0.6439 - loss: 14.4280
Epoch 16/30
1076/1076 - 9s - 9ms/step - accuracy: 0.6441 - loss: 14.7847
Epoch 17/30
1076/1076 - 6s - 5ms/step - accuracy: 0.6439 - loss: 15.2107
Epoch 18/30
1076/1076 - 10s - 10ms/step - accuracy: 0.6441 - loss: 15.5583
Epoch 19/30
1076/1076 - 10s - 10ms/step - accuracy: 0.6438 - loss: 15.8191
Epoch 20/30
1076/1076 - 4s - 4ms/step - accuracy: 0.6439 - loss: 16.2489
Epoch 21/30
1076/1076 - 5s - 5ms/step - accuracy: 0.6444 - loss: 16.6586
Epoch 22/30
1076/1076 - 6s - 5ms/step - accuracy: 0.6441 - loss: 17.1330
Epoch 23/30
1076/1076 - 10s - 10ms/step - accuracy: 0.6441 - loss: 17.3877
Epoch 24/30
1076/1076 - 6s - 5ms/step - accuracy: 0.6440 - loss: 17.7941
Epoch 25/30
1076/1076 - 10s - 10ms/step - accuracy: 0.6441 - loss: 18.4727
Epoch 26/30
1076/1076 - 11s - 10ms/step - accuracy: 0.6441 - loss: 18.7565
Epoch 27/30
1076/1076 - 10s - 9ms/step - accuracy: 0.6441 - loss: 18.9718
Epoch 28/30
1076/1076 - 4s - 4ms/step - accuracy: 0.6444 - loss: 19.6177
Epoch 29/30
1076/1076 - 5s - 5ms/step - accuracy: 0.6441 - loss: 19.7862
Epoch 30/30
1076/1076 - 11s - 10ms/step - accuracy: 0.6442 - loss: 20.2362

# 7. Creating the Confusion Matrix

In [190]:
# Defining the list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'

}

In [191]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [192]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  MADRID
True
BASEL        3677       1
BELGRADE     1109       2
BUDAPEST      197       0
DEBILT         83       0
DUSSELDORF     38       0
HEATHROW       91       0
KASSEL         16       0
LJUBLJANA      49       0
MAASTRICHT      5       0
MADRID        448       3
MUNCHENB        9       0
OSLO            4       0
STOCKHOLM       4       0
VALENTIA        2       0

# 8. Readjusting Hyperparameters for the RNN Model

In [258]:
epochs = 16
batch_size = 10
n_hidden = 10

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [260]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                        │ (None, 10)                  │             800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 10)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 15)                  │             165 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 965 (3.77 KB)

 Trainable params: 965 (3.77 KB)

 Non-trainable params: 0 (0.00 B)

In [262]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [264]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=2)

Epoch 1/16
1722/1722 - 13s - 7ms/step - accuracy: 0.1036 - loss: 8.9857
Epoch 2/16
1722/1722 - 10s - 6ms/step - accuracy: 0.2011 - loss: 9.1035
Epoch 3/16
1722/1722 - 10s - 6ms/step - accuracy: 0.2702 - loss: 9.4046
Epoch 4/16
1722/1722 - 10s - 6ms/step - accuracy: 0.2780 - loss: 9.7244
Epoch 5/16
1722/1722 - 10s - 6ms/step - accuracy: 0.2884 - loss: 10.0517
Epoch 6/16
1722/1722 - 10s - 6ms/step - accuracy: 0.3233 - loss: 10.3861
Epoch 7/16
1722/1722 - 7s - 4ms/step - accuracy: 0.3756 - loss: 10.7499
Epoch 8/16
1722/1722 - 12s - 7ms/step - accuracy: 0.4324 - loss: 11.2100
Epoch 9/16
1722/1722 - 11s - 6ms/step - accuracy: 0.4985 - loss: 11.5117
Epoch 10/16
1722/1722 - 10s - 6ms/step - accuracy: 0.5112 - loss: 11.9088
Epoch 11/16
1722/1722 - 11s - 6ms/step - accuracy: 0.5601 - loss: 12.1696
Epoch 12/16
1722/1722 - 10s - 6ms/step - accuracy: 0.5771 - loss: 12.2988
Epoch 13/16
1722/1722 - 8s - 4ms/step - accuracy: 0.5779 - loss: 12.3577
Epoch 14/16
1722/1722 - 8s - 5ms/step - accuracy: 0.5876 - loss: 12.6842
Epoch 15/16
1722/1722 - 11s - 6ms/step - accuracy: 0.6067 - loss: 12.9898
Epoch 16/16
1722/1722 - 10s - 6ms/step - accuracy: 0.6237 - loss: 13.3255

# 9. Creating the Confusion Matrix

In [266]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [268]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Pred        BASEL  LJUBLJANA  MADRID
True
BASEL        3673          1       4
BELGRADE     1105          0       6
BUDAPEST      195          0       2
DEBILT         83          0       0
DUSSELDORF     38          0       0
HEATHROW       91          0       0
KASSEL         16          0       0
LJUBLJANA      49          0       0
MAASTRICHT      5          0       0
MADRID        438          0      13
MUNCHENB        9          0       0
OSLO            4          0       0
STOCKHOLM       4          0       0
VALENTIA        2          0       0

# 10. Compiling and Running the CNN Model

In [194]:
epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax'))

C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [195]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_6 (Conv1D)                    │ (None, 14, 32)              │             608 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 14, 16)              │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_6 (MaxPooling1D)       │ (None, 7, 16)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_6 (Flatten)                  │ (None, 112)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 15)                  │           1,695 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,831 (11.06 KB)

 Trainable params: 2,831 (11.06 KB)

 Non-trainable params: 0 (0.00 B)

In [196]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [197]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=2)

Epoch 1/30
1076/1076 - 7s - 7ms/step - accuracy: 0.1201 - loss: 6275.9487
Epoch 2/30
1076/1076 - 6s - 5ms/step - accuracy: 0.1381 - loss: 67545.0625
Epoch 3/30
1076/1076 - 5s - 5ms/step - accuracy: 0.1369 - loss: 223667.0938
Epoch 4/30
1076/1076 - 11s - 10ms/step - accuracy: 0.1354 - loss: 479305.2500
Epoch 5/30
1076/1076 - 9s - 8ms/step - accuracy: 0.1301 - loss: 845609.2500
Epoch 6/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1256 - loss: 1324072.6250
Epoch 7/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1301 - loss: 1914300.0000
Epoch 8/30
1076/1076 - 5s - 5ms/step - accuracy: 0.1300 - loss: 2671083.7500
Epoch 9/30
1076/1076 - 4s - 4ms/step - accuracy: 0.1312 - loss: 3498957.2500
Epoch 10/30
1076/1076 - 6s - 5ms/step - accuracy: 0.1279 - loss: 4567526.0000
Epoch 11/30
1076/1076 - 4s - 3ms/step - accuracy: 0.1301 - loss: 5742869.0000
Epoch 12/30
1076/1076 - 5s - 5ms/step - accuracy: 0.1289 - loss: 7145544.0000
Epoch 13/30
1076/1076 - 5s - 5ms/step - accuracy: 0.1300 - loss: 8720058.0000
Epoch 14/30
1076/1076 - 11s - 10ms/step - accuracy: 0.1297 - loss: 10537992.0000
Epoch 15/30
1076/1076 - 10s - 10ms/step - accuracy: 0.1267 - loss: 12389837.0000
Epoch 16/30
1076/1076 - 4s - 4ms/step - accuracy: 0.1286 - loss: 14569495.0000
Epoch 17/30
1076/1076 - 4s - 4ms/step - accuracy: 0.1257 - loss: 17122374.0000
Epoch 18/30
1076/1076 - 7s - 7ms/step - accuracy: 0.1279 - loss: 19879324.0000
Epoch 19/30
1076/1076 - 11s - 10ms/step - accuracy: 0.1297 - loss: 22904422.0000
Epoch 20/30
1076/1076 - 10s - 9ms/step - accuracy: 0.1251 - loss: 26021366.0000
Epoch 21/30
1076/1076 - 6s - 6ms/step - accuracy: 0.1246 - loss: 29581468.0000
Epoch 22/30
1076/1076 - 11s - 10ms/step - accuracy: 0.1254 - loss: 33419496.0000
Epoch 23/30
1076/1076 - 10s - 9ms/step - accuracy: 0.1244 - loss: 37582628.0000
Epoch 24/30
1076/1076 - 7s - 7ms/step - accuracy: 0.1282 - loss: 42078500.0000
Epoch 25/30
1076/1076 - 8s - 8ms/step - accuracy: 0.1238 - loss: 46670260.0000
Epoch 26/30
1076/1076 - 10s - 10ms/step - accuracy: 0.1264 - loss: 51868776.0000
Epoch 27/30
1076/1076 - 9s - 8ms/step - accuracy: 0.1264 - loss: 57243756.0000
Epoch 28/30
1076/1076 - 4s - 4ms/step - accuracy: 0.1232 - loss: 63408928.0000
Epoch 29/30
1076/1076 - 6s - 6ms/step - accuracy: 0.1292 - loss: 69626024.0000
Epoch 30/30
1076/1076 - 11s - 10ms/step - accuracy: 0.1247 - loss: 76377480.0000

# 11. Creating the Confusion Matrix

In [198]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [199]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL          28        93      1202      36         533       131       8
BELGRADE        0         1       622       0          73         1       0
BUDAPEST        0         0        83       0          10         0       0
DEBILT          0         0        26       0           8         0       0
DUSSELDORF      0         0        10       0           5         1       0
HEATHROW        0         0        13       0           9         1       0
KASSEL          0         0        10       0           2         0       0
LJUBLJANA       0         0        21       0           2         0       0
MAASTRICHT      0         0         2       0           1         0       0
MADRID          0         0        75       0          14        18       0
MUNCHENB        0         0         7       0           0         0       0
OSLO            0         0         0       0           0         0       0
STOCKHOLM       0         0         2       0           0         0       0
VALENTIA        0         0         1       0           0         0       0

Pred        LJUBLJANA  MAASTRICHT  MADRID  MUNCHENB  OSLO  SONNBLICK  \
True
BASEL             150           3     876       105   478          3
BELGRADE            6           0     299         0   109          0
BUDAPEST            0           0      68         0    36          0
DEBILT              0           0      14         0    35          0
DUSSELDORF          1           0      12         0     9          0
HEATHROW            0           0      40         0    28          0
KASSEL              0           0       2         0     2          0
LJUBLJANA           6           0      16         0     4          0
MAASTRICHT          0           0       2         0     0          0
MADRID             11           0     266         0    67          0
MUNCHENB            0           0       1         0     1          0
OSLO                0           0       0         0     4          0
STOCKHOLM           0           0       2         0     0          0
VALENTIA            0           0       1         0     0          0

Pred        STOCKHOLM  VALENTIA
True
BASEL               4        28
BELGRADE            0         0
BUDAPEST            0         0
DEBILT              0         0
DUSSELDORF          0         0
HEATHROW            0         0
KASSEL              0         0
LJUBLJANA           0         0
MAASTRICHT          0         0
MADRID              0         0
MUNCHENB            0         0
OSLO                0         0
STOCKHOLM           0         0
VALENTIA            0         0

# 12. Readjusting Hyperparameters for CNN Model

In [201]:
epochs = 16
batch_size = 10
n_hidden = 10

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh'))

C:\Users\andyc\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [202]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_7 (Conv1D)                    │ (None, 14, 10)              │             190 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 14, 16)              │             176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_7 (MaxPooling1D)       │ (None, 7, 16)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_7 (Flatten)                  │ (None, 112)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 15)                  │           1,695 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,061 (8.05 KB)

 Trainable params: 2,061 (8.05 KB)

 Non-trainable params: 0 (0.00 B)

In [203]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [204]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=2)

Epoch 1/16
1722/1722 - 8s - 5ms/step - accuracy: 0.4794 - loss: 24.2751
Epoch 2/16
1722/1722 - 12s - 7ms/step - accuracy: 0.5254 - loss: 24.1883
Epoch 3/16
1722/1722 - 10s - 6ms/step - accuracy: 0.5188 - loss: 24.6069
Epoch 4/16
1722/1722 - 9s - 5ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 5/16
1722/1722 - 11s - 6ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 6/16
1722/1722 - 10s - 6ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 7/16
1722/1722 - 5s - 3ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 8/16
1722/1722 - 14s - 8ms/step - accuracy: 0.4783 - loss: 27.1354
Epoch 9/16
1722/1722 - 10s - 6ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 10/16
1722/1722 - 10s - 6ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 11/16
1722/1722 - 10s - 6ms/step - accuracy: 0.4783 - loss: 27.1354
Epoch 12/16
1722/1722 - 10s - 6ms/step - accuracy: 0.4783 - loss: 27.1354
Epoch 13/16
1722/1722 - 5s - 3ms/step - accuracy: 0.4783 - loss: 27.1354
Epoch 14/16
1722/1722 - 7s - 4ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 15/16
1722/1722 - 11s - 7ms/step - accuracy: 0.4783 - loss: 27.1353
Epoch 16/16
1722/1722 - 10s - 6ms/step - accuracy: 0.4783 - loss: 27.1353

# 13. Creating the Confusion Matrix

In [206]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [207]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        BASEL  BELGRADE  BUDAPEST  DUSSELDORF  KASSEL  MAASTRICHT  \
True
BASEL        2038       890       335          22      18         368
BELGRADE      484       614         0           0       0          13
BUDAPEST       85       112         0           0       0           0
DEBILT         38        45         0           0       0           0
DUSSELDORF     15        23         0           0       0           0
HEATHROW       46        44         0           0       0           1
KASSEL          7         9         0           0       0           0
LJUBLJANA      20        29         0           0       0           0
MAASTRICHT      2         3         0           0       0           0
MADRID        246       170         2           1       0          32
MUNCHENB        0         9         0           0       0           0
OSLO            0         4         0           0       0           0
STOCKHOLM       0         4         0           0       0           0
VALENTIA        0         2         0           0       0           0

Pred        STOCKHOLM
True
BASEL               7
BELGRADE            0
BUDAPEST            0
DEBILT              0
DUSSELDORF          0
HEATHROW            0
KASSEL              0
LJUBLJANA           0
MAASTRICHT          0
MADRID              0
MUNCHENB            0
OSLO                0
STOCKHOLM           0
VALENTIA            0